### PR TITLE
Use async call for "Edit image in external tool". Fixes #806

### LINKED ISSUE #806: Synfig freezes when "Edit image in external tool" command activated
@ankit-kumar-dwivedi I've just found one more issue in implementation of  #516.
After I choose "Edit image in external tool" command editor application gets opened, but Synfig gets unresponsive until I close the editor app. It would be better to allow user work in Synfig while editor app open.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72507316-synfig-freezes-when-edit-image-in-external-tool-command-activated?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
Replaced spawn_command_line_sync() with spawn_command_line_async()

@morevnaproject please review :)

### CODE REVIEW

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Can I start working on vectorization project?

**Comment by morevnaproject** [comment]
Testing now ^__^

**Comment by morevnaproject** [comment]
> Can I start working on vectorization project?

Yes!

**Comment by morevnaproject** [comment]
I have tested on Linux and it works perfectly! Need some time to test on OSX...

**Comment by ankit-kumar-dwivedi** [comment]
> I have tested on Linux and it works perfectly! I need some time to test on OSX...

Yes sure Sir :smiley: 

> > Can I start working on vectorization project?
> 
> Yes!

Great! I am excited [^_ ^]. I am finding similarities and differences  between opentoonz raster/ layer_bitmap and opentoonz vector/paste_canvas group

**Comment by morevnaproject** [comment]
Tested on OSX and it works there as well!

**Pull request merged**
