### PR TITLE
markers-for-waypoints

### PR DESCRIPTION
**Pull request by amanbora**
@morevnaproject can you pls review this pr. I'm unable to see the changes in the build version. Thanks

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hi @amanbora !
I compiled your code and I can see changes in Graphs panel - now there are a gaps appear in time cursor as if it covered by some fill (marked with red on screenshot):

screenshot_002

Right now your code is injected into part which draws curves (i.e. it executes when every segment of curve is drawn).

You need to draw markers only at those points, where waypoints existing. So, the code for drawing markers should be in separate "for" loop.  For reference, see code for drawing keyframe marks in Graphs Panel -

https://github.com/synfig/synfig/blob/6eafe8e0af292b65c2dd7d39822b7531da045bdc/synfig-studio/src/gui/widgets/widget_curves.cpp#L386-L398

**Comment by amanbora** [comment]
Thanks @morevnaproject I'll continue working on it. ^_^

**Comment by amanbora** [comment]
@morevnaproject I'm having the following issue while building although i have the latest version of glibmm and gtk installed.
Screenshot 2019-04-07 at 1 57 21 PM

**Comment by morevnaproject** [comment]
Please let me know what is your OS?

**Comment by amanbora** [comment]
@morevnaproject mac os 10.14.2

**Comment by morevnaproject** [comment]
Did you run ```1-setup-osx-brew.sh```?

**Comment by amanbora** [comment]
Yes
Screenshot 2019-04-07 at 11 01 19 PM

**Comment by amanbora** [comment]
@morevnaproject can I send a pre-proposal so that you could review it and i can implement the necessary changes

**Comment by amanbora** [comment]
[pre-proposal.pdf](https://github.com/synfig/synfig/files/3053997/pre-proposal.pdf)
Can you please review my proposal for GSOC. ^_^

**Comment by ice0** [comment]
Can you show output?
`brew info glibmm`

**Comment by morevnaproject** [comment]
@amanbora Can you please submit your proposal draft as Google Doc via https://summerofcode.withgoogle.com/ ?

**Comment by amanbora** [comment]
@ice0 
Screenshot 2019-04-08 at 10 13 47 PM

**Comment by amanbora** [comment]
@morevnaproject done

**Comment by morevnaproject** [comment]
Looks like we have incompatibility with glibmm 2.60... Investigating...

**Comment by morevnaproject** [comment]
@amanbora I have pushed fix to master branch (4738a94ea9fbebe1c225b2b61ae0dfb116afe2a7). Please check if compilation works on your MacOS machine now. ^__^

**Comment by amanbora** [comment]
I'm getting this 
Screenshot 2019-04-11 at 2 13 39 PM

**Comment by morevnaproject** [comment]
@amanbora Please try to remove  "/home/aman/Desktop/synfig/_debug" directory. After that run ```./2-build-debug.sh" script again.

P.S. It would be nice if you can provide your error messages as text output. You can use https://gist.github.com/ for uploading them, as @AnishGG does here - https://github.com/synfig/synfig/issues/794#issuecomment-482107585 ^__^

**Comment by amanbora** [comment]
https://gist.github.com/amanbora/05650d49468d2db7d777486fd5c5ec03.js here you go  ^_^

**Comment by amanbora** [comment]
@morevnaproject pls review my pr, I think I'm almost there..

**Comment by morevnaproject** [comment]
@amanbora When trying to build your branch I get the following error - 

```
make[3]: Entering directory '/home/konstantin/sources/synfig/_production/synfig-studio/src/gui'
g++ -DHAVE_CONFIG_H -I. -I/home/konstantin/sources/synfig/synfig-studio/src/gui -I../..  -I/home/konstantin/sources/synfig/synfig-studio/src  -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -pthread -D_REENTRANT -I/home/konstantin/sources/synfig/synfig-core/src -I/home/konstantin/sources/synfig/ETL -I/home/konstantin/sources/synfig/_production/build/include/ETL -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/OpenEXR -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/mlt++ -I/usr/include/mlt -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DIMAGE_DIR=\"/home/konstantin/sources/synfig/_production/build/share/pixmaps/synfigstudio\" -DIMAGE_EXT=\"png\" -DPLUGIN_DIR=\"/home/konstantin/sources/synfig/_production/build/share/synfig/plugins\" -DSOUND_DIR=\"/home/konstantin/sources/synfig/_production/build/share/synfig/sounds\" -DLOCALEDIR=\"/home/konstantin/sources/synfig/_production/build//locale\" -fdiagnostics-color=always -O2 -DNDEBUG -MT widgets/synfigstudio-widget_curves.o -MD -MP -MF widgets/.deps/synfigstudio-widget_curves.Tpo -c -o widgets/synfigstudio-widget_curves.o `test -f 'widgets/widget_curves.cpp' || echo '/home/konstantin/sources/synfig/synfig-studio/src/gui/'`widgets/widget_curves.cpp
/home/konstantin/sources/synfig/synfig-studio/src/gui/widgets/widget_curves.cpp:48:9: fatal error: synfig/valuenodes/ValueNode_Animated.h: No such file or directory
 #include<synfig/valuenodes/ValueNode_Animated.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:2842: recipe for target 'widgets/synfigstudio-widget_curves.o' failed
make[3]: *** [widgets/synfigstudio-widget_curves.o] Error 1
make[3]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-studio/src/gui'
Makefile:448: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-studio/src'
Makefile:718: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-studio'
Makefile:533: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by morevnaproject** [comment]
Regarding your compilation error (https://github.com/synfig/synfig/pull/803#issuecomment-482025268): please execute the following command and give me its output:

```
cd /home/aman/Desktop/synfig/ && git status && git log -n 2
```

**Comment by amanbora** [comment]
@morevnaproject 
```
Amans-MBP:synfig aman$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Amans-MBP:synfig aman$ git log -n 2
commit d8f7cd822dd08ea30fb392029c6be3918cb92a73 (HEAD -> master, origin/master, origin/HEAD)
Author: aman <aman@github.com>
Date:   Sat Apr 13 16:03:47 2019 +0530

    header-file-updated

commit 287ca23dda03c83b9f4251aebff63b91c6f0d4cb
Merge: e63d8cb7d 4738a94ea
Author: aman <aman@github.com>
Date:   Sat Apr 13 16:00:08 2019 +0530

    edits
```

**Comment by morevnaproject** [comment]
@amanbora Okay, please give me an output of the following commands:

```
ls /Users/aman/Desktop/synfig/_debug/build/include/ETL/ETL
```

```
brew info gcc
```

```
g++ --version
```

**Comment by amanbora** [comment]
```

Amans-MBP:synfig aman$ ls /Users/aman/Desktop/synfig/_debug/build/include/ETL/ETL
_angle.h			_surface.h
_bezier.h			_thread.h
_bezier_angle.h			_trivial.h
_boxblur.h			_value.h
_bspline.h			angle
_calculus.h			bezier
_clock_base.h			boxblur
_clock_gettimeofday.h		calculus
_clock_system.h			clock
_clock_win32hpcount.h		etl_config.h
_condition.h			etl_profile.h
_curve.h			fastangle
_curve_func.h			fixed
_fastangle.h			gaussian
_fastangle_tables.h		handle
_fixed.h			hermite
_gaussian.h			ipc
_handle.h			misc
_hermite.h			mutex
_misc.h				pen
_mutex_null.h			random
_mutex_pthreads.h		rect
_mutex_pthreads_simple.h	ref_count
_mutex_win32.h			smach
_pen.h				smart_ptr
_random.h			spline
_rect.h				status
_ref_count.h			stringf
_rwlock.h			surface
_smach.h			thread
_smart_ptr.h			trivial
_status.h			value
_stringf.h


```

**Comment by amanbora** [comment]
`Amans-MBP:synfig aman$ brew info gcc
gcc: stable 8.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/8.2.0 (1,413 files, 295.9MB) *
  Poured from bottle on 2019-04-03 at 13:09:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 84,007 (30 days), 246,959 (90 days), 777,826 (365 days)
install_on_request: 40,241 (30 days), 118,083 (90 days), 375,956 (365 days)
build_error: 0 (30 days)`

**Comment by amanbora** [comment]
`Amans-MBP:synfig aman$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by amanbora** [comment]
Hey @morevnaproject, I am unable to work on the issue due to exams, but will soon be over with them. I'll be back at them asap..

**Comment by ankit-kumar-dwivedi** [comment]
Hello @morevnaproject any help needed? Let us know if you are stuck on something

**Comment by morevnaproject** [comment]
The implementation is done in #982. Closing.

**Pull request closed without merging**
