### PR TITLE
Replace deprecated set_margin method

### PR DESCRIPTION
**Pull request by FirasH**
set_margin_left() and set_margin_right() are now deprecated.
Using set_margin_start() and set_margin_end() instead.

### CODE REVIEW

**Comment by rodolforg** [comment]
These methods are in GTKmm since 3.12 (april 2014).
Is it ok? :) @morevnaproject  @ice0

**Comment by FirasH** [comment]
In Synfig Studio there are various places where deprecated methods w.r.t. the current stable gtkmm are used.
Maybe we should set a minimum gtk version and slowly update the code?

**Comment by ice0** [comment]
> Maybe we should set a minimum gtk version and slowly update the code?
I will check minimum required version/

**Comment by rodolforg** [comment]
OK.

- GTK 3.12 was released march'14 https://ftp.gnome.org/pub/gnome/sources/gtk+/3.12/
- GTKmm 3.12 april'14 https://ftp.acc.umu.se/pub/gnome/sources/gtkmm/3.12/

- GTK 3.14 was released september'14 https://ftp.gnome.org/pub/gnome/sources/gtk+/3.14/
- GTKmm 3.14 too https://ftp.acc.umu.se/pub/gnome/sources/gtkmm/3.14/

**Comment by rodolforg** [comment]
Old Debian 8 (Jessie) has 3.14 https://packages.debian.org/search?searchon=sourcenames&keywords=gtkmm3
Old Ubuntu 16.04 (Xenial) 3.18 https://packages.ubuntu.com/source/xenial/gtkmm3.0

**Comment by rodolforg** [comment]
Some distros: https://pkgs.org/search/?q=gtkmm

**Comment by rodolforg** [comment]
@FirasH please squash both commits :)

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
