### PR TITLE
feat: eyedropper tool now takes fill color instead of outline color by default

### LINKED ISSUE #2899: Eyedrop Tool should take fill color by default
screenshot_005

Currently Eyedrop Tool has the following behavior in master branch:
- click on workarea picks color and puts it into the  **OUTLINE** color
- Ctrl+click  on workarea picks color and puts it into the  **FILL** color

I suggest to swap this behavior:
- click on workarea picks color and puts it into the **FILL** color
- Ctrl+click  on workarea picks color and puts it into the **OUTLINE** color

screenshot_006

### PR DESCRIPTION
**Pull request by mohamedAdhamc**
Fixes #2899 
not sure if this is a "refactor" or a "feature". Anyways, pretty straightforward reordereding of condition statement.

### CODE REVIEW

**Review by rodolforg — CHANGES_REQUESTED** [review]
You have to change the text in the Tool Options panel

**Comment by mohamedAdhamc** [comment]
> You have to change the text in the Tool Options panel

oops forgot about this, done.

**Review by rodolforg — APPROVED** [review]

**Comment by ice0** [comment]
> not sure if this is a "refactor" or a "feature". Anyways, pretty straightforward reordereding of condition statement.

There is an easy rule for this:

If you want to see this change in the changelog (so that users can read about it), use the `feature` prefix.
If this is an internal change and does not affect users, use the `refactor` prefix.

**Comment by ice0** [comment]
P.S. I changed the PR title and put it back just to run newly added style check.

**Comment by rodolforg** [comment]
We should squash both commits here to a single one

**Comment by ice0** [comment]
> We should squash both commits here to a single one

I will squash them on merge.

**Comment by mohamedAdhamc** [comment]
> There is an easy rule for this:
> 
> If you want to see this change in the changelog (so that users can read about it), use the `feature` prefix. If this is an internal change and does not affect users, use the `refactor` prefix.

Makes sense, thanks :)

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
