### PR TITLE
fix: setting filename parameter of Layer Sound corrupts file

### LINKED ISSUE #2757: Synfig [2022.07.12-linux64-19589] damages file after saving
**Describe the bug**
Error with this Synfig build - [SynfigStudio-1.5.1-testing-2022.07.12-linux64-19589.appimage](https://cloud.morevnaproject.org/s/BWTYjKSya8ZyJQL)

When saving file it cannot be opened again anymore.

Video -
https://www.youtube.com/watch?v=QAnhMPDGp2c

**To Reproduce**
1. Download sample file - [Synfig-22-final-03.sif](https://forums.synfig.org/uploads/short-url/6HAYqRETUIYRx6aclxuQdI0nqNX.sif) and open it in Synfig.
2. Make some changes to file.
3. Save and close the file.
4. Try to open file again -> it shows an error.

**Screenshots**
screenshot_001

**System information:**
 - OS: Linux Mint 19
 - OS version: Linux Mint 19
 - Commit ID: 19589

### PR DESCRIPTION
**Pull request by rodolforg**
Fix #2757

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by morevnaproject** [comment]
It works perfectly now, thank you so much! ^__^

**Comment by rodolforg** [comment]
If #2727 will be backported to 1.4.3, this one needs to be too.

**Comment by morevnaproject** [comment]
#2727 doesn't affects 1.4.x branch, so no backporting.

**Pull request merged**
