### PR TITLE
feat: add Show Canvas External Dependencies dialog

### PR DESCRIPTION
**Pull request by rodolforg**
Now user can see, via Show > View Dependencies, what files current
canvas depends on.

PS: This PR is another (indirect) step to help fixing #1393 that is
being handled in #2086

### CODE REVIEW

**Comment by rodolforg** [comment]
Captura de tela de 2021-12-23 11-37-26

**Comment by rodolforg** [comment]
Hm... I added some icons now. Feel free for squash XD

Captura de tela de 2021-12-23 12-48-56

**Comment by rodolforg** [comment]
Force-pushed because AppVeyor stalled

**Comment by morevnaproject** [comment]
This is so cool! Testing now...

**Comment by morevnaproject** [comment]
Hi! I have found one issue with this test set - 
[2472.zip](https://github.com/synfig/synfig/files/8192523/2472.zip)

- Unpack the archive and open `file.sif`.
- Choose "File" -> "View Dependencies".
- One item in the list doesn't have a name -
screenshot_001


Other minor notes:
- It would be nice if dialog will have larger width/height when opened.
- I suggest to replace "View Dependencies" to "Show Dependencies..."

Thank you!

**Comment by rodolforg** [comment]
> One item in the list doesn't have a name -

Hm... I found out the reason: the `Y-axis` of `Origin` of exported `t-parent`. I'll hide not named valuenodes, because they'll only exist if they're under/in an external exported (=named) valuenodes.



> * It would be nice if dialog will have larger width/height when opened.

Done

> * I suggest to replace "View Dependencies" to "Show Dependencies..."

Done

----
Finally, I rebased and squashed both commits.

**Comment by rodolforg** [comment]
(rebased)

**Review by morevnaproject — DISMISSED** [review]
Hi! It looks good to me now! I took an initiative to move "Show Dependencies" entry to the place near import-related commands.

screenshot_001


Waiting for CI checks to complete and it is ready for merge!

**Review by morevnaproject — APPROVED** [review]

**Pull request merged**
