### PR TITLE
[Release] Version 1.5.0 (development)

### PR DESCRIPTION
**Pull request by morevnaproject**
I finally managed to build binary packages for all platforms from master branch.
That means we're ready to release development version of Synfig with all latest changes! :tada: :boom: :boom: :boom:

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by morevnaproject** [comment]
Packages:
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2021.08.13-linux32-32dd4.appimage
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2021.08.13-linux64-32dd4.appimage
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2021.08.13-win32-32dd4.exe
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2021.08.13-win32-32dd4.zip
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2021.08.13-win64-32dd4.exe
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2021.08.13-win64-32dd4.zip
- [SynfigStudio-1.5.0-20210813.dmg](https://cloud.morevnaproject.org/s/rqjtC7jegqYStfH)

**Comment by morevnaproject** [comment]
Now I need to write a quick (non-detailed) summary of all changes in this development build and we're ready for release. ^__^

**Comment by morevnaproject** [comment]
Here is my draft document - https://docs.google.com/document/d/1CIOnaHJh9zUTd1nsuqQQiQXqOksUd-Fjsj5oJ6dXlnA/edit?usp=sharing

If I have missed some big feature - please comment. ^__^

**Comment by rodolforg** [comment]
Not that big as those you listed, but here is some for your analysis:

https://github.com/synfig/synfig/pull/2012
https://github.com/synfig/synfig/issues/2240
https://github.com/synfig/synfig/pull/1330
https://github.com/synfig/synfig/pull/1483
https://github.com/synfig/synfig/pull/1507
https://github.com/synfig/synfig/pull/1585
https://github.com/synfig/synfig/pull/1789
https://github.com/synfig/synfig/pull/1872

**Comment by morevnaproject** [comment]
Thank you, this helps a lot! I have updated release notes document now. ^__^

**Comment by morevnaproject** [comment]
https://synfig.readthedocs.io/en/latest/releases/development/1.5.0.html

**Comment by morevnaproject** [comment]
https://www.synfig.org/2021/08/16/synfig-studio-1-5-0-released/

**Pull request merged**
