### PR TITLE
loadcanvas: fix loading of some non-value nodes lists

### LINKED ISSUE #2481: Importing an .svg drawing corrupts the animation file
**Describe the bug**
Importing the attached .svg [drawing](https://github.com/synfig/synfig/files/7792403/Oculus.zip)  corrupts the animation file.

If that can help, [here](https://github.com/synfig/synfig/files/7792442/currupted-animation.zip) is my corrupted file.

**To Reproduce**
1. Create a new animation and import the attached .svg drawing
2. Save and close the animation
3. Reopen the animation

Synfig throws a bunch of errors with many Unexpected elements.

**Expected behavior**
Seamless reopening of the animation file.

**System information:**
 - OS: Windows
 - OS version: 10
 - Commit ID: 52a105a

### PR DESCRIPTION
**Pull request by rodolforg**
fix #2481 (Importing an .svg drawing corrupts the animation file)

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
Maybe backport it?

**Comment by ice0** [comment]
@rodolforg 
1.4.2 and 1.5.1 work without problems. They do not display the svg correctly, but it looks like we need all SVG changes to be backported in that way.

**Comment by rodolforg** [comment]
Oh, but this PR is not specific for SVG stuff.
Any list that is not a value node (static_list, dynamic_list, bline, etc.) suffers here. :)

**Comment by morevnaproject** [comment]
Backported :+1:

**Pull request merged**
