### PR TITLE
[CMake] Bump minimum required CMake version to 3.5

### PR DESCRIPTION
**Pull request by ice0**
Actually we need version 3.1 at the moment

### CODE REVIEW

**Comment by Keyikedalube** [comment]
I'm curious why synfig has `cmake_minimum_required()` set both in the root and subdirectory? Shouldn't the root one be enough?
```
(root) synfig-core/CMakeLists.txt
    |___ synfig-core/src/CMakeLists.txt

(root) synfig-studio/CMakeLists.txt
    |___ synfig-studio/src/CMakeLists.txt
```

**Comment by ice0** [comment]
> I'm curious why synfig has `cmake_minimum_required()` set both in the root and subdirectory? Shouldn't the root one be enough?

Agree. Removed extra lines.

**Comment by ice0** [comment]
@Keyikedalube @FirasH @rodolforg 

Guys, please approve the PRs, which you think is ok to be merged. This will help a lot.

**Review by Keyikedalube — APPROVED** [review]

**Comment by FirasH** [comment]
I honestly have no idea about how `cmake` works and how should be set up.
Anyway looking at the code seems fine to me and better than before as we're referencing the same `cmake` version everywhere in the code.

**Review by FirasH — APPROVED** [review]

**Comment by Keyikedalube** [comment]
@FirasH I think ice0 meant not only this but the other PRs also. More eyes scanning the code would greatly help project maintainers :)

**Review by rodolforg — APPROVED** [review]

**Pull request merged**
