### PR TITLE
refactor: prefer prefix ++ operators for non-primitive types

### PR DESCRIPTION
**Pull request by rodolforg**
And prefer the style of the `for` loop as discussed in the forums https://forums.synfig.org/t/trying-to-define-our-code-style/13097.
```c++
for (int a = 0; a < 30; ++a) {
}
```
(spaces surrounding operators, spaces after `(` and `;`, and bracket layout)

### CODE REVIEW

**Comment by rodolforg** [comment]
Maybe there are more, but I think I should stop here to avoid a large PR that is difficult to review.

**Review by ice0 — DISMISSED** [review]

**Comment by ice0** [comment]
@rodolforg 
Looks good, can you check codacy warnings?

**Comment by rodolforg** [comment]
image


Can I replace  `; prev = iter, iter++, ++next, ++current` with `; prev = iter++, ++next, ++current`, right?

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
