### PR TITLE
Travis: Add distcheck job

### PR DESCRIPTION
**Pull request by morevnaproject**
We have a script that makes "distcheck" operation and generates source tarballs - https://github.com/synfig/synfig/blob/master/autobuild/synfigstudio-release.sh

Often "distcheck" returns additional errors, even when when other build tasksare successful.

For example, currently it gives following error for ETL:
```
g++ -DHAVE_CONFIG_H -I. -I../../../test -I../ETL  -I../../.. -I../ETL  -W -Wall -O2 -DNDEBUG -I../../.. -I../ETL -W -Wall -O2 -DNDEBUG -MT smach.o -MD -MP -MF .deps/smach.Tpo -c -o smach.o ../../../test/smach.cpp
../../../test/smart_ptr.cpp: In function ‘int loose_smart_ptr_test()’:
../../../test/smart_ptr.cpp:259:7: error: ‘loose_smart_ptr’ is not a member of ‘etl’
  etl::loose_smart_ptr<my_test_obj> obj_smart_ptr_loose;
```

### CODE REVIEW

**Comment by ice0** [comment]
Travis build can't find `./travis.sh: line 39: ./build/synfigstudio-release.sh: No such file or directory`

**Comment by morevnaproject** [comment]
Fixed now. Thank you!

**Comment by morevnaproject** [comment]
Okay, in this branch I also fixed all issues shown by `distcheck`. Should pass CI checks now...

**Comment by ice0** [comment]
Ok, looks good to me.

**Pull request merged**
