### PR TITLE
Create sound panel - fix #783

### LINKED ISSUE #783: Create a new Panel which displays sound waveform
Many people request to have an ability to load a sound file and display its waveform in sync with animation.

Synfig already can import sounds, but can't display waveform.

I suggest to add a new panel, similar to Graphs Panel, but instead of displaying parameter graphs it will display a waveform of given file.

Example mockup:

screenshot_003

1 - Waveform
2 - Button to load file. 
3 - Timeline
4 - Current time cursor

Expected workflow:
User click the button and choosing a file. After that waveform for selected file is displayed in this panel. At the top of the panel you can see a timeline (just like in Graphs Panel), and waveform should be synchronized to it. Just like in Graphs Panel, user can hover cursor over timeline and change scale by scrolling mouse wheel. This also changes scale of waveform view.

Related links:
- https://wiki.synfig.org/Graphs_Panel
- https://wiki.synfig.org/Dev:Adding_a_Panel_-_Part_I
- Waveform generation code in "rainynite-studio" app by @caryoscelus - https://github.com/caryoscelus/rainynite-studio/blob/master/studio/canvas/editors/waveform.cpp

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/71840878-create-a-new-panel-which-displays-sound-waveform?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rodolforg**
fix #783 
* [x] create dock
* [x] create basic waveform widget
* [x] can load (button and drag-drop)/unload file
* [x] can zoom waveform and pan time
* [x] let user set a sound delay (positive or negative)
* [x] let user choose what sound channel to show

### CODE REVIEW

**Comment by rodolforg** [comment]
Oh well, it should in draft mode…
It works however.

**Comment by morevnaproject** [comment]
It looks awesome!!!
screenshot_003

**Comment by rodolforg** [comment]
I hope it's done now.

I did some tests and they all succeeded:
* load a sound file and change delay and channel parameters
* clear
* load another sound file and change delay and channel parameters (they should be reset to default)
* open a synfig file (sound panel should be clear)
* load a sound file and change delay and channel parameters
* switch tab and check if it doesn't affect other file tab parameter GUI elements

If there are some GUI stuff to fix, please tell me before merge ;)

**Comment by rodolforg** [comment]
I'm considering to add another way to load sound: from available sound layers in file/workarea.
But how would it the GUI be? :/

**Comment by morevnaproject** [comment]
> I'm considering to add another way to load sound: from available sound layers in file/workarea.

I think this is absolutely awesome idea!

> But how would it the GUI be? :/

I suggest to put dropdown list instead of this widget -
screenshot_006

Dropdown list will list all sound files imported as sound layers.

P.S. I plan to merge this PR tomorrow, so I suggest to put further improvements of this feature in separate PR. ^__^

**Comment by rodolforg** [comment]
> Dropdown list will list all sound files imported as sound layers.

But how could an user choose another sound file that is not in a sound layer?

**Comment by morevnaproject** [comment]
Merged via e973e8ffed3f9cfbb8e133de1b61086603bd885a. Thank you very much!

**Comment by morevnaproject** [comment]
> But how could an user choose another sound file that is not in a sound layer?

Then, I suggest to add "Open" button, right after the dropdown list. 
Pressing this button will import new sound as Sound Layer and make this layer selected in dropdown list of Sound Panel. How about this?

**Pull request closed without merging**
