### PR TITLE
refactor: list document actions in a std::vector to better readability

### PR DESCRIPTION
**Pull request by rodolforg**
(I suppose)

### CODE REVIEW

**Review by Keyikedalube — APPROVED** [review]
61 lines of duplicated code eliminated. Kinda clever

Readability? I suppose too ;-)
If we pay attention to what struct members are then that's fine but I did initially got lost inside the vector brace. Definitely not human-friendly readable LOL

**Comment by rodolforg** [comment]
> Definitely not human-friendly readable LOL

It is more readable when not in a diff view lol

Force-pushed to fix what Codacy pointed.

**Review by Keyikedalube — APPROVED** [review]

**Comment by Keyikedalube** [comment]
Uh... do PRs now have to pass all tests mandatorily?

**Comment by rodolforg** [comment]
Hm.. no, but we try to. And those were good suggestions

**Pull request merged**
