### PR TITLE
[Lottie Exporter] Add support for reciprocal convert method

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Added support for Reciprocal convert method
@AnishGG please review ^__^

### CODE REVIEW

**Comment by AnishGG** [comment]
@saurabh-ramola please resolve the conflicts here. ^__^

**Comment by saurabh-ramola** [comment]
> There are some LGTM warnings. Please look at them. ^__^
> Otherwise, the PR works good.
> Great work!

Done :smiley:

**Comment by morevnaproject** [comment]
TODO: Remove ATF flag on relevant test after this PR will be merged. See https://gitlab.com/synfig/synfig-tests/-/commit/05f12241914c6c0d5db49e5a5ea1cb254c21b9c1

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
