### PR TITLE
[Lottie Exporter] Add support for range convert method

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Added support for `range` convert method.
@AnishGG , please check ^__^

### CODE REVIEW

**Comment by saurabh-ramola** [comment]
@morevnaproject @AnishGG , in using `range` convert , the user can set `min` > `max` which is counter-intuitive. I feel that should not be allowed.

**Comment by AnishGG** [comment]
> @morevnaproject @AnishGG , in using `range` convert , the user can set `min` > `max` which is counter-intuitive. I feel that should not be allowed.

Yep, I agree.
@ice0 , @rodolforg your views. ^__^

**Comment by rodolforg** [comment]
> > @morevnaproject @AnishGG , in using `range` convert , the user can set `min` > `max` which is counter-intuitive. I feel that should not be allowed.
> 
> Yep, I agree.
> @ice0 , @rodolforg your views. ^__^

Well, it is. But IMHO if Synfig support it... Lottie exporting should do it (maybe inverting them)

**Comment by morevnaproject** [comment]
> IMHO if Synfig support it... Lottie exporting should do it

I agree that  it should behave the same as in Synfig ^__^

**Comment by saurabh-ramola** [comment]
> > IMHO if Synfig support it... Lottie exporting should do it
> 
> I agree that it should behave the same as in Synfig ^__^

Alright, I have mirrored what Synfig does in this PR.

**Comment by morevnaproject** [comment]
TODO: Remove ATF flag on relevant test after this PR will be merged. See https://gitlab.com/synfig/synfig-tests/-/commit/05f12241914c6c0d5db49e5a5ea1cb254c21b9c1

**Comment by ice0** [comment]
@saurabh-ramola please rebase

**Comment by saurabh-ramola** [comment]
> @saurabh-ramola please rebase

Done :smiley:

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
