### PR TITLE
Limit background rendering to playback bounds

### LINKED ISSUE #1719: Don't render animation outside playback bounds
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
1. Set the playback bounds
2. Turn on Render feature

Screenshot from 2020-09-30 16-56-05

Rendering all sides of the timeline is a bottleneck for long-duration animation. I'd love Synfig to be more efficient by rendering only those regions between left and right bound. That'll save up more resources and improve user's productivity too.

### PR DESCRIPTION
**Pull request by FirasH**
Fix #1719

### CODE REVIEW

**Review by FirasH — COMMENTED** [review]
Not wonderful to look at...
Any suggestions are welcome.

**Comment by Keyikedalube** [comment]
Pulled and tried out your updates. Works as expected.

Can't help with code :( But thanks for the fix :)

BTW, you need to use brace for `if` block I think. Got this warning message while building:
Screenshot from 2020-11-16 06-14-44

**Comment by ice0** [comment]
@FirasH please check Deepcode warning.

**Comment by FirasH** [comment]
Cleaned a bit, now it's fairly straightforward.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
