### PR TITLE
Fix typos and non translatable strings

### LINKED ISSUE #1158: Some strings are not translatable in the .po files
There are some strings that cannot be translated because they are missing in the .po translation files.

In this Issue I will report the strings that need to be reviewed in the code:
- The dialog at: File > Preview...
- The dialog at: Canvas > Options...
- The dialog at: Layer > Convert to Vector (when a raster image is selected)
- The dialog at: Window > Workspace > Edit workspaces...
- From File > Preferences... > Editing, open the dialog "Choose..." to select the external Image Editor (#1159, fixed)
- The tooltip at: File > Preferences... > Editing, hover the mouse pointer above "Choose..." button (#1159, fixed)

If I find new strings I'll report them here.
I took a look at the code and from what I understood we need to add an underscore "_" to make the string available in the .po files, is that correct?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/88398312-some-strings-are-not-translatable-in-the-po-files?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by FirasH**
Fixes #1158  (does not include ` REGISTER_VALUENODE` strings)

This pull request includes fixes to various typos and makes translatable the list of operations that can be applied to a node (right-click menu on items parameter) and rendering modes.

### CODE REVIEW

**Comment by ice0** [comment]
Ok, thank you!

@blackwarthog found why code is not compiling after changes in localization.
The main problem in code inside `REGISTER_VALUENODE`. We can't fix this quickly, so here are 2 solutions:
1. remove `_()` from `REGISTER_VALUENODE` and i will merge changes, or
2. wait until the problem will be fixed, and i will merge your changes after what.

**Comment by FirasH** [comment]
@ice0 at this point there is no hurry to include those changes, it depends on the complexity of the required changes.

**Comment by FirasH** [comment]
@ice0 the changes related to `REGISTER_VALUENODE` have been reverted.
I'll open a new issue so we can merge those changes into master.

**Comment by ice0** [comment]
Awesome!

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
