### PR TITLE
fix(lang): Spanish translation typo

### PR DESCRIPTION
**Pull request by pgilfernandez**
Simple typo fixed in the Spanish translation file

### CODE REVIEW

**Review by rodolforg — APPROVED** [review]

**Comment by ice0** [comment]
Hi, Pablo!

Thanks for the PR. We are using Transifex as our primary source for translations, so I need to check if I can merge it without modifications in Transifex.

@morevnaproject 
Can I merge it as-is, or should this be fixed on Transifex first?

**Comment by morevnaproject** [comment]
Yes, we should fix that on Transifex, otherwise it will be lost after next sync with Transifex.

**Comment by ice0** [comment]
> Yes, we should fix that on Transifex, otherwise it will be lost after next sync with Transifex.

What if I merge this PR, and fix it on Transifex? Will this cause a merge conflict?

**Comment by morevnaproject** [comment]
> What if I merge this PR, and fix it on Transifex? Will this cause a merge conflict?

I have made changes to Transifex (to both development and stable branches). No merge conflicts will be after merge.

**Review by morevnaproject — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
