### PR TITLE
Revert "fix sync scrolling of params and timetrack"

### PR DESCRIPTION
**Pull request by morevnaproject**
Reverts commit aeb01c14cafdb409f5a67a865a5ad8b5fa06b0b7.

This applies fix for issue #1442 to master branch.

Actually, we need to check if #1442 takes place on master (for this we have to build packages and test). It is possible the issue is not takes place on master because of new timetrack.

Also, commit aeb01c14cafdb seems to be fixing several things at once. Maybe we should split it into parts?

### CODE REVIEW

**Comment by morevnaproject** [comment]
> Actually, we need to check if #1442 takes place on master (for this we have to build packages and test)

@ice0 @Svarov-RZM @FadhilKwan Can you please check this build? - 
[SynfigStudio-1.5.0-testing-2020.06.20-win64-60bf6.zip (108.2 MB)](https://archive.morevnaproject.org/s/mX9Y9Z47CYJGwRK/download) 

Does it crashes the same way as in issue #1442 (when selecting spline)?

**Comment by Svarov-RZM** [comment]
> Does it crashes the same way as in issue #1442 (when selecting spline)?

Yeah, version 1.5.0 also crashes the same way.

**Comment by rodolforg** [comment]
@morevnaproject  so this build is from the master branch without the reverting commit, right?

**Comment by ice0** [comment]
@rodolforg I think yes. I tested on latest master with latest MSYS (it has newer GTK) and I cannot reproduce the problem.  But I think better to test HEAD commit, because this PR #1475 is also needed.

**Comment by morevnaproject** [comment]
> @morevnaproject so this build is from the master branch without the reverting commit, right?

Right.

> Actually, we need to check if #1442 takes place on master

I have posted the build to verify this statement.

@Svarov-RZM Thank you for testing, now we know that the issue persist in master branch too. ^__^

Important thing to note: @ice0 and others reported that they weren't able to reproduce this issue when rebuilding from source (debug and production). My guess is that this crash related with particular version of GTK. 

We use gtk-3.22.12 when building our packages for windows and Linux.

The latest version from 3.22.x branch is 3.22.30.

We can upgrade version of GTK and check. 
But I think we should upgrade after 1.4.0 release only.

**Comment by rodolforg** [comment]
So, should I fix the error of this PR in Dock_Timetrack2?

**Comment by morevnaproject** [comment]
@rodolforg I think there is no need to do that yet. First, we'll try to update GTK version ^__^ -

> We can upgrade version of GTK and check.

**Comment by ice0** [comment]
@morevnaproject 
Does this issue still persist or can I close this PR?

**Comment by morevnaproject** [comment]
The issue has gone since we updated gtk/glib in morevna-builds - https://github.com/morevnaproject/morevna-builds/pull/90

**Pull request closed without merging**
