### PR TITLE
add test for conversion homogeneous-standard widthpoints & loop

### PR DESCRIPTION
**Pull request by rodolforg**
you can run with make check

### CODE REVIEW

**Comment by ice0** [comment]
Can you add it to CMakeLists.txt too?

**Comment by rodolforg** [comment]
Ice0,  if I know how to do so... lol

**Comment by ice0** [comment]
ok, then I will do it :)

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
> ok, then I will do it :)

thank you @ice0

**Pull request merged**
