### PR TITLE
fix: revert Custom Workspaces Editor button labels to GTK ones

### PR DESCRIPTION
**Pull request by pgilfernandez**
Simple fix for https://github.com/synfig/synfig/issues/3174 as @rodolforg suggested.

Thanks

### CODE REVIEW

**Comment by pgilfernandez** [comment]
Umm, why the "conventional commits style" fails? uppercase after "fix:"?

**Comment by pgilfernandez** [comment]
> Umm, why the "conventional commits style" fails? uppercase after "fix:"?

I respond myself: no verb or action was added...

**Comment by rodolforg** [comment]
Maybe replace directly with Close and Delete strings?

**Comment by pgilfernandez** [comment]
I just reverted the changes to the ones that worked.
If you prefer to change to just text strings then we should change the "Edit" button as well.

What do you want to do?

**Comment by ice0** [comment]
> I just reverted the changes to the ones that worked. If you prefer to change to just text strings then we should change the "Edit" button as well.

I don't see `Edit` button. Do you mean `Rename` button?

> What do you want to do?

At first I thought that these labels would be automatically translated, but unfortunately they are not, they are still in English after changing the language.
So yes, it's better to just rename it as Rodolfo suggested.

**Comment by pgilfernandez** [comment]
> I don't see `Edit` button. Do you mean `Rename` button?

Yes, I mean `Rename` button that is gtk-rename but afterwards the text really applied is `Edit` (at least in Synfig 1.4.1):

workspaces_141


> So yes, it's better to just rename it as Rodolfo suggested.

Ok, I will rebase and add the new modification... just to be sure, I do these changes:
`gtk-delete` turns into just `Delete` string
`gtk-rename` turns into just `Edit`string
`gtk-close` turns into just `Close`string

And the strings will be translatable or is it needed any other work?

**Comment by rodolforg** [comment]
> `gtk-rename` turns into just `Edit`string

`Rename` is the best choice here. You don't **edit** the workspace layout, only the given name.



> And the strings will be translatable or is it needed any other work?

You have to add an xml attribute `translatable` like this:
`<property name="label" translatable="yes">The Button Label</property>`

**Comment by pgilfernandez** [comment]
Well, I think it's done... I hope I did it right.
Rebased as well =)

**Review by rodolforg — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
