### PR TITLE
Improves Graphs widget/panel (related to #267)

### LINKED ISSUE #267: Waypoint editable graph represention mode
Alternative timetrack dock/mode, which would present parameter values as a graph (as graphs dock currently does) *and* allow to edit waypoints, including their parameters (e.g. curve handles for curve interpolation)

### PR DESCRIPTION
**Pull request by rodolforg**
Improves Graph widget features.

Partially implements #267 requests.

Current status:
* [x] draw waypoints in curves
* [x] allow single waypoint selection
* [x] allow multiple waypoint selection
  * [x] via `shift` (adding to selection) and `control` (toggling selection state) keys
  * [x] via mouse dragging rectangle
  * [x] cancelable while mouse-dragging with `right-click`
* [x] allow waypoint value change by dragging orarrow keys
  * [x] `shift` key constraints dragging
  * [x] cancelable while dragging with `right-click` or `Esc`
* [x] allow multiple waypoint value change by dragging
* [x] allow to move (multiple) waypoint time by dragging or arrow keys
* [x] select all visible nodes with `Ctrl+A`
* [ ] select all nodes of single channel with `Ctrl+Shift+A`?
* [ ] ~~show control points for TCB~~
* [x] double click in waypoint shows edit dialog
* [ ] ~~create Bézier waypoint type~~
* [ ] ~~add control points for Bézier waypoints~~
* [x] zoom to pointer/mouse position
* [x] pan with `middle-button` click and drag
* [x] show tooltip for hovered point
* [x] `Del` removes selected waypoints
* [x] Double-click in a curve creates a new waypoint

Items ~~striked-through~~ will be implemented in another PR.

### CODE REVIEW

**Comment by rodolforg** [comment]
@morevnaproject Could you please check if is the building error my fault?
And test if curve points selection works how it should? (as well as @ebarranco )

**Comment by ice0** [comment]
@rodolforg Hi, Rodolfo!
The build is failed because travis-ci is updated they OSX image. I will fix it.

**Comment by morevnaproject** [comment]
@rodolforg This is absolutely epic! I have tested your latest changes and confirming that selection works perfectly! ^__^

screenshot_001

**Comment by rodolforg** [comment]
@morevnaproject  now I started to drag :)
However, it has two issues I see:
* It requires to be in edit mode :(
* The undo history increases a lot

I need some help with Undo feature.
Does SynfigStudio use undo-group stuff like some frameworks?
How can I start one undo-group and edit it (add more actions to it while dragging)?

**Comment by morevnaproject** [comment]
> - It requires to be in edit mode :(

Ah, I see - it requires to have Animation Mode on, right? I see you solved this by temporary enabling/disabling this mode. ^__^

**Comment by morevnaproject** [comment]
> I see you solved this by temporary enabling/disabling this mode. ^__^

I've tested this. It works cool. ^__^

> - The undo history increases a lot
> 
> I need some help with Undo feature.
> Does SynfigStudio use undo-group stuff like some frameworks?

Unfortunately, there are no such thing as undo-group in Synfig.

The same issue happens when you edit color - it produces a lot of history entries. See #451.
I think it's okay to leave things as is for now and address this issue separately later.

**Comment by rodolforg** [comment]
> I've tested this. It works cool. ^__^

So is it good enough?

I want to start the TCB handles only after selection and dragging are working as expected, in order to don't change both feature codes and make them a reference for the future timetrack widget rework.

> > Does SynfigStudio use undo-group stuff like some frameworks?

> Unfortunately, there are no such thing as undo-group in Synfig.

Oh... Ok. Maybe later then.
Thank you for testing.

**Comment by morevnaproject** [comment]
> So is it good enough?

Actually, it would be really nice to allow dragging horizontally (this will change time of waypoint). Horizontal dragging should be snapped to frames.

> I want to start the TCB handles only after selection and dragging are working as expected, in order to don't change both feature codes and make them a reference for the future timetrack widget rework

:tada:

**Comment by rodolforg** [comment]
Should I put some snap to other curve values?

**Comment by morevnaproject** [comment]
> Should I put some snap to other curve values?

@rodolforg No, I think we do not need snap for vertical movement.

**Comment by morevnaproject** [comment]
I found an issue with moving points horizontally - when the point we move overlaps with another point, then it changes value of both points.

Video - https://www.youtube.com/watch?v=udV1Wot1268

Is it possible to tweak horizontal snapping, so it will avoid overlapping with existing points?

**Comment by rodolforg** [comment]
> Is it possible to tweak horizontal snapping, so it will avoid overlapping with existing points?

What do you mean? Avoid dragging movement pass beyond other existent curve points?
Or to skip frame of those existent waypoints?

**Comment by Jose-Moreno** [comment]
@morevnaproject @rodolforg Hi, if I may, normally the value overlapping happens in software like after effects and blender where overlapping the "waypoint" /keyframe will replace the static waypoint value with the value from the active one.

However the specific issue seen in the video portrays the overlapping behavior is contrary to that of most programs and while certainly you can't have the a "waypoint" occupying the same temporal space as another (waypoint value should get replaced), in the case of this video Konstantin shows, I'd say the issue is that if the user does NOT release the waypoint immediately on top of other static waypoints, the value should be preserved and the moving waypoint should keep it's value while "floating" until the user releases it on any other part of the timeline.

_Example After Effects "Waypoint" Dragging_
_Note: X is Red, Y is Green_
after_effects_curves

Notice on the GIF how the active value "snaps" and is ready to replace the static waypoint, however if i keep dragging the waypoint it dos NOT replace the original static value when I keep moving past that.

In the case of the video at second `0:06` the waypoint that is being moved should indeed reform the curve but without modifying the value of the waypoint it just crossed over. That waypoint should just be preserved, otherwise this would become VERY frustrating for users that want to experiment with timing or if the users are moving a keyframe from one place to another and didn't use copy/paste especifically, for example.

**Comment by morevnaproject** [comment]
> What do you mean? Avoid dragging movement pass beyond other existent curve points?
Or to skip frame of those existent waypoints?

I mean skip frame of those existent waypoints.

> normally the value overlapping happens in software like after effects and blender where overlapping the "waypoint" /keyframe will replace the static waypoint value with the value from the active one. ...

@Jose-Moreno The approach you described would be the best solution. I just was thinking about some minimal/easier way to implement. Thanks for  putting detailed notes about that! ^__^

**Comment by rodolforg** [comment]
@Jose-Moreno I did as you showed me, thank you!

@morevnaproject I use your suggestion for converted/linked layer values. Its children work fine as Jose-Moreno suggested, but I couldn't do it that way for converted ones.

Could you please test with exported values and any other "unusual" case? I don't know Synfig that much…

**Comment by morevnaproject** [comment]
@rodolforg Thank you for the fixes!

I have tested latest commit (28bba15d0183f9f4b) and found a weird behaviour - when I select multiple waypoints and slightly move mouse to left or right (really small movement, which doesn't make waypoints to go into other frame), then it makes other selected waypoints move up or down.

I have recorded a video to show how it looks like -
https://www.youtube.com/watch?v=eTQCspFVA_o&feature=youtu.be

**Comment by rodolforg** [comment]
@morevnaproject  Are you sure this is the last commit? That debug message about erasing waypoint shouldn't appear anymore.
I'm investigating it anyway.

**Comment by morevnaproject** [comment]
@rodolforg Let me double-check that...

**Comment by morevnaproject** [comment]
> That debug message about erasing waypoint shouldn't appear anymore.

I figured that out. I was rebuilding last commit, but only did a build for synfig-studio (not for synfig-core). Now did a full rebuild and debug message has gone. 

The weird  behaviour I described in https://github.com/synfig/synfig/pull/982#issuecomment-554308960 still remains.

**Comment by rodolforg** [comment]
@morevnaproject could you please try it now?

**Comment by morevnaproject** [comment]
Tested 86f8b0449a8b78f9f3a31c86c205813b0b9082a1, still the same behaviour :(

**Comment by rodolforg** [comment]
sorry, I pushed the wrong commit :P

**Comment by morevnaproject** [comment]
=D

I've tested 2d318255ff and it behaves better. Still, it behaves weird when multiple points are selected and I move them up-down. See video - https://www.youtube.com/watch?v=wlCtZGGEwAQ

Notice how point from purple line moves vertically relatively to points of blue line.
This is especially visible at 00:54.

Here is the test file I have played with, just in case - 
[test.sifz.zip](https://github.com/synfig/synfig/files/3854423/test.sifz.zip)

**Comment by rodolforg** [comment]
I believe now it is fixed.
I found another issue : dragging the same 3 points quickly in horizontal axis, some selected point would be unselected and and stay at wrong time. Fixed it also.

**Comment by morevnaproject** [comment]
It works perfectly now for me! :tada: ^__^

**Comment by morevnaproject** [comment]
Some info on how splines represented in TCB - https://www.cubic.org/docs/hermite.htm (see "The Kochanek-Bartels Splines (also called TCB-Splines)" section).

**Comment by rodolforg** [comment]
@morevnaproject  could you tell me what do you think about this tooltip implementation?
Captura de tela de 2019-11-22 19-17-16
While dragging, the shown info is a bit different, but I can't take a screenshot =P

**Comment by morevnaproject** [comment]
> could you tell me what do you think about this tooltip implementation?

I think it is awesome! ^__^

https://www.youtube.com/watch?v=2Bi--fpBhsM

**Comment by rodolforg** [comment]
Ok. Only the "value" in tooltip that bothers me now because its values are not user friendly: no measurement unit shown neither converted to those used in GUI (degrees instead of radians, pixels instead of units, etc.)

But now I'll focus in TCB handles and possible bug fixes you point me.

**Comment by rodolforg** [comment]
@morevnaproject should I show the handles of all TCB waypoints or just of those selected ones?

**Comment by morevnaproject** [comment]
@rodolforg It makes sense to display handles only for selected waypoints.

**Comment by rodolforg** [comment]
Hey @morevnaproject Do :)

1. Do you think I should finish this PR right before " first draft of TCB handles for Graph panel" (1cd7ce8) ?
This PR affects `synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp`and `synfig-studio/src/gui/widgets/widget_timeslider.cpp` besides `dock_` and `widget_curves.cpp` obviously. So it might be good people review/try this huge PR to fix any possible regression.

2. Did you try and play with this last commit? ;)

**Comment by morevnaproject** [comment]
1. I think this is a very good idea. For my taste it is already a very cool feature (even without TCB handles), and it works very good for me. If we will merge it, then it will be shipped with 1.4.0, which is also very cool. @blackwarthog @ice0 opinions?

2. Yes, I tested it. As I understood, this is a very early WIP of TCB handles, so I withheld any feedback. ^__^

**Comment by ice0** [comment]
I think it would be nice to include this feature in 1.4

**Comment by rodolforg** [comment]
>     2. Yes, I tested it. As I understood, this is a very early WIP of TCB handles, so I withheld any feedback. ^__^

It is indeed. However, I was analyzing how TCB interpolation works in Synfig when an animation mix TCB with other interpolators and then I found out that, in some cases, TCB has no influence in the curve.
What should I do regarding TCB handle in these cases?
And that's why I put it aside for a while. lol

**Comment by rodolforg** [comment]
Done.

**Comment by morevnaproject** [comment]
> What should I do regarding TCB handle in these cases?

If they has no influence, then it's okay to hide them, I think.

**Comment by blackwarthog** [comment]
seems it works

**Comment by morevnaproject** [comment]
Merged via a415edb6aee6717ddda4aeb77ae14a9afe163899

Thank you s much for your contributions! ^__^

**Pull request closed without merging**
