### PR TITLE
fix crash when undoing creation of a moved/changed vertex of spline

### PR DESCRIPTION
**Pull request by rodolforg**
fix crash when undoing creation of a moved/changed vertex of spline

It happened because the history tree rebuilds on every
undo/redo. It doesn't do it anymore.

Long chain:
The history tree row description would call to
Action::ValueDescSet::get_local_name() and it would
make a 'long' stack until it crashes, as follow:

```
-> Action::ValueDescSet::get_local_name()
 -> ValueDesc::get_description()
  -> ValueDesc::is_exported()
   -> ValueDesc::get_value_node()
    -> LinkableValueNode::get_link()
```
AND FINALLY it crashes due to the invalid link index!

Test case:
* Create a polygon or spline.
* Click on a vertex to open context menu
* Select "Create Item"
* Move the new vertex
* Ctrl+Z (ok, vertex 'unmoved')
* Ctrl+Z (crash)

### CODE REVIEW

**Comment by rodolforg** [comment]
I can split the code cleanup and the actual fix, if desired.

**Comment by rodolforg** [comment]
Travis task stalled :/

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by morevnaproject** [comment]
> Test case:
> 
>  * Create a polygon or spline.
>  * Click on a vertex to open context menu
>  * Select "Create Item"
>  * Move the new vertex
>  * Ctrl+Z (ok, vertex 'unmoved')
>  * Ctrl+Z (crash)

That's weird - I cannot reproduce this issue (without patch) on master and in 1.3.x branch...

(I wanted to test it on 1.3.x to see of I need to apply the patch)

**Comment by rodolforg** [comment]
@morevnaproject I'll build v1.3.x to check it and screencast.

I could reproduce it in master branch easily - I lost my work a few times, but maybe I didn't type the steps properly.

**Comment by morevnaproject** [comment]
@rodolforg Thank you!

**Comment by rodolforg** [comment]
It crashes.

The problem happens if you move the last vertex, not the new one :P
The reason is it always rebuilds the action history tree, so it needs to to fetch all action names again.
However the spline vertex number reduced, so that index registered in action is out of bounds of current state of spline.

https://youtu.be/6IncqQGVNPY

**Comment by morevnaproject** [comment]
Reproduced now! Thank you!

**Comment by morevnaproject** [comment]
Merged into 1.3.x branch. ^_^

**Pull request merged**
