### PR TITLE
feat: added support for SVG image sequence with lst files

### LINKED ISSUE #965: Feature resquest: Support sequence of svg images with lst files.
**Version 1.3.11 or higher,  Gnu/Linux 64**:

**Issue description**:

Hi. Thank you very much for improving this software day by day. I think it is very useful for artists that you can create an lst file that supports sequences of svg images, to have the alternative of importing them without the option of editing the vectors that make up the image. Only for the purpose of importing the sequence and scaling it without worrying about the pixels.

Thank you very much, I hope the information is useful.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/80803345-feature-resquest-support-sequence-of-svg-images-with-lst-files?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rodolforg**
with the fix provided by PR #2789 (commit 25f28b14214bcc98d736ce88138e79f087d56510),
it was finally viable to implement this (simple) feature :)

fix #965

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by ice0** [comment]
@rodolforg 
Forgot to ask: does this function only work when `mod_imagemagick` is enabled?

**Comment by rodolforg** [comment]
Yes

**Comment by rodolforg** [comment]
Same for tiff.
Ppm can be with imagemagick or mod_ppm
Jpeg can be with imagemagick or mod_jpeg

**Comment by rodolforg** [comment]
As alternative we could have ffmpeg (if compiled with librsvg support) or create a Magick++ importer

**Comment by rodolforg** [comment]
Should I create a Magick++ importer?

**Comment by ice0** [comment]
> Should I create a Magick++ importer?

I was planning to discuss switching from ImageMagick to GraphicsMagick because we have issues with ImageMagick on Windows and macOS (or maybe add a `mod_graphicsmagick` as alternative).

The Autotools build currently does not work on macOS because ImageMagick adds `-omp` flags that cannot be handled correctly by libtool/clang toolchain. This can be solved by switching to GCC compiler for autotools build, but I prefer to use clang on macOS (since it's a native compiler). Anyway CMake build works fine so it's not a critical issue.

Another issue is broken MSYS2 and macOS builds (with latest ImageMagick). This can be resolved by adding tests to MSYS2/Homebrew so they can't update ImageMagick until issue is fixed.

Also I am not sure if switching to GraphicsMagick will fix this issues.

So yes, it would be a nice feature if you're interested, but we can skip it if it's too complicated.

**Pull request merged**
