### PR TITLE
Perf imps

### PR DESCRIPTION
**Pull request by define-private-public**
As mentioned in #1775, the perf improvement here is very miniscule, but I'd like to push in the two scripts I wrote that should help with measurement.  I plan on adding some more PRs that should be more significant.

So show you how tiny the change has been, here is some output from the `view_comparison_graph.py` script:
Figure_1

### CODE REVIEW

**Comment by ice0** [comment]
Hi!
Nice to see you start from ColorMatrix class. Fixing it should improve performance greatly.

In my opinion, the main slowdown factor is the lack of batch processing of pixel data. Since it uses pointers to color functions, this results in an expensive function call for **every** pixel processed.

I can illustrate this with a small example:
**test.cpp**
```
#include <random>
#include <ctime>

inline int val2(int r, int g, int b) {
  return r + g + b*2;
}


inline int val(int r, int g, int b) {
  return r*2 + g + b;
}

int main() {
  const int count = 1024*1024*100;
  std::srand(std::time(nullptr)); // use current time as seed for random generator

  std::uint32_t out = 0;
  int r = std::rand();
  int g = std::rand();
  int b = std::rand();

  typedef int (*funcptr)(int, int, int);  // Declare typedef
  funcptr func = nullptr;    // Define function-pointer variable, and initialize
  
  // without std::rand compiler can do optimization here 
  if (std::rand() > 100) {
    func = &val;
  } else {
    func = &val2;
  }

  for (int i = 0; i < count; i++) {
  #ifdef PTR
     out += func(r, g, b);
  #else
     out += val(r, g, b);
  #endif
  }
}
```

test results:
**call a function for each pixel**
```
$ g++ ./test.cpp -O3 -DPTR
$ time ./a.exe

real    0m0.134s
user    0m0.000s
sys     0m0.000s
```

**function call now inlined**
```
$ g++ ./test.cpp -O3
$ time ./a.exe

real    0m0.032s
user    0m0.015s
sys     0m0.015s
```

**3x** speedup!

P.S. 
1) Maybe we need `requirements.txt` here (for python scripts)
2) Can you change spaces to tabs? (what's not critical, but whole project uses tabs)

**Review by ice0 — APPROVED** [review]

**Comment by define-private-public** [comment]
So far I've only been making cursory glances on instructions/lines that could be moved around to take better advantage of of auto-vectorization.  I plan on doing more substantial changes, but I want to learn a bit more about the project before going a little more into adjusting the architecture of things.  I'm well aware of how pointer chasing and ruin performance.

1. I'll get you a requirements.txt soon,
2. I'll put the spaces into tabs for the C++ code.  Do you want it for the Python scripts as well?  Most people try to follow PEP8 and they recommend spaces (with an indent of 4) over tabs.

**Comment by ice0** [comment]
> I'll put the spaces into tabs for the C++ code. Do you want it for the Python scripts as well? Most people try to follow PEP8 and they recommend spaces (with an indent of 4) over tabs.

Only for C++ code.

**Comment by define-private-public** [comment]
Requirements file added and spaces->tabs fixed.

**Comment by ice0** [comment]
Please check LGTM warning about `num_runs` variable. Is it used somewhere?

**Comment by define-private-public** [comment]
whoops, that was a leftover form a previous iteration.  It's gone now.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
