### PR TITLE
feat: added hotkey for duplicate layer button

### LINKED ISSUE #2891: Hotkey for Duplicate Layer button
`ctrl + d` hotkey for "duplicate layer" function would help speed up artwork creation in Synfig.
image

### PR DESCRIPTION
**Pull request by mohamedAdhamc**
fixes #2891 
ctrl + d and ctrl + shift + d, are both already being used for unselect all layer and ducks. I semi-arbitrarily chose ctrl+u as its what comes after the d in duplicate, and anyway the user can change it. But if there is a better initial key pair please let me know :).

### CODE REVIEW

**Comment by yoSachinkr** [comment]
Works perfectly. 💯

**Comment by ice0** [comment]
@yoSachinkr @morevnaproject @rodolforg @pgilfernandez @FirasH

Does anyone use the `ctrl+d` combination to select? Maybe deprecate it?

**Comment by pgilfernandez** [comment]
I have never used any combination of those under Synfig but if you ask me I would set `ctrl+a` (or `cmd+a`) for selecting all and `shift+ctrl+a` (or `shift+cmd+a`) for deselecting all.
Nowadays `a` is used for selecting and deselecting but Windows keep using `e` in the File Explorer... anyway I personally prefer `a` as other open source software uses it (such as Blender).

**Comment by yoSachinkr** [comment]
> @yoSachinkr @morevnaproject @rodolforg @pgilfernandez @FirasH
> 
> Does anyone use the `ctrl+d` combination to select? Maybe deprecate it?

Personally I use `ctrl+a` to select all vertices and `shift+a` to deselect all vertices. Also `ctrl+shif+a` to select all layers and `ctrl+shift+d` to deselect all layers.

**Comment by rodolforg** [comment]
> I have never used any combination of those under Synfig but if you ask me I would set `ctrl+a` (or `cmd+a`) for selecting all and `shift+ctrl+a` (or `shift+cmd+a`) for deselecting all.

What about `Ctrl+a` for both selecting all and deselecting all handles?
What about `Ctrl+shift+a` for both selecting all and deselecting all layers?
Blender uses `a` to toggle all/none selected.

This is a way to free `ctrl+d` and `ctrl+shift+d`

**Comment by mohamedAdhamc** [comment]
@rodolforg , I also think this would be the best to have the layer/duck selects be ctrl/shift/a combinations. So the CTR+d is freed for this. I guess I just need confirmation here now and I can change it accordingly.

**Comment by ice0** [comment]
I think it's better to switch the hotkeys in the new PR.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by morevnaproject** [comment]
> I also think this would be the best to have the layer/duck selects be ctrl/shift/a combinations. So the CTR+d is freed for this.

Yes, I like this too.

In any case, I do not use Ctrl+D for selecting layers. Actually, I never had a need to select all layers. XD

**Pull request merged**
