### PR TITLE
[Lottie exporter] Convert methods working with radius of simple circle layer

### LINKED ISSUE #1101: [Lottie exporter] Convert methods not working with radius of simple circle layer
**Synfig version & platform**:
Master branch, commit https://github.com/synfig/synfig/commit/0f2e3ebf5869c0aeb036172801012cec650f6aa3

**Issue description**:
Test File: https://gitlab.com/synfig/synfig-tests/blob/master/export/lottie/087-add-convert-simplecircle.sif

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/87453598-lottie-exporter-convert-methods-not-working-with-radius-of-simple-circle-layer?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Fixes: #1101 
@AnishGG , I looked at #1018 which had similar issue as this one and was able to resolve this.
Please have a look at this.

### CODE REVIEW

**Comment by ice0** [comment]
@saurabh-ramola I think `.controller.py.swp` is not needed here?

Please change PR title to more descriptive

**Comment by rodolforg** [comment]
Please squash this last commit into the first one

**Comment by saurabh-ramola** [comment]
@ice0 @rodolforg Thank you for the review. I have made the necessary changes as per your suggestions.

**Comment by AnishGG** [comment]
I have tested it with https://gitlab.com/synfig/synfig-tests/blob/master/export/lottie/087-add-convert-simplecircle.sif and it works well.
So this PR fixes the issue!
Keep up the good work @saurabh-ramola!

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
