### PR TITLE
Version 1.4.3

### PR DESCRIPTION
**Pull request by morevnaproject**
This is an update to stable branch (critical fixes).

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hi! I have made a test Windows build from this branch - [SynfigStudio-1.4.3-testing-2022.04.05-win64-71775.exe](https://cloud.morevnaproject.org/s/NrH2Dx8DFL4dtNT)

...and I found an important issue:
It is not possible to import any file from the same drive.

I.e., if user has synfig's file saved on drive D, then it is not possible to import any file from drive D. 
It shows error: "You cannot import a file to itself".

Here is a demonstration video - https://www.youtube.com/watch?v=0Q2mShLWle4

**Comment by ice0** [comment]
> ...and I found an important issue: It is not possible to import any file from the same drive.
> 
> I.e., if user has synfig's file saved on drive D, then it is not possible to import any file from drive D. It shows error: "You cannot import a file to itself".

This is packaging issue.
https://github.com/synfig/synfig/issues/2410

**Comment by ice0** [comment]
@morevnaproject 

OK. Just checked, and it still looks like a packaging issue.
What I've done:
1) Tried to build `1.4.x` locally. Failed because CMake not working in `1.4`, autotools build fails because MSYS2 removed the `libdl` shared library (only static is available), but autotools depends on the shared library.
2) Downloaded version `1.5.1`. The issues are reproduced here too.
So I build `v1.5.1` locally using CMake. The problem is not reproduced.

So I think the problem is in the outdated `glib/glibmm` libraries used for the build. I only see `Gio::...` methods when checking a file, and they are part of `glib` libs.

**Comment by morevnaproject** [comment]
I have updated glib 2.50.0 -> 2.69.3 and glibmm 2.50.0 -> 2.58.1.
The issue has gone.
Though, I've got other issues with Windows version. Will test them more and report.

Also, I made clean rebuild of everything again and got error in Linux build - #2612

**Comment by morevnaproject** [comment]
> Unfortunately, the fix with the replacement of libraries does not work anymore

@ice0 I wonder why library replacement doesn't work anymore. 🤔 Could it be an SJLJ vs SEH issue? - https://microeducate.tech/what-is-the-difference-between-mingw-seh-and-mingw-sjlj/.

I would prefer to have this possibility to replace libraries from MSYS2. So, if this is an SJLJ vs SEH issue, then I can change compiler in my build environment.

**Comment by ice0** [comment]
> > Unfortunately, the fix with the replacement of libraries does not work anymore
> 
> @ice0 I wonder why library replacement doesn't work anymore. 🤔 Could it be an SJLJ vs SEH issue? - https://microeducate.tech/what-is-the-difference-between-mingw-seh-and-mingw-sjlj/.


Just checked again, and after replacing everything works fine.
I think maybe I forgot to replace the 'lib' and 'share' folders last time.

**Comment by morevnaproject** [comment]
> Just checked again, and after replacing everything works fine.
> I think maybe I forgot to replace the 'lib' and 'share' folders last time.

Good to know! Thanks!

**Comment by morevnaproject** [comment]
Here is the Windows build with new Glib - [synfigstudio-1.4.3-20220419-new-glib.exe](https://cloud.morevnaproject.org/s/a3fbrMGqan3xyFF).

About the bug I have mentioned earlier - looks like it happens in master branch only. Will investigate more soon.

**Comment by morevnaproject** [comment]
So far, the release is blocked only by this issue - https://github.com/synfig/synfig/issues/2608

Also, I still have to review this one - https://github.com/synfig/synfig/pull/2495

**Comment by ice0** [comment]
@morevnaproject 
Can you check if 1.4.3 has this issue #1701? (it is also fixed)

**Comment by rodolforg** [comment]
May I push the changes to be backported (https://github.com/synfig/synfig/projects/12) directly here in this PR?

**Comment by rodolforg** [comment]
On July 29, it's been a year since last stable release :) Will we have a new one for celebration? XD

**Comment by morevnaproject** [comment]
> Can you check if 1.4.3 has this issue #1701? (this has also been fixed)

Yes, 1.4.3 is affected. Fix backported now.

**Comment by morevnaproject** [comment]
> On July 29, it will be a year since last stable release :) Will we have a new one for celebration? XD

Sorry for taking so long... Releasing now. ^__^

**Comment by morevnaproject** [comment]
> May I push the changes to be backported (https://github.com/synfig/synfig/projects/12) directly here in this PR?

I am not sure what would be better approach with 1.4.x branch...
In general, it is okay if other devs will push into it... But when we have release time (like no) this is not desirable.
We should somehow identify when it is "release time" and when it isn't. ^__^

**Comment by morevnaproject** [comment]
> > May I push the changes to be backported (https://github.com/synfig/synfig/projects/12) directly here in this PR?
> 
> I am not sure what would be better approach with 1.4.x branch... In general, it is okay if other devs will push into it... But when we have release time (like no) this is not desirable. We should somehow identify when it is "release time" and when it isn't. ^__^

Ah, I got it. It's better to submit PRs to 1.4.x branch. instead of pushing directly.

This way we have one person, who is responsible for maintaining 1.4.x release (currently that's me) and others can help by preparing backports for the branch (for the cases when commits can't be cherry-picked without conflicts).

**Pull request merged**
