### PR TITLE
Navigation Menu Added

### PR DESCRIPTION
**Pull request by yshkp**

### CODE REVIEW

**Comment by yshkp** [comment]
@morevnaproject PTAL and if looks fine go ahead for the merge else suggest the improvements required.

**Comment by morevnaproject** [comment]
Hi @yshkp! Thank you for the pull request!

I tested it and it works fine.

Here are few issues with PR I would like to be fixed:

- Please provide issue number in PR description. Like this: "Fixes #732".
- I have noticed the commit message contains  some random text. Please provide a proper description for commit -
screenshot_001

**Comment by yshkp** [comment]
@morevnaproject I have changed commit message and also in that mentioned about the issue. Last commit was unusual please don't mind it.

**Comment by morevnaproject** [comment]
@yshkp I can see the commit history of this PR still contains redundant commits -
screenshot_007

Please make sure to cleanup commit history. You can do that in the following way:

1. Remember the ID of commit you would like to keep - ```e4fcd1781e872a5267fa80ca0dd550f9226baed2```
2. Do ```git reset --hard origin/master```
3. After that, copy commit by ID into your current branch: ```git cherry-pick e4fcd1781e872a5267fa80ca0dd550f9226baed2```
4. Force-push your branch to GitHub: ```git push --force```

Warning: I might be wrong with command syntax somewhere (just recalling them quickly from my memory). Please consult manpages for **git-reset**, **git-cherry-pick** and **git-push** commands.

**Comment by ankit-kumar-dwivedi** [comment]
@yshkp this can help
```
git remote add upstream https://github.com/upstream/repo.git

git pull --rebase upstream master
git push --force-with-lease origin master
```
this is what I usually do
Hope it will help :)

**Pull request closed without merging**
