### PR TITLE
fix warning on MODULE_INVENTORY_BEGIN: misleading indentation

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by ice0** [comment]
I'm not sure if this is correct. I used `g++ -E <args>` to test this change. 
Before:
```
extern "C" {
    synfig::Module* libmod_example_LTX_new_instance(synfig::ProgressCallback *cb) {
        if (synfig::check_version_(50,sizeof(synfig::Vector),sizeof(synfig::Color), sizeof(synfig::Canvas),sizeof(synfig::Layer)))
        {
            libmod_example_modclass *mod=new libmod_example_modclass(cb);
            mod->constructor_(cb); 
            return mod; 
        }

        if (cb) cb->error("libmod_example"": Unable to load module due to version mismatch."); 
        return nullptr; 
    }
}; 

libmod_example_modclass::libmod_example_modclass(synfig::ProgressCallback * )
{{
  synfig::Layer::register_in_book( synfig::Layer::BookEntry(SimpleCircle::create, SimpleCircle::get_register_name(), synfigcore_localize(SimpleCircle::get_register_local_name()), SimpleCircle::get_register_category(), SimpleCircle::get_register_version()));
  synfig::Layer::register_in_book( synfig::Layer::BookEntry(Metaballs::create, Metaballs::get_register_name(), synfigcore_localize(Metaballs::get_register_local_name()), Metaballs::get_register_category(), Metaballs::get_register_version()));
}}
```

After:
```
extern "C" {
    synfig::Module* libmod_example_LTX_new_instance(synfig::ProgressCallback *cb) {
        if (synfig::check_version_(50,sizeof(synfig::Vector),sizeof(synfig::Color), sizeof(synfig::Canvas),sizeof(synfig::Layer)))
        {
            libmod_example_modclass *mod=new libmod_example_modclass(cb);
            mod->constructor_(cb);
            return mod;
        }
        if(cb) {
            cb->error("libmod_example"": Unable to load module due to version mismatch.");
        }
        return nullptr;
    };
    
    libmod_example_modclass::libmod_example_modclass(synfig::ProgressCallback * ) 
    {{
        synfig::Layer::register_in_book( synfig::Layer::BookEntry(SimpleCircle::create, SimpleCircle::get_register_name(), synfigcore_localize(SimpleCircle::get_register_local_name()), SimpleCircle::get_register_category(), SimpleCircle::get_register_version()));
        synfig::Layer::register_in_book( synfig::Layer::BookEntry(Metaballs::create, Metaballs::get_register_name(), synfigcore_localize(Metaballs::get_register_local_name()), Metaballs::get_register_category(), Metaballs::get_register_version()));
    }} 
}
```

As you may notice, now `libmod_example_modclass` constructor is inside `extern "C"` section.

**Comment by rodolforg** [comment]
I did it intentionally lol
Would it be wrong then?

**Comment by ice0** [comment]
> I did it intentionally lol 
> Would it be wrong then?

I think no need to demangle class constructor. This way we will show that the only thing we want to be exported is the `...LTX_new_instance` function.

**Comment by rodolforg** [comment]
Fixed

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
