### PR TITLE
refactor: minor cleanup in state Lasso and Draw

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Review by mohamedAdhamc — APPROVED** [review]
looks good. I think the state classes in general have a lot of dead/need-to-be refactored code. I noticed this while working on the select tool.

**Comment by ice0** [comment]
@rodolforg Please rebase

**Comment by rodolforg** [comment]
@ice0  done

**Comment by ice0** [comment]
@rodolforg 
Can it be squashed?
I didn't notice that the first commit is empty.
It looks like this changes was already merged.

**Comment by rodolforg** [comment]
Oh.

Yes, it can be squashed.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
