### PR TITLE
UI : Handle tooltip transformation widget - display Layer desc

### PR DESCRIPTION
**Pull request by d-j-a-y**
transfo widget

### CODE REVIEW

**Comment by d-j-a-y** [comment]
just to know> following that change, i'm working at dialog setup.cpp (preferences) accordingly to [jcome redesign work](http://www.synfig.org/forums/viewtopic.php?f=14&t=3648) ...

**Comment by morevnaproject** [comment]
Good work! Merged the tooltips feature, together with preferences dialog.

**Comment by morevnaproject** [comment]
Ooops, sorry, probably I was too fast. I think it would be better to apply this change into the "rendering" branch. The "rendering" branch will take place of "master" very soon.

**Comment by d-j-a-y** [comment]
> I think it would be better to apply this change into the "rendering" branch. The "rendering" branch will take place of "master" very soon.
@morevnaproject Yep no prob', looking at what's going on rendering, i thought something like that will occur... 
I close the request has my "preference redesign" branch is upon that one.

**Pull request closed without merging**
