### PR TITLE
[Lottie exporter] Add variable gamma correction

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Fixes: #1174 
@AnishGG please have a look.

### CODE REVIEW

**Comment by saurabh-ramola** [comment]
One doubt here: If there is a group layer inside our main canvas and it's canvas has some different gamma correction values associated with it. How do we handle that here?

**Comment by saurabh-ramola** [comment]
I have created a gist showing an example:
https://gist.github.com/saurabh-ramola/86a8709e4ca8e684fbbf6275cdbb7ccc#file-check_gamma-sif-L59
I tested this file on Synfig, but the internal canvas's gamma values have no effect on the color. So I guess this PR closes the issue.

**Comment by AnishGG** [comment]
I have tested this. Looks great!
@morevnaproject I think this ready to be merged.

**Comment by AnishGG** [comment]
> the internal canvas's gamma values have no effect on the color.

Even I tested this and I got the same result. @morevnaproject could you if this is the expected behaviour.

**Comment by AnishGG** [comment]
@morevnaproject , could you have a look at this please ^__^

**Comment by saurabh-ramola** [comment]
@ice0 Does this need any changes? ^_^

**Comment by ice0** [comment]
@saurabh-ramola code looks good to me.

**Comment by ice0** [comment]
@saurabh-ramola just checked. If i change Canvas->Properties->Gamma correction i can see difference in colors on canvas. (Especially if you set it like 3, 1, 1). But when i export animation using plugin - i can't see any difference in result. Can you confirm that?

**Comment by saurabh-ramola** [comment]
> @saurabh-ramola just checked. If i change Canvas->Properties->Gamma correction i can see difference in colors on canvas. (Especially if you set it like 3, 1, 1). But when i export animation using plugin - i can't see any difference in result. Can you confirm that?

@ice0 , I tried the steps followed by you, but I am getting different colors every time I change the gamma correction.
I am attaching the file that I used: [circle.sif](https://gist.github.com/saurabh-ramola/d6771dfbd00cb666ea0e18c0576baf75)
Could you provide me the test file that you used?

**Comment by ice0** [comment]
Here is what I see when your file is exported:

lottie1

**Comment by saurabh-ramola** [comment]
@ice0 I even tried running the files from bash using `python3`. But I got the correct results.
Could you guide me furthur how can we resolve this?

**Comment by AnishGG** [comment]
I am currently building your branch, will report soon. :D

**Comment by AnishGG** [comment]
@ice0 even I am getting the correct export results. Is it possible that you might have built the wrong branch from the fork?
While testing this file, I encountered an error in the app. Will submit it to the issue tracker. ^__^

**Comment by ice0** [comment]
@saurabh-ramola @AnishGG, that was a problem on my side guys. I forgot to fix the `plugin.xml` file, so all this time I checked the old plugin. At the moment - everything works fine! Well done!

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
