### PR TITLE
Soundwave dock now loads sound layers from canvas

### PR DESCRIPTION
**Pull request by rodolforg**
Fix https://github.com/synfig/synfig/issues/1346

### CODE REVIEW

**Comment by rodolforg** [comment]
It now has issues with Canvas Time model beginning being shifted from 0f. I'll fix that later.

Anyway, tell me what you think about how we should name items in sound layer combobox…

Currently it uses filename listed in sound layer parameter.

**Comment by rodolforg** [comment]
I see one problem here: popping the combobox is not good :(

**Comment by rodolforg** [comment]
@morevnaproject could you test it?

**Comment by morevnaproject** [comment]
Testing now! Thank you! ^__^

**Comment by morevnaproject** [comment]
The feature works great!

For name in combobox I suggestto display it in the following way:
* [**LAYER_NAME**] - **/path/to/file.wav**

Also I suggest to shorten path to file if it is too long.
I.e. for "/very/very/very/very/very/long/path/to/file.wav" display it like "...ry/long/path/to/file.wav".

**Comment by rodolforg** [comment]
Is this way better?

**Comment by morevnaproject** [comment]
I tested it and for some reason it doesn't shows filepath -
screenshot_004

**Comment by rodolforg** [comment]
It only shows if it is different of layer description ("name").
Should it be always visible?

**Comment by morevnaproject** [comment]
> Should it be always visible?

Yes, I think it's better to make it always visible. ^__^

Also, I just  realized that it would be nice if combobox choices will appear above of combobox itself. Just like we did for Blend Method's parameter combobox - https://github.com/synfig/synfig/issues/650#issuecomment-450001367

**Comment by rodolforg** [comment]
I realize that `synfig::CanvasFileNaming::make_short_filename()` doesn't ellipsize long strings, it creates a relative path (which usually shortens the name).

How many chars would have a long filename?
In order to implement your example:

> I.e. for "/very/very/very/very/very/long/path/to/file.wav" display it like "...ry/long/path/to/file.wav".

**Comment by morevnaproject** [comment]
> How many chars would have a long filename?

I guess, 30 is enough. ^__^

**Comment by rodolforg** [comment]
Done :)

**Comment by morevnaproject** [comment]
Thank you, it works perfectly now! Can you rebase, please? ^__^

**Comment by rodolforg** [comment]
Done :)

**Comment by morevnaproject** [comment]
Thank you for an awesome feature! ^__^

**Pull request merged**
