### PR TITLE
[Synfig Studio] Waypoint Editor didn't properly support enums

### LINKED ISSUE #1965: [Synfig Studio] Waypoint Editor "Value" could set not feasible Parameter values
**Synfig version & platform**:
master 4b7f89b

**Issue description**:
1. Create a new animation
2. Draw a `Star` on Canvas (works with any Layer)
3. Enable Animate mode and create a waypoint for `Blend Method` parameter
4. Double-click on the waypoint created in step 3 to open `Waypoint Editor` dialog
waypoint-editor-value
`Value` is represented as a spin box, not as a dropdown.

5. Scroll on `Value` spin box to change its value e.g. -20
waypoint-editor-out-of-bounds
The spin box hasn't a min/max value and the value is set.

This happens for all values set with dropdowns in `Parameters` panels.

### PR DESCRIPTION
**Pull request by rodolforg**
fix #1965

### CODE REVIEW

**Comment by rodolforg** [comment]
Maybe backport it?

**Comment by FirasH** [comment]
Tested and works perfectly!


Noticed that with enums type of variables when some kind of interpolation is set, those will get through all variables (this happened even before)
For example if you interpolate from `Blend Method` `Composite` to `Alpha` Synfig will get through each one of them like from 0 to 20.

If interpolation is set to Constant it's fine, but I don't know if this is a plus or an issue...

**Comment by rodolforg** [comment]
Maybe it should use "Constant" interpolation by default. Perhaps all "enum" parameters.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
> Maybe backport it?

I think yes.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
