### PR TITLE
Parameters and Timeline panels show the same row selected

### LINKED ISSUE #246: Parameters and Timeline panels should show the same row selected.
When you select an item in one of the two panels, the same should be selected in the other panel.

synfig_report_004
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38182084-parameters-and-timeline-panels-should-show-the-same-row-selected?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rodolforg**
Fix #246

### CODE REVIEW

**Comment by rodolforg** [comment]
Yeah, for the old timetrack. I think it's good to fix it in case new TimeTrack causes instability

**Review by ice0 — APPROVED** [review]

**Comment by rodolforg** [comment]
Maybe backport?

**Comment by ice0** [comment]
> Maybe backport?

Sure. Added it to list.

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by morevnaproject** [comment]
> > Maybe backport?
> 
> Sure. Added it to list.

Unfortunately, the fix doesn't applies cleanly to 1.4.x branch.

**Pull request merged**
