### PR TITLE
Fix crash when removing a list item of a parameter

### PR DESCRIPTION
**Pull request by rodolforg**
If you select a vertex item of Spline parameter list and then right-click on it and choose `Remove item (Smart)`, app crashes.
Not anymore. Simple, but not the best, solution.

### CODE REVIEW

**Comment by rodolforg** [comment]
Depends on https://github.com/synfig/synfig/pull/1104.
Could you please review both PR?

**Comment by ice0** [comment]
@blackwarthog found a deeper problem, so i will continue to review after he take decision to use hack or fix original problem.

**Comment by rodolforg** [comment]
@ice0 This PR just avoids Synfig Studio from crashing. Crash yells a bad reputation for the software: work hour loss :(

The problem root seems to be bad (or none) reaction to item removal of parameter list: connected signals and queued redrawing before internal (studio) structure/data update.

**Comment by ice0** [comment]
@rodolforg I agree. Just want to check if better solution is possible. Anyway we do not release, until this issue is closed.

**Comment by blackwarthog** [comment]
After call method LayerParamTreeStore::rebuild() does the following:
- called LayerParamTreeStore
- items from tree removes one by one
- after removing of selected item section moves to the next item and calling signal_selection_changed()
- Dock_Curves listen this signal and initiates of redraw
- error raised when selection moved to last element in list, because curretly list have a one item less

also this behavior produse a lot of extra calls of signal_selection_changed and a lot of repaints of GUI.


GTK cannot handle this situation because TreeStore (child of TreeModel) does not know nothing about widgets and selection
TreeView widget and Selection does not know when TreeStore cleared
GTK have no signal on TreeModel completely clears, it replaced by one by one calling of item removing signals

We need to safely clear th TreeStore when its content was invalidated.
But GTK assumes that item will removed from model *before* removing from user logic.
So by GTK assumed workflow we need to keep model and linked with it user data in valid state.

We have ability to remove a single item, but it have some ancient problems. Developers before us was disabled this code, and just do full rebuild of the tree. Will be goot to fix it in future.

But anyway we need an ability to do full rebuild safely.

Solution can be in adding of our own signal_clearing into LayerParamTreeStore, and connect widget to it, to clear the selection before clearing of TreeStore.

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by ice0** [comment]
Created a new issue to find the better solution later: https://github.com/synfig/synfig/issues/1287

**Pull request merged**
