### PR TITLE
Try to fix adv outline rendering

### PR DESCRIPTION
**Pull request by rodolforg**
#1480 

But please test it... I'm tired lol

The cuspids are still sometimes ugly…

I didn't check unlooped splines or splines with 1 or more than 2 width points.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Thank you so much! Testing it now... ^__^

**Comment by FirasH** [comment]
I'm testing this as well, till now it's working as expected :smile:

**Comment by FirasH** [comment]
Noticed that in the cases where a `Side Type` is on a corner of an `Advanced Outline Layer` there are some strange artifacts, not sure if it's related to this issue as it happened also without this patch...

**Comment by rodolforg** [comment]
I think it is related to bend code. It deals with cuspids.

**Comment by morevnaproject** [comment]
It is much better now!

I have found the following issue with sample file provided in #1480:

Here how it looks at frame 0 in 1.2.2 -
screenshot_002
(note two dots visible)

Here how it looks at frame 0 in master branch (with this patch) -
screenshot_003

Notice only one "point" in visible.

Also, it appears in different place, but this is a different issue, not related to this. I'll post about it a bit later.

**Comment by rodolforg** [comment]
I think I fixed it now... Not in a beautiful way :P

**Comment by rodolforg** [comment]
@FirasH so does this PR solve #1329?

**Comment by FirasH** [comment]
> @FirasH so does this PR solve #1329?

Yes, now it works.

**Comment by morevnaproject** [comment]
> I think I fixed it now... Not in a beautiful way :P

Thank you! I have tested and result is better now, but it is still different from output of version 1.0.2. 

This is how it looks for me (notice the flat beginning of outline) -
screenshot_005

Notice the same line looks rounded in version 1.2.2 and below -
screenshot_006


Also, I have found one more issue ^__^".

Here is a sample file - 
[advanced-outline-cusps-flat-002.sif.zip](https://github.com/synfig/synfig/files/4878257/advanced-outline-cusps-flat-002.sif.zip)

Here is how it looks in 1.0.2:
screenshot_004

...and this is result I get from master (with patch from this PR):
screenshot_002

Notice, that if I slightly move last widthpoint from position 1.0, then result becomes correct -
screenshot_003

I hope that helps. 

Thank yo so much for your efforts!

**Comment by rodolforg** [comment]
> This is how it looks for me (notice the flat beginning of outline) -

Are you sure about the pink line? I got it right here.
https://youtu.be/L4huFsWgtBc

I'll try to fix the second case you showed.

**Comment by rodolforg** [comment]
> Are you sure about the pink line? I got it right here.
> https://youtu.be/L4huFsWgtBc

Oooohh that parameter overrides that one in Width Point. Got it ;)

**Comment by rodolforg** [comment]
I think I did it! :)
Without that hack now :D

**Comment by rodolforg** [comment]
the last force-push is for splitting a commit in two, and improving their message :P

**Comment by rodolforg** [comment]
> Thank yo so much for your efforts!

Looking forward to a new stable version. In order to get a new/updated development version XD

**Comment by morevnaproject** [comment]
Thank you so much! Taking it for test.

**Comment by rodolforg** [comment]
So I added a fix for a case I saw earlier via fefe3a5 and now I rebased to master branch.

**Comment by morevnaproject** [comment]
I haven't found any issues with cusps now! Thank you so much!

> Noticed that in the cases where a `Side Type` is on a corner of an `Advanced Outline Layer` there are some strange artifacts, not sure if it's related to this issue as it happened also without this patch...

I am also not happy about quality of outline, which we've got after its algorithm has been reworked in  573f832f5c0c2c9eecc74b811ae9e2943dbae3a2

For example in this file - 
[linea2.sifz.zip](https://github.com/synfig/synfig/files/4908181/linea2.sifz.zip)

Here is how the line bend looks in 1.2.2 -
screenshot_001

...and here is in current master -
screenshot_002

Still, I believe that refactoring done in 573f832f5c0c2c9eecc74b811ae9e2943dbae3a2 made a code cleaner and easier to maintain. So, I believe the bend function can be improved at some point later (after release of 1.4.0).

**Comment by rodolforg** [comment]
@morevnaproject would it be pushed to branch 1.3.x too?

**Comment by morevnaproject** [comment]
@rodolforg Done! Now I think we are ready for 1.3.15! :tada:

**Pull request merged**
