### PR TITLE
feat: allow to change resource filepath in Canvas Dependencies dialog

### PR DESCRIPTION
**Pull request by rodolforg**
For now, it won't work on animated valuenodes or any other value node type. User is warned on those cases and no action is performed.

### CODE REVIEW

**Comment by ice0** [comment]
@rodolforg 

How I can test it?
I created a new file and imported another `.sifz`, but it doesn't show up in the `External Canvas Dependencies` dialog.
What I am doing wrong?

**Comment by rodolforg** [comment]
@ice0 

Oh, well. I forgot about this possibility XD
I focused on image, audio and such stuff... I'll include the imported .sif XD

**Comment by ice0** [comment]
Also if the file is not saved, then when you try to change the dependency, it simply disappears.

Do you plan to continue here, or is it better to merge it as is?

**Comment by rodolforg** [comment]
(rebased and fixed issue pointed in https://github.com/synfig/synfig/pull/3105#issuecomment-1592300310 thanks to `Path::proximate_to()`)

**Comment by rodolforg** [comment]
Done.

**Comment by rodolforg** [comment]
> I created a new file and imported another `.sifz`, but it doesn't show up in the `External Canvas Dependencies` dialog.

Done.

**Comment by rodolforg** [comment]
(rebased)

**Comment by rodolforg** [comment]
(rebased)

**Comment by rodolforg** [comment]
(rebased)

**Comment by rodolforg** [comment]
(rebased)

**Comment by rodolforg** [comment]
(rebased)

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Looks good. @rodolforg can you rebase it please?

**Comment by rodolforg** [comment]
@ice0 rebased

**Review by morevnaproject — APPROVED** [review]
I tested and it works great! Thank you very much!

**Comment by rodolforg** [comment]
Will we have a new Christmas release?

**Comment by ice0** [comment]
> Will we have a new Christmas release?

I hope on it too :)

Merged. Thank you!

**Pull request merged**
