### PR TITLE
[WIP] Allow users to select multiple waypoints

### LINKED ISSUE #762: Allow to select multiple waypoints from different rows
Allow user to select multiple waypoints by holding CTRL.

Currently this is possible if waypoints belong to the same parameter.
But if waypoints belong to different parameters, then it is impossible to select them together.

### PR DESCRIPTION
**Pull request by yshkp**
Fixes #762 
Verticals lines behave as per requirement. Horizontal lines to be implemented as per the new method suggested.
Last step of rendering waypoints and allowing it to be activable(multiple waypoints) for users.

### CODE REVIEW

**Comment by yshkp** [comment]
@morevnaproject  I have pushed the commit, you can check it.
As soon as exams get finished, without any delay, I will render the waypoints and other remaining steps.

**Comment by morevnaproject** [comment]
Hi @yshkp! Thank you for sharing the code. I quickly examined the code. First of all, it would be nice to create new panel (i.e. "TimeTrack2") and put all your changes there. That way you will have code for both Time tracks (old and new) available and this will simplify he process of writing code (and finding possible bugs).

**Comment by yshkp** [comment]
@morevnaproject By this, Do you mean to create a new file named `dock_timetrack2`?

**Comment by morevnaproject** [comment]
Yes.

**Comment by ankit-kumar-dwivedi** [comment]
Hey! @yshkp are you planning on resuming the work?

**Pull request closed without merging**
