### PR TITLE
ci: Add workflow to automatically generate release notes for GitHub releases

### PR DESCRIPTION
**Pull request by Ahmed-Khaled-dev**
This is done by adding a simple GitHub workflow that uses the [Release Notes Manager](https://github.com/Ahmed-Khaled-dev/release-notes-manager) GitHub Action which I created for Synfig during Google Summer of Code 2024.

## What does this do?
- Adds the first feature listed in the [features](https://github.com/Ahmed-Khaled-dev/release-notes-manager?tab=readme-ov-file#key-features) of the Release Notes Manager.

- Finishes the main points in the first half of the [Google Summer of Code Project](https://synfig-docs-dev.readthedocs.io/en/latest/gsoc/2024/ideas.html#automated-release-notes-generator-and-packaging-script-fixes-175-or-350-hrs)

## Why is this beneficial?
- Free up valuable time by removing the burden of modifying release notes manually in [ChangeLog.md](https://github.com/synfig/synfig/blob/master/ChangeLog.md)

- Tremendously improve the looks and structure of the release notes which will help Synfig users better understand the changes made

- Transfers the release notes to the GitHub releases' descriptions, increasing their visibility and professionalism

## Notes
- Instructions for generating release notes with this workflow can be found starting from step 5 in the [How To Use](https://github.com/Ahmed-Khaled-dev/release-notes-manager?tab=readme-ov-file#1-generating-release-notes) section.

- The current version of the Release Notes Manager GitHub Action is specifically designed for Synfig and offers limited customization from the workflow in this repository. Additional customization features can be added later after closing issue [#3377](https://github.com/Synfig/Synfig/issues/3377)

### CODE REVIEW

**Comment by mohamedAdhamc** [comment]
Hello @Ahmed-Khaled-dev ,

I did a small test:

releases:
Screenshot from 2024-10-20 18-29-58


release note generator:
gen

error:
Screenshot from 2024-10-20 18-37-02

Any idea what is happening here ?

**Comment by Ahmed-Khaled-dev** [comment]
Hello Mohamed!
Thank you for the images that clarify the test,
If you are testing this with Synfig's commit messages, then this wouldn't be an error since all the commit messages between v1.4.2 and v1.5.1 don't follow conventional commit types, you can check the commits between these 2 releases by running `git log v1.4.2..v1.5.1 --oneline`, it will print all the commit messages of all the commits that happened between these 2 releases, and all of them don't follow conventional commit types, I would suggest testing generating release notes between v1.4.3, v1.4.4, and v1.4.5 since these contain commits that follow conventional commit types,
or if you would like to you can create new commits and tags and test on these, only one thing to keep in mind is to follow the convention that Synfig uses in commit messages as shown below:

Screenshot from 2024-10-20 22-26-00

On another note, in case you run into this, if you have correctly formatted commit messages between the 2 tags and it still gives an error, this would probably be due to permission issues, I mentioned the fix to this in the [Release Notes Manager](https://github.com/Ahmed-Khaled-dev/release-notes-manager) README as follows:

image

**Comment by mohamedAdhamc** [comment]
> all the commit messages between v1.4.2 and v1.5.1 don't follow conventional commit types

Yes, correct. I forgot about that. I'll retest with newer version.

**Review by mohamedAdhamc — COMMENTED** [review]
Two things come to mind here as of now:

1- I think it would be a lot simpler if instead of manually typing the tag name of the release. There would be a drop down selection menu that just lists out all of them from latest to first. Do you think this could be simple to implement ?

**it's not crucial the idea just came to mind when I kept going back and forth and had multiple "release not found" errors.

2- I believe the last selection only affects the PR mode. Instead of writing that, couldn't you just hide it in the other mode ?

**Comment by mohamedAdhamc** [comment]
Ok, now the action runs successful and everything. It says to check the release_notes.md/.html file. However, no such files are present. Any idea as to what is happening or where I should be looking for it ?

**Comment by Ahmed-Khaled-dev** [comment]
Screenshot from 2024-10-24 12-32-02

If the GitHub Action ran successfully, you should see the generated markdown release notes added as the description of the new release. Here, as an example, on this release, you should see the markdown release notes added instead of the sentence "Release version 1.5.1," and you should see the HTML release notes file added as an asset in the new release.

It says "check the release_notes.md/.html file" since the first step in the below image only generates the release notes and outputs them in files in the GitHub Action runner/server. The following 2 steps are the ones that take release_notes.md and use its content to update the new release description and take release_notes.html and adds it as an asset to the new release.

image

**Comment by mohamedAdhamc** [comment]
Oh, yes I see what you mean. I'll do a little more testing, and then I think we should be good here.

**Review by mohamedAdhamc — APPROVED** [review]
Looks good to me, works as expected.

**Comment by ice0** [comment]
Merged. Thanks for the awesome contribution!

**Pull request merged**
