### PR TITLE
Add "Scale to fit canvas" button to Import dialog

### LINKED ISSUE #1126: Add "Scale to fit canvas" checkbox to image import dialog.
Currently, "Scale to fit canvas" is an option in preferences -
screenshot_002

I think it is logical to place in Import Image dialog (appears after "File" - "Import"), so user can decide if he wants to fit canvas or not right during import -
screenshot_003

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/87783238-add-scale-to-fit-canvas-checkbox-to-image-import-dialog?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by FirasH**
Fixes #1126

### CODE REVIEW

**Comment by morevnaproject** [comment]
I tested and  it works perfectly! Can we remove this option from Preferences now? ^__^

**Comment by FirasH** [comment]
> I tested and it works perfectly! Can we remove this option from Preferences now? ^__^

Do you want to remove in this same merge request?

**Comment by FirasH** [comment]
@morevnaproject the option should also be added to `Import Sequence...` as well, working on it.

**Comment by FirasH** [comment]
This same option is used also in other importing dialogs...

At this point I think it would be better to define the widget outside the specific method to avoid code repetition and add it to all dialogs that make use of it.

**Comment by morevnaproject** [comment]
I have tested this feature and it works perfectly for me. Can you please rebase? ^__^

**Comment by FirasH** [comment]
mmm, this is not good...

**Comment by FirasH** [comment]
How can I revert this rebase commit and just force push my commits?

**Comment by FirasH** [comment]
@morevnaproject done!

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
