### PR TITLE
refactor!: rename action "KeyframeToggl" as "KeyframeToggle"

### PR DESCRIPTION
**Pull request by rodolforg**
and remove unused #include

BREAKING CHANGE: synfigapp API changed:
- action "KeyframeToggl" renamed as "KeyframeToggle"

### CODE REVIEW

**Review by mohamedAdhamc — COMMENTED** [review]
How about also renaming the action file "keyframetoggl.cpp/.h" it appears to have the same typo ?

**Comment by rodolforg** [comment]
> How about also renaming the action file "keyframetoggl.cpp/.h" it appears to have the same typo ?

@ice0 ?

**Comment by ice0** [comment]
> > How about also renaming the action file "keyframetoggl.cpp/.h" it appears to have the same typo ?
> 
> @ice0 ?

I think yes, it's better to rename it.

**Comment by rodolforg** [comment]
Done

> I think yes, it's better to rename it.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
