### PR TITLE
Svg_parser: fix command 'a' for Path element: ellipse arcs work now

### PR DESCRIPTION
**Pull request by rodolforg**
Compare it:
https://www.w3.org/TR/SVG/images/paths/arcs01.svg
Synfig from v1.2.1 to 1.4.2 do not render anything.

SVG-Arc2

### CODE REVIEW

**Comment by rodolforg** [comment]
Force-pushed to fix the new LGTM alerts

**Comment by rodolforg** [comment]
Argh. I don't know if I should try to fix it again.

**Review by ice0 — DISMISSED** [review]
Please rebase

**Comment by rodolforg** [comment]
rebased :)

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
