### PR TITLE
Fixed rename file extension when rendering based on 'target'

### LINKED ISSUE #627: Feature request: Rename file extension when rendering based on 'target'
**Synfig version & platform**:
1.2.2

**Issue description**:
As the title. Use case: I've saved as png. Now I want to render as gif. And it overwrites my png. When I change the target to gif my file extension in the textbox above should change to gif (or mpeg or whatever)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63742324-feature-request-rename-file-extension-when-rendering-based-on-target?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
### **Topic:** Fixes #627 
Now every-time the target changes filename will be updated with new .ext if required.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hi! Thank you for PR, this is a good start!
There is a following problem in current implementation: Synfig can have different set of target, depending on compilation options. I.e., user can have synfig compiled without "magick++" module. In this case, targets in dropdown list will have different order, which is not corresponding to your array -
```
string ext[] = {"null", ".bmp", ".png", ".dv", ".avi", ".gif", ".png", ".jpg", ".gif", ".mng", "null", "null", ".exr", ".png", ".png", ".ppm", ".yuv"};
```

**Comment by ankit-kumar-dwivedi** [comment]
> user can have synfig compiled without "magick++" module. In this case, targets in dropdown list will have different order, which is not corresponding to your array -
> 
> ```
> string ext[] = {"null", ".bmp", ".png", ".dv", ".avi", ".gif", ".png", ".jpg", ".gif", ".mng", "null", "null", ".exr", ".png", ".png", ".ppm", ".yuv"};
> ```
@morevnaproject 
In that case I can simply replace the vector with an map as in that case order is not going to matter the extension being selected I'll get it in string from the target Dropbox.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject please review the changes :smile_cat:

**Comment by morevnaproject** [comment]
Hey, I did a quick test and it works as expected now! ^__^

Just want to suggest a few improvements to the code:

1. I think we can remove everything that maps to "null"  - ```{"Auto","null"},{"null","null"},{"null-tile","null"}```. 

If those entries will be removed, then ```ext.find(target_names[i])``` (line 250) will return ```ext.end()``` and that should be fine. 

Also, that will allow to simplify condition from ```if(itr != ext.end() && (itr->second)!="null")``` to ```if(itr != ext.end())``` (line 252).

2. I forgot one more possible target - "libav". It should map to ".avi" extension. Can you please add this as well? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Done Changes !

**Comment by morevnaproject** [comment]
Looks good to me! Thank you and congratulations with the first code contribution! ^__^

**Pull request merged**
