### PR TITLE
[Synfig Studio] Noticeable progress bar

### LINKED ISSUE #2017: [Synfig Studio] Small progress bar on status bar
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
Import any raster image and convert it to vector. The progress bar height is very small to be noticed.

Screenshot from 2021-02-13 19-43-29

### PR DESCRIPTION
**Pull request by Keyikedalube**
Fixes #2017 

Screenshot from 2021-02-13 19-56-29

### CODE REVIEW

**Comment by morevnaproject** [comment]
Looks cool!

**Comment by rodolforg** [comment]
How does the render progress bar in Info Panel do?

**Comment by Keyikedalube** [comment]
> How does the render progress bar in Info Panel do?

Its height is set to 20px
https://github.com/synfig/synfig/blob/10b7715872763b7b488e43fb2284f6535336a895/synfig-studio/src/gui/resources/css/synfig.css#L1-L3

I didn't know that there was another progress bar on Synfig's status bar while working on this PR  #1789

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
