### PR TITLE
Migrate old containers from widget classes to new containers

### LINKED ISSUE #1787: Migrate old Widget_Defaults container to Gtk::Grid
**Issue description**:
1. `Gtk::Table` to `Gtk::Grid`
2. `Gtk::VBox` &nbsp; to `Gtk::Grid`

Screenshot from 2020-10-19 10-46-43

Both Table and Grid has `attach()` functions but their arguments differ. You've to adapt the existing [Table](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Table.html#a28b6926e68337a51ba29f2b4dd69f087) container to [Grid](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Grid.html#a664d8700c0a8176c2e2595e1d9938ff0) by eliminating most of its arguments.

Pen and paper is a good starting point to visualize how each widgets are supposed to be attached :)

### PR DESCRIPTION
**Pull request by Keyikedalube**
Closes #1787

Also improved color edit widget UI:
- 
Screenshot from 2020-10-30 16-31-02
- 
Screenshot from 2020-10-30 16-08-35

### CODE REVIEW

**Comment by ice0** [comment]
I don't know when this changed, but I see the difference in the dialog buttons.

1.3.16
Screenshot_32

Current
Screenshot_33

Can you check this?

**Comment by Keyikedalube** [comment]
- If you mean button size
That's because of new CSS applied only to synfig workspace. Not dialog buttons and other widgets.

- Or Close button icon missing
That's default GNOME style. Explained in [this post](https://stackoverflow.com/questions/2188659/stock-icons-not-shown-on-buttons).

Both of them are not the result of this PR :(

**Comment by ice0** [comment]
I mean box on button image is cropped from bottom on left button, and from top on middle button.

**Comment by Keyikedalube** [comment]
Strange.

I possibly couldn't have touched the buttons code. BTW, there isn't `Gtk::ButtonBox` in `Widget_ColorEdit` class there's only notebook tab. Buttons must have been added from somewhere.

**Comment by Keyikedalube** [comment]
Anyway, I'm building synfig from master branch now without this PR changes to see if I might get the same output or not.

**Comment by Keyikedalube** [comment]
- Autotools
Screenshot from 2020-11-01 16-15-57
- CMake
Screenshot from 2020-11-01 16-16-08

Issue is not from my side. It's CMake. Tested on master branch.

Also, found out Canvas Properties toggle link button
Screenshot from 2020-11-01 16-24-21

Rendered icons look OK. I opened them manually from my file manager.
Must be the way CMake builds synfigstudio. Autotools no prob.

**Comment by ice0** [comment]
This is very interesting! Thank you for investigating!

**Comment by ice0** [comment]
One more question about margins - maybe better to move it to CSS and make them customizable? Or maybe it is unnecessary?

**Comment by Keyikedalube** [comment]
> One more question about margins - maybe better to move it to CSS and make them customizable? Or maybe it is unnecessary?

Yup, that's what CSS is intended for :) As much as possible we should try to separate out logic *(C++)* and UI *(glade, css)* code. My PR is quite bloated with `widget->set_margin_start/end/top/bottom` statements. Thanks for the idea :smile: 

Working on the changes...

**Comment by Keyikedalube** [comment]
Updating...

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
