### PR TITLE
Update time track area when keyframe is changed from keyframe header

### LINKED ISSUE #1454: new timetrack doesn't autoupdate when user moves a keyframe in Timetrack panel
**Synfig version & platform**:
master 6d3f75f

**Issue description**:
The new timetrack doesn't autoupdate when user moves a keyframe in Timetrack panel.
If user clicks on timetrack area, it refreshes correctly though;

### LINKED ISSUE #2283: Timetrack Panel not updated after dragging keyframe
**Describe the bug**
When user dragging keyframe the brown line on TimeTrack panel is not updated.

**To Reproduce**
1. Open sample file - [bug-kf-drag.sifz.tar.gz](https://github.com/synfig/synfig/files/7044014/bug-kf-drag.sifz.tar.gz)
2. Drag keyframe at 24f to some other time
screenshot_001
3. See the bug: the brown line on TimeTrack panel remains in its place (not moved together with keyframe)
screenshot_003

**Expected behavior**
The brown line should move together with keyframe marker.

**Screenshots**
Video demonstration - https://youtu.be/IaE7rEMP3qs

**System information:**
 - OS: Linux Mint
 - OS version: 19
 - Commit ID: Appimage 1.5.0

### PR DESCRIPTION
**Pull request by ice0**
Fix #2283
Fix #1454

### CODE REVIEW

**Review by morevnaproject — APPROVED** [review]

**Comment by morevnaproject** [comment]
Works perfectly here. Thank you!

**Review by rodolforg — COMMENTED** [review]
I'd prefer to implement the fix in the `Widget_Timetrack` itself.
Maybe in `on_canvas_interface_changed()`. It would connect the signal keyframe-changed to a slot as you did here, but cancel/delete the connection when another (improbable) `canvas_interface` is set.

This way, if we find another usage for `Widget_Timetrack` somewhere else, this issue won't happen again.

**Comment by ice0** [comment]
@rodolforg 
Moved code to `Widget_Timetrack`

**Review by rodolforg — APPROVED** [review]

**Review by rodolforg — CHANGES_REQUESTED** [review]
canvas_interface could be null

**Review by rodolforg — APPROVED** [review]

**Comment by ice0** [comment]
@morevnaproject 
Please set project if you need this commit backported.

**Comment by morevnaproject** [comment]
@ice0 Thank you! We do not need to back port this commit, as this issue is related to new TimeTrack, which exist in 1.5.0 only. ^__^

Looking forward for merge of this PR!

**Pull request merged**
