### PR TITLE
fix: pasting of external exported valuenodes

### LINKED ISSUE #1393: File corruption: Copy-paste layers with exported values from one file to another
There is a very common situation when user can get his file corrupted by simply copy-pasting layers from one file to another. This happens if layer contains exported values (note that bones are exported values too!).

Steps to reproduce this situation:
1. Launch Synfig and create new file.
2. Create a simple Circle Layer.
3. Select Circle Layer, right-click its Radius parameter and select "Export".
4. Enter name for exported value, i.e. "test". Click Export.
5. Save file as "file1.sifz"
6. Hit Ctl+C to copy circle layer to clipboard.
6. Create a new file in other tab.
7. Hit Ctrl+V to paste circle from clipboard. Circle will appear on workspace. Notice, that layer is copied, but it is still references exported value from "file1.sifz"
8. Save file as "file2.sifz"
9. Quit Synfig.
10. Now remove (or rename) "file1.sifz".
11. Launch Synfig and try to open "file2.sifz".
12. Error:
screenshot_001

@rodolforg @ice0 @FirasH  I think this is a top-priority issue to solve for next stable release (1.4.1 or 1.6.0).

What should be done here:

1. Change how Synfig deal with pasting layers when layer has exported values.
2. Change how Synfig handles situations with broken links to exported values in external documents.

### PR DESCRIPTION
**Pull request by rodolforg**
Fix #1393

### CODE REVIEW

**Comment by rodolforg** [comment]
It does work fine.
However, I didn't try to fix the copy'n paste issues for Layer_Duplicate or Layer_Skeleton or Layer_Skeleton_Deform.

**Comment by rodolforg** [comment]
@morevnaproject  could you please test it? I hope it works like you described on synfig-docs-dev.

**Comment by morevnaproject** [comment]
Hi! I have finally tested the feature. ^__^

First of all, I would like to say that this feature is an epic achievement in solving this old and annoying problem of copy-pasting. This is so exciting!

Here is a set of files, which I used to test this PR - 
[2086.zip](https://github.com/synfig/synfig/files/6415790/2086.zip)

It contains 2 files:
* export-a.sifz
* export-b.sifz

I opened both files and copied "Group 1" layer from `export-a.sifz` to `export-b.sifz`.
It displays following dialog for me (as expected):

screenshot_001

I have notice following issues:
1. The leftmost column is too tiny - the heading with "Copy?" title (1) is only partially visible.
2. If I click Cancel button (2), then the layer is copied anyway. As user I would expect the copy operation to be aborted. ^__^
3. After playing a bit with the feature, I found that it will be useful to have path in "Source file" column always visible (3). The [reference document](https://synfig-docs-dev.readthedocs.io/en/latest/projects/copy-paste-exported-values.html) describes different behaviour, but after using the feature I think we should change that.
4. When I disabled checkbox in second row (for "t2" value) the "OK" button remains inactive -
screenshot_002
Disabling checkbox for "t2" value should tell synfig to **not** copy  exported value. Instead it should be linked from `export-a.sifz` file, so no conflict take place and OK button should become active.

Thanks again for implementing this! :clap:

**Comment by rodolforg** [comment]
> The leftmost column is too tiny - the heading with "Copy?" title (1) is only partially visible.

Yes, I'm fighting against Gtk to make it right



> If I click Cancel button (2), then the layer is copied anyway. As user I would expect the copy operation to be aborted. ^__^

Fixed


>     3\. After playing a bit with the feature, I found that it will be useful to have path in "Source file" column always visible (3). The [reference document](https://synfig-docs-dev.readthedocs.io/en/latest/projects/copy-paste-exported-values.html) describes different behaviour, but after using the feature I think we should change that.

Ok, I'll do it.



>     4\. Disabling checkbox for "t2" value should tell synfig to **not** copy  exported value. Instead it should be linked from `export-a.sifz` file, so no conflict take place and OK button should become active.

Problem is that they are of a different type: vector x real.

**Comment by rodolforg** [comment]
Any suggestions about the text in the dialog?

**Comment by morevnaproject** [comment]
>> screenshot_002
>>  4. Disabling checkbox for "t2" value should tell synfig to **not** copy  exported value. Instead it should be linked from `export-a.sifz` file, so no conflict take place and OK button should become active.
>
> Problem is that they are of a different type: vector x real.

Yes, they are different types. 
But in this case the layer will reference "t2" parameter from `export-a.sifz` file.
Here I have recorded a short video to demonstrate how it currently works ^__^ (i have used version of Synfig without changes made in this PR) - https://www.youtube.com/watch?v=Q4uJ0HGasfg

**Comment by morevnaproject** [comment]
> Any suggestions about the text in the dialog?

I suggest to use "exported value" instead of "exported valuenode" in the text.
Also, I can suggest just a slight change for "Note" text -

> if you choose to keep a valuenode linked to other file, you won't be able to load this one if source file(s) are deleted, moved or renamed.

I have made attempt to remove double "if":

> If you choose to keep an exported value linked to other file, then your current file become dependent on source (referenced) file. That means you will not be able to load this file if any source file is deleted, moved or renamed.

I am not an expert in English, though. ^___^"

**Comment by morevnaproject** [comment]
> And the tooltips I added in last commit?

Tooltips are great!
There is only one issue - the tooltip for "t3" value is empty in my case ^__^ -
screenshot_004

**Comment by rodolforg** [comment]
> I am not an expert in English, though. ^___^"

Me neither ;)

>  There is only one issue - the tooltip for "t3" value is empty in my case ^__^ -

It was intentional, but I'll fix it.

**Comment by rodolforg** [comment]
>  But in this case the layer will reference "t2" parameter from `export-a.sifz` file.

Ouch ! lol

I fixed it as well as the text change you suggested.

**Comment by morevnaproject** [comment]
> I have notice following issues:
>  ...

>  2. If I click Cancel button (2), then the layer is copied anyway. As user I would expect the copy operation to be aborted. ^__^

Works as expected now. ^__^

> 3. After playing a bit with the feature, I found that it will be useful to have path in "Source file" column always visible (3). The [reference document](https://synfig-docs-dev.readthedocs.io/en/latest/projects/copy-paste-exported-values.html) describes different behaviour, but after using the feature I think we should change that.

Confirmed as fixed.

> 4. When I disabled checkbox in second row (for "t2" value) the "OK" button remains inactive -

Confirmed as fixed.


We have following issue remaining:

> 1. The leftmost column is too tiny - the heading with "Copy?" title (1) is only partially visible.

...and here are some more, which I've got after testing latest version of this PR:

5. After text change the dialog became too wide. I suggest to add line break after "... (referenced) file." words -
screenshot_001

I have found no other issues so far. Great work! ^__^

**Comment by ice0** [comment]
> 1. After text change the dialog became too wide. I suggest to add line break after "... (referenced) file." words -

Maybe just allow word wrap in the label?

**Comment by rodolforg** [comment]
i think the only missing issue is reported here: https://github.com/synfig/synfig/issues/1393#issuecomment-831349492

**Comment by morevnaproject** [comment]
> i think the only missing issue are reported here:
> 
>     * [#1393 (comment)](https://github.com/synfig/synfig/issues/1393#issuecomment-831349492)
> 
>     * [#1393 (comment)](https://github.com/synfig/synfig/issues/1393#issuecomment-810306466)

For first item I have outlined expected behavior in this comment - https://github.com/synfig/synfig/issues/1393#issuecomment-832781258
I need to check how it works in current implementation...

For second item I have wrote comment right now ^__^ - https://github.com/synfig/synfig/issues/1393#issuecomment-850523858

**Comment by rodolforg** [comment]
@morevnaproject I think I finally finished it. Could you please test it?

Now it handles these cases too:
- if the layers to be pasted have two different valuenodes but with same ID (different files), list them in separate rows
- if an exported valuenode is a dependency for another exported valuenode to be pasted (like that bone example or via converters)… well, the dependency is forced to be a foreign link if user choose to the 'main' valuenode to be a foreign link.

**Comment by morevnaproject** [comment]
Apologies for delay. Now I'm back to test this PR!

**Comment by morevnaproject** [comment]
Hi! I have tested this PR and it works good for me!

Just a few things to mention:

1. I haven't used this feature for a long period and with a fresh eyes I found text at the top of the dialog a bit confusing. 
screenshot_005

So, I've come up with better version, how about to replace it with this one? -

> Use checkboxes below to choose which exported values should be copied (transferred) to current document.
> 
> If checkbox is turned off for particular value, then this exported value will not be copied, it will be linked to the exported value in original file.

2. It would be nice to replace "link" icon according to this proposal - https://github.com/synfig/synfig/issues/1393#issuecomment-852847988 (see first part of the message)

Thank you!

**Comment by rodolforg** [comment]
@morevnaproject done! :)

**Comment by morevnaproject** [comment]
Testing now! ^__^

**Comment by morevnaproject** [comment]
I am sorry to say that, but I have found one more bug.
This is related with copying nested exported values.

Steps to reproduce:
1. Download [the archive with sample files (2086-2.zip)](https://github.com/synfig/synfig/files/7026441/2086-2.zip), unpack. 
2. Open "2086-test-2-nested.sifz" file.
3. Copy layer "Circle119" to clipboard
4. Open "2086-test-2-nested-empty.sif" file (this is just an empty Synfig document).
5. Paste "Circle119" layer from clipboard.
6. A dialog appears, which is asking what to do with exported values. Make sure you have all checkboxes enabled (copy all exported values). Click OK.
screenshot_001
7. Select "Circle119" layer, expand its "Origin" parameter and change value of "X-Axis" sub-parameter (it is linked to "t-child" exported value).
8. Result: The value of "X-Axis" sub-parameter has changed, but the value of "Feather" parameter (which is also linked to "t-child" exported value) remains unchanged. This is because "X-Axis" sub-parameter remains linked to "t-child" exported value **from original file** (not in the same file). Expected behavior: it should be linked to "t-child" exported value in the **same file** (as we chose to copy it in step 6).

I guess it will be easier to see demonstration of the bug in this video ^__^ - https://youtu.be/LOlg_SG52dE

**Comment by rodolforg** [comment]
> I am sorry to say that, but I have found one more bug.

I'm glad you find it :)

It should be solved with latest commit.

**Comment by morevnaproject** [comment]
Hi! I have tested the latest commit and issue is fixed now! Thank you!

I found one more (cosmetic) issue, it is shown in this video - https://youtu.be/qy1gY2nFLp0

Steps to reproduce:

1. Download the archive with sample files (2086-2.zip), unpack.
2. Open "2086-test-2-nested.sifz" file.
3. Copy layer "Circle119" to clipboard
4. Create **new** file.
5. Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
6. In the appeared dialog disable checkbox for "t-child" exported value. Click OK.
screenshot_002
7. Now open  "2086-test-2-nested-empty.sif" file.
8. Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
9. You will see that in "Source file" column shown wrong name of source file.
screenshot_004

**Comment by morevnaproject** [comment]
Oh, and I found one more issue:

1. Download the archive with sample files (2086-2.zip), unpack.
2. Open "2086-test-2-nested.sifz" file.
3. Copy layer "Circle119" to clipboard
4. Open "2086-test-2-nested-empty.sif" file.
5. Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
6. A dialog appears, which is asking what to do with exported values. Make sure you have all checkboxes enabled (copy all exported values). Click OK.
screenshot_005
7. Now again: Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
8. A dialog appears again, but it shows only "t-parent" exported value. That's logically **correct** - the exported value with such name is already exists in source and destination file. So it is no matter if we choose to copy "t-parent" or not - in both cases we have no control on "t-child" exported value (it will follow the same choice as we did for "t-parent").
screenshot_007
9. BUT, let's try to rename "t-parent" exported value into "t-parent-2".
screenshot_006
In this case "t-parent-2" is not exists in destination document. So, if we choose to copy it, then its child value "t-child" can belong to destination file or be linked to source file. User should have an ability to choose that.

Thank you! ^__^

**Comment by rodolforg** [comment]
Thank you, Konstantin for your great review!
I decided to split this PR. Some not related changes that aren't directly related to the bug/feature request.

I started with #2296 - code in this PR was inspired by the one I made for layer_duplicate action - but improved. So I decided to provide it in that separate PR.

I'll split the copy fix I did here (copy a group layer but don't duplicate its contents if they are both selected).
Your last review comments are not so trivial to me, so I want to organize my mind and this PR better in order to see a way to solve the problems you detected.

**Comment by morevnaproject** [comment]
Got it, thank you!

**Comment by morevnaproject** [comment]
I suggesting to merge this PR and open a separate issue for bug described in https://github.com/synfig/synfig/pull/2086#issuecomment-904310322
In this situation Synfig will become better  and the issue from https://github.com/synfig/synfig/pull/2086#issuecomment-904310322 is not that critical and can be fixed later.

@ice0 @rodolforg What do you think about that? ^__^

**Comment by ice0** [comment]
@morevnaproject Agree.

**Comment by morevnaproject** [comment]
@rodolforg Then, can you  please rebase it? ^__^

**Comment by rodolforg** [comment]
Just recording here all bugs @morevnaproject caught in this long dialog. AFAIK, only the last issue is pending.
So here it is for testing all known previous problems this PR had along its development (and the pending one)

https://github.com/synfig/synfig/pull/2086#issuecomment-831343398

    1. The leftmost column is too tiny - the heading with "Copy?" title (1) is only partially visible.
    2. If I click Cancel button (2), then the layer is copied anyway. As user I would expect the copy operation to be aborted. ^__^
    3. After playing a bit with the feature, I found that it will be useful to have path in "Source file" column always visible (3). The reference document describes different behaviour, but after using the feature I think we should change that.
    4. When I disabled checkbox in second row (for "t2" value) the "OK" button remains inactive -
    screenshot_002
    5. Disabling checkbox for "t2" value should tell synfig to not copy exported value. Instead it should be linked from export-a.sifz file, so no conflict take place and OK button should become active.


https://github.com/synfig/synfig/pull/2086#issuecomment-832768364

    tooltip for non-existent external valuenode


https://github.com/synfig/synfig/issues/1393#issuecomment-831349492

Let's think about the following situation:

    We have a skeleton layer and one of its bones is exported (valueA)
    The origin of this exported bone is exported too (valueB)
    User copies skeleton layer to other document
    The dialog displays both values "valueA" and "valueB".
    User chooses NOT to copy "ValueA" (bone). So, it will be linked instead.
    ...but that means we cannot copy "ValueB"! Because it belongs to "ValueA", which cannot be changed (as it is linked, not copied).

How can we solve this?


https://github.com/synfig/synfig/issues/1393#issuecomment-810306466

I think we need a small icon to a value node is from an external canvas.
The following icon is used to indicate a layer parameter is a value node (in Parameter panel):
valuenode_icon
How to change it for indicate this difference?
Or doesn't it worth?


https://github.com/synfig/synfig/pull/2086#issuecomment-860039774

    if the layers to be pasted have two different valuenodes but with same ID (different files), list them in separate rows
    if an exported valuenode is a dependency for another exported valuenode to be pasted (like that bone example or via converters)… well, the dependency is forced to be a foreign link if user choose to the 'main' valuenode to be a foreign link.


https://github.com/synfig/synfig/pull/2086#issuecomment-897559400

It would be nice to replace "link" icon according to this proposal - File corruption: Copy-paste layers with exported values from one file to another #1393 (comment) (see first part of the message)
https://github.com/synfig/synfig/issues/1393#issuecomment-852847988


https://github.com/synfig/synfig/pull/2086#issuecomment-903201870

Steps to reproduce:

    Download the archive with sample files (2086-2.zip), unpack.
    Open "2086-test-2-nested.sifz" file.
    Copy layer "Circle119" to clipboard
    Open "2086-test-2-nested-empty.sif" file (this is just an empty Synfig document).
    Paste "Circle119" layer from clipboard.
    A dialog appears, which is asking what to do with exported values. Make sure you have all checkboxes enabled (copy all exported values). Click OK.
    screenshot_001
    Select "Circle119" layer, expand its "Origin" parameter and change value of "X-Axis" sub-parameter (it is linked to "t-child" exported value).
    screenshot_002
    Result: The value of "X-Axis" sub-parameter has changed, but the value of "Feather" parameter (which is also linked to "t-child" exported value) remains unchanged. This is because "X-Axis" sub-parameter remains linked to "t-child" exported value from original file (not in the same file). Expected behavior: it should be linked to "t-child" exported value in the same file (as we chose to copy it in step 6).

I guess it will be easier to see demonstration of the bug in this video ^__^ - https://youtu.be/LOlg_SG52dE


https://github.com/synfig/synfig/pull/2086#issuecomment-904303309

Steps to reproduce:

    Download the archive with sample files (2086-2.zip), unpack.
    Open "2086-test-2-nested.sifz" file.
    Copy layer "Circle119" to clipboard
    Create new file.
    Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
    In the appeared dialog disable checkbox for "t-child" exported value. Click OK.
    screenshot_002
    Now open "2086-test-2-nested-empty.sif" file.
    Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
    You will see that in "Source file" column shown wrong name of source file.
    screenshot_004
I found one more (cosmetic) issue, it is shown in this video - https://youtu.be/qy1gY2nFLp0


https://github.com/synfig/synfig/pull/2086#issuecomment-904310322

[PENDING]
    Download the archive with sample files (2086-2.zip), unpack.
    Open "2086-test-2-nested.sifz" file.
    Copy layer "Circle119" to clipboard
    Open "2086-test-2-nested-empty.sif" file.
    Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
    A dialog appears, which is asking what to do with exported values. Make sure you have all checkboxes enabled (copy all exported values). Click OK.
    screenshot_005
    Now again: Choose "Edit" - "Paste" to insert "Circle119" layer from clipboard.
    A dialog appears again, but it shows only "t-parent" exported value. That's logically correct - the exported value with such name is already exists in source and destination file. So it is no matter if we choose to copy "t-parent" or not - in both cases we have no control on "t-child" exported value (it will follow the same choice as we did for "t-parent").
    screenshot_007
    BUT, let's try to rename "t-parent" exported value into "t-parent-2".
    screenshot_006
    In this case "t-parent-2" is not exists in destination document. So, if we choose to copy it, then its child value "t-child" can belong to destination file or be linked to source file. User should have an ability to choose that.

**Comment by morevnaproject** [comment]
@rodolforg Can you rebase, please? ^__^

**Comment by rodolforg** [comment]
(rebased) the pending issue is still... pending XD

**Comment by morevnaproject** [comment]
Thank you!

> the pending issue is still... pending XD

My opinion is that we should better merge this PR as is. This will make life of users much easier. 
The issue mentioned by me in https://github.com/synfig/synfig/pull/2086#issuecomment-904310322 is less significant. ^__^

**Comment by morevnaproject** [comment]
This one is ready to merge. But we need to rebase again. ^__^

**Comment by rodolforg** [comment]
Rebased again :)
If OK, please squash and merge. And report the pending problem.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Squashed and merged :)

Thank you!

**Pull request merged**
