### PR TITLE
chore: updated changelog

### PR DESCRIPTION
**Pull request by morevnaproject**

### CODE REVIEW

**Comment by ice0** [comment]
@morevnaproject 
I propose to extract 7266c58 to a separate PR
In this case, all other commits can be squashed.

**Comment by morevnaproject** [comment]
@ice0 Done! Please check #2782 ^__^

**Comment by ice0** [comment]
@morevnaproject please resolve conflicts.

**Comment by morevnaproject** [comment]
@ice0 Done

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
