### PR TITLE
Fixed current_rendered_frames_count assignment

### LINKED ISSUE #1304: "Render Progress" percentage is wrong if exporting a subset of frames
**Synfig version & platform**:
Master: c1b848

**Issue description**:
1. Open an animation project
2. Go to: `File > Render...` and iselect `Time` tab
3. Change `Start Time` and/or `End Time` (e.g. `Start Time: 30f` and `End Time: 60f`)

In the `Info Panel` the `Render Progress` percentage bar will display a negative value.

The percentage of progress should be relative to the selected interval of Time.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/90821008-render-progress-percentage-is-wrong-if-exporting-a-subset-of-frames?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by FirasH**
Fixes #1304

### CODE REVIEW

**Comment by FirasH** [comment]
@rodolforg I made a mess with git so this a new merge request

**Comment by rodolforg** [comment]
Nice.

You could git push --force after squash ;)

**Comment by FirasH** [comment]
> Nice.
> 
> You could git push --force after squash ;)

I didn't know that! Next time will do it.

**Comment by rodolforg** [comment]
;)

But use it with caution, as well as `git rebase`. They override git history!
Only do it for Pull Requests to avoid unnecessary commits. =)

**Comment by morevnaproject** [comment]
Works perfectly now! Thank you!

**Pull request merged**
