### PR TITLE
[Synfig Studio] Improve layout of Workspaces editor

### PR DESCRIPTION
**Pull request by FirasH**
Current layout:
current-workspace-editor

Improved layout:
improved-workspace-editor

### CODE REVIEW

**Comment by rodolforg** [comment]
The name "custom" is because there are 3 standand workspace layouts: they aren't shown on this list

**Comment by FirasH** [comment]
> The name "custom" is because there are 3 standand workspace layouts: they aren't shown on this list

Yes, I've thought about that.
Not sure if it's necessary to explicitly report it in the dialog title, it's not even present in the menu entry.

Anyway we could change it to "Custom workspaces editor" if you prefer :+1:

**Comment by ice0** [comment]
I agree. "Custom workspaces editor" looks more clear to me.

**Review by ice0 — APPROVED** [review]

**Comment by FirasH** [comment]
@ice0 done!

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
