### PR TITLE
fix: palette loading

### LINKED ISSUE #562: Memory leak on importing saved palette spal
**Synfig version & platform**:
1.3.8
Ubuntu 14.04

**Issue description**:

Loading an existing palette causes memory leak & the system runs out of memory because of this

Try loading this `spal` in synfig & observe that it fills your RAM & Swap within seconds & your system will become unresponsive

Note that this problem happens only with `spal` & does not happen if you try to load an equivalent gpl (GIMP palette)

[My Palette.spal.zip](https://github.com/synfig/synfig/files/2110057/My.Palette.spal.zip)
[Custom-Colors-Palette.gpl.zip](https://github.com/synfig/synfig/files/2110062/Custom-Colors-Palette.gpl.zip)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59799298-memory-leak-on-importing-saved-palette-spal?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2720: Palette import bug
**Describe the bug**
Importing GIMP(.gpl) palette into Synfig causes it to freeze.

**To Reproduce**

[Animation-#1.zip](https://github.com/synfig/synfig/files/9019957/Animation-.1.zip)
Import the given palette into synfig. It will freeze.
**Expected behavior**
It should successfully import the palette.

**System information:**
 - OS: Windows 10 64bit
 - OS version:21h2
 - Synfig version: 1.5.1

### PR DESCRIPTION
**Pull request by rodolforg**
Fix #562
Fix #2720

### CODE REVIEW

**Comment by rodolforg** [comment]
While working on this fix, I found out one problem left to solve:
`synfig::FileSystemNative::ReadStream` seems to not properly work with its `unget()` method.
It does not affect this fix, though.

**Comment by ice0** [comment]
> While working on this fix, I found out one problem left to solve: `synfig::FileSystemNative::ReadStream` seems to not properly work with its `unget()` method. It does not affect this fix, though.

I already fixed it, I will do PR tomorrow.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
Backport it?

**Comment by ice0** [comment]
> Backport it?

Sure.

Fixed problem with `unget()` here: https://github.com/synfig/synfig/pull/2730

**Pull request merged**
