### PR TITLE
[Release] Version 1.6.0

### PR DESCRIPTION
**Pull request by morevnaproject**

### CODE REVIEW

**Comment by rodolforg** [comment]
I suggest to include Text Layer improvements: accept font face name, allow user to select font face in GUI, speed up rendering a bit via font caching.
It would be good to include Arabic text support, and maybe my port to Cobra.

**Comment by morevnaproject** [comment]
The problem is: the more we cherry-picking commits into stable, the more efforts it takes to prepare every next release. Because with every next stable release I've had to rebase all cherry-picked commits and its often results in conflicts - it takes time to resolve all of them.

My plan is gradually roll all the features from master as a sequence of stable releases 1.6.0, 1.8.0, and so on. I hope to catch up with current master eventually and in the meantime users will be able to test fresh features by using development versions (1.5.0, 1.7.0, etc.).

I am sorry about this delay, but this is the current situation.

**Comment by morevnaproject** [comment]
> and maybe my port to Cobra

Can you please let me know which branch it is? Sorry, I couldn't find it. ^__^"

**Comment by rodolforg** [comment]
> The problem is: the more we cherry-picking commits into stable, the more efforts it takes to prepare every next release. Because with every next stable release I've had to rebase all cherry-picked commits and its often results in conflicts - it takes time to resolve all of them.

Wouldn't be easier to release dev versions with current master as you did in 1.3.x?

> Can you please let me know which branch it is? Sorry, I couldn't find it. ^__^"

Oh I realize I didn't push it because I'm waiting for finishing Arabic support (is it done, btw?)

**Comment by morevnaproject** [comment]
> Wouldn't be easier to release dev versions with current master as you did in 1.3.x?

That's exactly how I do for next dev version - 1.5.0.
But for stable 1.6.0 I had to rebase (I do not include full master branch in it).

> I'm waiting for finishing Arabic support (is it done, btw?)

I still have this problem ^__^ - https://github.com/synfig/synfig/pull/2232#issuecomment-894735526

BTW, so happy to hear that Text Layer is ported to Cobra!!! :tada:

**Comment by morevnaproject** [comment]
Closing this PR, because we will have different strategy for 1.6.0. Please see explanation in https://github.com/synfig/synfig/issues/2267#issuecomment-903212360 for details. ^__^

**Pull request closed without merging**
