### PR TITLE
Don't show multiple warning messages about old canvas. Closes #1380.

### LINKED ISSUE #1380: Multiple repeated warning messages when opening old file
When opening an old file (2017) https://wiki.synfig.org/images/3/38/Crosshair-leg.zip
I got this warning dialog:
Captura de tela de 2020-04-26 09-36-33

### PR DESCRIPTION
**Pull request by morevnaproject**
Closes #1380.

### CODE REVIEW

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
Oh. This didn't ship on 1.3.14 =o

**Comment by morevnaproject** [comment]
Everything is alright, I shipped it to 1.3.x earlier ^__^ - https://github.com/synfig/synfig/commit/a1afa66d2e4b0fb99901e238fe9e22c42a7bfa27

**Comment by morevnaproject** [comment]
No problem! I am happy that someone else (besides me) also keeping an eye on stuff like this. ^__^

**Pull request merged**
