### PR TITLE
test: marking_node_as_changed_changes_the_last_time_changed fails on AppVeyor

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
¬¬

**Review by mohamedAdhamc — COMMENTED** [review]
Looks good, this was causing all recent appveyor builds to fail. I wonder though why this only started being an issue now.

**Comment by ice0** [comment]
Hi guys! Sorry, I've been sick, will back tomorrow.

> Looks good, this was causing all recent appveyor builds to fail.

Please approve then.

image


> I wonder though why this only started being an issue now.

Unfortunately I can't reproduce it locally, so it looks like a bug in MSYS2 standard library.

**Review by mohamedAdhamc — APPROVED** [review]

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

P.S.
AppVeyor updated [Visual Studio 2019 images on April 14, 2023](https://www.appveyor.com/updates/2023/04/14/), but I still don't understand what has changed so I'll check a few ideas later.

**Pull request merged**
