### PR TITLE
Fix inconsistent dialog action button order. Closes #2038.

### LINKED ISSUE #2038: Inconsistent dialog action button order
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
Screenshot from 2021-02-19 19-44-40

Should be **Cancel** -> **OK** instead of the reverse

### PR DESCRIPTION
**Pull request by DhairyaBahl**
PR for the issue **Inconsistent dialog action button order #2038** .

### CODE REVIEW

**Comment by Keyikedalube** [comment]
Please fix these dialogs too:
- https://github.com/synfig/synfig/issues/2038#issuecomment-783140650
- https://github.com/synfig/synfig/issues/2038#issuecomment-791990353

Cancel or Close button should come first

**Comment by DhairyaBahl** [comment]
> Please fix these dialogs too:
> 
> * [#2038 (comment)](https://github.com/synfig/synfig/issues/2038#issuecomment-783140650)
> * [#2038 (comment)](https://github.com/synfig/synfig/issues/2038#issuecomment-791990353)
> 
> Cancel or Close button should come first

@Keyikedalube I am on it ^_^

**Comment by morevnaproject** [comment]
Hi! Thank you for the PR! Can you please change PR name to something meaningful, like "Fix inconsistent dialog action button order. Closes #2038."? ^__^

**Comment by DhairyaBahl** [comment]
> Hi! Thank you for the PR! Can you please change PR name to something meaningful, like "Fix inconsistent dialog action button order. Closes #2038."? ^__^

Changed the name of the PR to the suggested name ^__^

**Comment by morevnaproject** [comment]
Thank you!

**Comment by Keyikedalube** [comment]
@DhairyaBahl Color dialog's fixed

You haven't fixed the gradient dialog yet
Screenshot from 2021-03-20 20-11-17

**Comment by DhairyaBahl** [comment]
@Keyikedalube Ok I am starting working on it btw when I was solving the issue of text paragraph box, I saw this so this should also be resolved. 

Size of box is increasing.

image

**Comment by DhairyaBahl** [comment]
image
@Keyikedalube  I've made the required changes and fixed the gradient dialog box also. I will squash all of my commits after your approval ^__^

**Comment by Keyikedalube** [comment]
> I saw this so this should also be resolved.
> 
> Size of box is increasing.

No, just fix only the buttons in this PR. Stay within the scope of the issue.

**Comment by Keyikedalube** [comment]
Squashing is up to Synfig maintainers. But I suspect they might tell you to because your commit messages are not meaningful.

Just wait for their approval.

**Comment by Keyikedalube** [comment]
Tested. OK 🎉 🎆 

Thanks, @DhairyaBahl for the fixes :)

**Comment by DhairyaBahl** [comment]
> No, just fix only the buttons in this PR. Stay within the scope of the issue.
Okay ^__^

> But I suspect they might tell you to because your commit messages are not meaningful.
I will fix them while squashing :) or as per the suggestion of maintainers ^_^

> Thanks, @DhairyaBahl for the fixes :)
Already looking forward to solve another issue 😊✌

**Comment by DhairyaBahl** [comment]
@FirasH @Keyikedalube @ice0 Can anyone tell me why the appveyor build is failing here ? I mean i just did some minor changes !

Thanks ^_^

**Comment by FirasH** [comment]
> @FirasH @Keyikedalube @ice0 Can anyone tell me why the appveyor build is failing here ? I mean i just did some minor changes.
> 
> Thanks ^_^

The code is fine don’t worry. It’s a memory problem 👍

**Comment by DhairyaBahl** [comment]
@ice0 Kindly review this PR . If this is correct, then I will take another issue. Otherwise I will fix this one ^_^.

Thank You.

**Review by FirasH — APPROVED** [review]

**Comment by FirasH** [comment]
@DhairyaBahl I've reviewed your proposal and it seems fine to me.
You can already look into other issues if you want, @ice0 will check it for sure as he has a bit of time 👍

**Comment by DhairyaBahl** [comment]
> @DhairyaBahl I've reviewed your proposal and it seems fine to me.
> You can already look into other issues if you want, @ice0 will check it for sure as he has a bit of time 👍

I will now check out other issues as well. BTW you are talking about proposal or PR ?
Thank You @FirasH for approving the PR ^__^.

**Comment by FirasH** [comment]
> 
> 
> > @DhairyaBahl I've reviewed your proposal and it seems fine to me.
> > You can already look into other issues if you want, @ice0 will check it for sure as he has a bit of time 👍
> 
> I will now check out other issues as well. BTW you are talking about proposal or PR ? Actually I am also aiming for GSoC this year so it is a bit confusing for me. ^_^
> 
> Thank You @FirasH for approving the PR ^__^.

I'm talking about this PR, sorry for the misunderstanding 😉

**Comment by ice0** [comment]
> @FirasH @Keyikedalube @ice0 Can anyone tell me why the appveyor build is failing here ? I mean i just did some minor changes.

We just run out of space in the artifacts storage, so I temporary disabled them. 
Please rebase your commits - this will allow the Appveyor job to run with the new settings.

**Comment by DhairyaBahl** [comment]
> > @FirasH @Keyikedalube @ice0 Can anyone tell me why the appveyor build is failing here ? I mean i just did some minor changes.
> 
> We just run out of space in the artifacts storage, so I temporary disabled them.
> Please rebase your commits - this will allow the Appveyor job to run with the new settings.

@ice0 I am on it !

**Comment by DhairyaBahl** [comment]
@ice0 All the build are working finally ^__^ ! Any suggestions for this PR ?

**Comment by ice0** [comment]
@DhairyaBahl yes. It looks like you added extra commit to your PR (https://github.com/synfig/synfig/pull/2068/commits/bb11459cfd82bca8188fdb680c6504a669c37465), please check it.

**Comment by DhairyaBahl** [comment]
@ice0 Okay !! Understood ! Working on it now :)

**Comment by DhairyaBahl** [comment]
@ice0 I was fixing the commits in this branch ! But I forced push it which closed the  PR ! Now the branch is fixed so shall I create another PR for the same in which I will mention that new PR is in continuation with #2068 . Kindly tell me what to do. I was having no intention of closing this PR.

Thank You

**Comment by ice0** [comment]
@DhairyaBahl Am I right and these changes have already merged by [this PR](https://github.com/synfig/synfig/pull/2090)?

**Comment by DhairyaBahl** [comment]
@ice0  Yes ! Correct . Actually this PR is mistakenly closed by me while I was squashing the commits so that's why I made another one.  Thank you for merging that PR ^_^

**Pull request closed without merging**
