### PR TITLE
build(autotools): include UI files created via PR #2638

### PR DESCRIPTION
**Pull request by rodolforg**
Commit: 0b455f370fc7fcf3d640eecd4c988729af0d25d8

### CODE REVIEW

**Comment by rodolforg** [comment]
What happened here?
It happened also with last commit in master branch: https://github.com/synfig/synfig/commit/38cc869732922a2f2e61fb986626fb4fb513c952

**Comment by ice0** [comment]
> What happened here? It happened also with last commit in master branch: [38cc869](https://github.com/synfig/synfig/commit/38cc869732922a2f2e61fb986626fb4fb513c952)

I don't know. I will try to reproduce this locally.

**Comment by ice0** [comment]
@rodolforg 
Please rebase.

**Comment by rodolforg** [comment]
Done. But.... Failing again o.O

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
