### PR TITLE
Fixed crash of test on Void Linux

### PR DESCRIPTION
**Pull request by ice0**
Crash caused by incorrect work with iterators

Fixes issue: #2259

### CODE REVIEW

**Comment by rodolforg** [comment]
Hm… By reading the `connect_dynamic_param` internal code now, it seems it didn't need the `disconnect` call…
What do you think?

**Comment by newbluemoon** [comment]
Just for confirmation: this fixes the crash and the test passes. Thank you!

**Comment by ice0** [comment]
@rodolforg 

> Hm… By reading the `connect_dynamic_param` internal code now, it seems it didn't need the `disconnect` call…
> What do you think?

Agree. But without it, we lose `static_param_changed()` signal which is called from `disconnect_dynamic_param`.
I don't know why this signal is used, but it looks like a typo in the code.

**Comment by ice0** [comment]
@newbluemoon 
Thank you for testing!

**Review by rodolforg — APPROVED** [review]

**Comment by ice0** [comment]
> > Hm… By reading the `connect_dynamic_param` internal code now, it seems it didn't need the `disconnect` call…
> > What do you think?
> 
> Agree. But without it, we lose `static_param_changed()` signal which is called from `disconnect_dynamic_param`. I don't know why this signal is used, but it looks like a typo in the code.

I thought it was a typo and there must be `disconnect_static_param` somewhere, but this is not a typo and there is no such method.

**Pull request merged**
