### PR TITLE
refactor!: add etl::hermite::derivative() and remove ETL/calculus

### PR DESCRIPTION
**Pull request by rodolforg**
BREAKING CHANGE: ETL API changed:
- add etl::hermite::derivative()
- remove etl::derivative() ; not used
- remove etl::derivative<hermite<>>() ; use etl::hermite::derivative()
- remove etl::integral() ; not used

### CODE REVIEW

**Comment by rodolforg** [comment]
I believe next step here is to merge ETL/hermite with ETL/bezier, since hermite is just a simple "specialization" class of bezier class.
Then we can move new bezier file to synfig. Nothing on ETL depends on them.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
> next step here is to merge ETL/hermite with ETL/bezier, since hermite is just a simple "specialization" class of bezier class.

@ice0 do you agree? If so, what should be the final filename: bezier or hermite? (Note: both classes will exist in the same file)

**Comment by ice0** [comment]
Fast grep from sources:

```
include.*hermit - 18 matches
include.*bezier - 8 matches
```

First I thought about bezier, but now I am not sure about it.

**Comment by rodolforg** [comment]
Some with <hermite> includes <bezier> too. So there is even less with bezier directly.
Change to hermite, then?

**Comment by rodolforg** [comment]
Or, as the majority of code is in bezier, we keep it :)

**Comment by ice0** [comment]
I think the decision will be more clear when you check second bezier/hermite code.
P.S. I haven't checked them yet

**Pull request merged**
