### PR TITLE
Minor cleaning mainwindow

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hi! I have tested this PR and found one problem. When I start Synfig and choosing "View" - "Show Menubar" checkbox it doesn't work first time. When I do same command again then it works. That happens only first time after Synfig starts  - all subsequent calls of "View" - "Show Menubar" work as expected.

**Comment by rodolforg** [comment]
Ugh. Sorry.
But here in Gnome it vanishes the menu, how can you make it show again?

**Comment by morevnaproject** [comment]
@rodolforg Yeah, that's a common problem. ^__^ You can use button in top-left corner of canvas to call menu:

screenshot_006

**Comment by morevnaproject** [comment]
Merged now. Thank you! ^__^

**Pull request merged**
