### PR TITLE
fix regression: text layer accepts font filename again

### LINKED ISSUE #1766: Cannot select "Font Family" on Windows builds
**Synfig version & platform**:
1.5.0 Artifact build of 5 October 4699e374 (got from a pull request)

**Issue description**:
1. Create a new animation
2. Insert a `Text Layer` on Canvas
3. Change the `Font Family` value in the `Parameters Panel`

The dropdown menu is greyed out and it's not possible to select any fonts.
I could not use it the "old" way i.e. by copying the font file name in the `Font Family` box.

### PR DESCRIPTION
**Pull request by rodolforg**
closes #1766

### CODE REVIEW

**Comment by rodolforg** [comment]
Please cherry-pick to 1.3.x branch as it's a regression :P

Sorry my mistake

**Comment by ice0** [comment]
Added `backport` label, now @morevnaproject can easily filter PR that needs backporting.

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
> Added `backport` label, now @morevnaproject can easily filter PR that needs backporting.

@morevnaproject please don't forget to filter by Backport lable for open and closed PR XD

**Comment by rodolforg** [comment]
Whoops. This problem doesn't happen in 1.3.x :P

**Comment by morevnaproject** [comment]
I think this problem might appear in 1.4.x branch as soon as I backport latest Text Layer changes there. So, let's leave the "Backport" label on this PR. ^__^

**Comment by morevnaproject** [comment]
> as soon as I backport latest Text Layer changes there

I do not remember which PR I was about to backport :sob:

**Comment by rodolforg** [comment]
@morevnaproject maybe you could check via `git log synfig-core/src/modules/lyr_freetype/` the last commits of a branch and another :P 
Would it be about font caching or combobox for font family support?

**Comment by rodolforg** [comment]
https://github.com/synfig/synfig/pulls?q=is%3Apr+is%3Aclosed+freetype+

**Comment by morevnaproject** [comment]
Thank you! I have looked through them and I couldn't find the issue I looking for ^__^". I remember we had a discussion there about backporting, but I couldn't find those messages now. Well, anyway I remember there were problems with backporting (some conflicts), which was prevented me from cherry-picking that PR into 1.4.x...

**Pull request merged**
