### PR TITLE
Job for translations validation

### PR DESCRIPTION
**Pull request by AnishGG**
Fixes: #1250 
@ice0 is this what we need? Please review this

This is how it ran on the current branch(validation fails): https://travis-ci.com/github/AnishGG/synfig/builds/155064868

### CODE REVIEW

**Comment by ice0** [comment]
Nice! This exactly what I wanted. @morevnaproject can you take a look?

**Comment by morevnaproject** [comment]
@AnishGG The script looks good, but we need it executed for all branches and PRs (not for translations branch only). ^__^

**Comment by AnishGG** [comment]
Updated :D

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
