### PR TITLE
fix dashed outline behavior in non homogeous outline

### LINKED ISSUE #1589: Dashed outline rendered incorrectly in non-homogenous mode
**Synfig version & platform**:
master branch, 1.3.15

**Issue description**:
Dashed outline rendered incorrectly when homogenous parameter is off.

Sample file - 
[dashes.sifz.zip](https://github.com/synfig/synfig/files/4982099/dashes.sifz.zip)

Here is how it rendered in 1.2.2 -
screenshot_008

Here is result on master and 1.3.15 -
screenshot_007

### PR DESCRIPTION
**Pull request by rodolforg**
fix #1589

### CODE REVIEW

**Comment by rodolforg** [comment]
@morevnaproject

**Comment by morevnaproject** [comment]
Testing now

**Comment by morevnaproject** [comment]
Hi! I have tested and it looks much better now! But the count of dashes is different, comparing to previous versions:

In version 1.0.2, 1.2.2:
screenshot_002

In master branch (this PR):
screenshot_003

**Comment by rodolforg** [comment]
Hm…
In old versions the dash parameters are based on (that strange) internal distance unit: 0.1 length means 6px.
In current version (at least for this changed to homogeneous), they are based on spline length

**Comment by morevnaproject** [comment]
We should keep behavior of old version. ^__^

**Comment by morevnaproject** [comment]
BTW, shouldn't this parameter has effect on dash length? - 
screenshot_007

**Comment by rodolforg** [comment]
@morevnaproject  maybe it's fixed now

**Comment by morevnaproject** [comment]
Tested. t works great now! Thank you!

**Pull request merged**
