### PR TITLE
[Lottie exporter] Important comments regarding effects/fill.py

### PR DESCRIPTION
**Pull request by AnishGG**
@ice0 I have added some important comments in `python` file.
Please have a look.

### CODE REVIEW

**Comment by ice0** [comment]
Looks good, but can you also add a description about "ty"?

**Comment by AnishGG** [comment]
Will do :D

**Comment by AnishGG** [comment]
Have made the suggested changes.
Also I have skipped the travis and appveyor build because this is only addition of comments. ^__^

**Comment by ice0** [comment]
Awesome! Merged. Thank you!

**Comment by AnishGG** [comment]
Have raised an issue regarding the same: https://github.com/airbnb/lottie-web/issues/2042

**Pull request merged**
