### PR TITLE
[Lottie Exporter] Add support for vectorlength convert method

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Added support for vectorlength convert method.
@AnishGG please check ^__^

### CODE REVIEW

**Comment by morevnaproject** [comment]
TODO: Remove ATF flag on relevant test after this PR will be merged. See https://gitlab.com/synfig/synfig-tests/-/commit/05f12241914c6c0d5db49e5a5ea1cb254c21b9c1

**Comment by ice0** [comment]
@saurabh-ramola please rebase

**Comment by saurabh-ramola** [comment]
> @saurabh-ramola please rebase

Done :smiley:

**Comment by saurabh-ramola** [comment]
> @saurabh-ramola please rebase

Done :smiley:

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
