### PR TITLE
[CMake] Fixed path for splash screen image and added Adwaita icons for MSYS2 builds.

### PR DESCRIPTION
**Pull request by AYESDIE**
Fixes the issue raised [here](https://github.com/synfig/synfig/issues/1058#issuecomment-683697028) in #1058.

### CODE REVIEW

**Comment by FirasH** [comment]
I've completely reinstalled msys and rebuilt your branch, but still the interface has the same missing icons and missing splash screen.

I have no idea if there's an issue on my side, but my system is vanilla (just the programs I use, not even the antivirus)

**Comment by AYESDIE** [comment]
It doesn't have anything to do with the antivirus. After you run the cmake command, can you go and check whether there's /cmake-build-msys/output/share/icons/Adwaita` folder in there. It should be there after you run the cmake command. Also, in this case, if there's no source (which means you've not installed that dependency, it should fail at the cmake part). 

For me, on running the `./2-build-msys-cmake.sh`, those icons are placed in the correct folder once the cmake part is complete, and the splash screen is placed where it should be as well when it's built.

**Comment by AYESDIE** [comment]
Even on the appveyor build, the splash screen is generated into the correct folder [here](https://ci.appveyor.com/project/Synfig/synfig/builds/34965655/job/rppv0uph5s6y0u55?fullLog=true#L2649).

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
