### PR TITLE
[Synfig Studio] remove unused headers

### PR DESCRIPTION
**Pull request by rodolforg**
and do some sorting

### CODE REVIEW

**Comment by rodolforg** [comment]
It's an endless job! :P

**Comment by rodolforg** [comment]
Ouch. So CMake doesn't set the config.h file with the same #define Autotools does? :P

**Comment by ice0** [comment]
> Ouch. So CMake doesn't set the config.h file with the same #define Autotools does? :P

Some defines maybe missing. I will take a look.

**Comment by rodolforg** [comment]
Missing #defines (as per ipc.cpp):

- HAVE_SYS_TYPES_H 
- HAVE_SYS_STAT_H 
- HAVE_SYS_ERRNO_H
- HAVE_UNISTD_H 
- HAVE_FCNTL_H

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
