### PR TITLE
fix: Upgraded MLT version from '7.2.0' to '7.28.0' under MSYS2 environment

### PR DESCRIPTION
**Pull request by shreyaspranav**
This PR upgrades the MLT framework from 7.2.0 to 7.28.0 in the MSYS2 environment. This update addresses issue #3026 where the MLT framework fails to build in the MSYS2 environment.

### CODE REVIEW

**Comment by shreyaspranav** [comment]
Hi @rodolforg,

I apologize for the force pushes earlier. I wasn’t aware that the commit messages needed to follow a specific format. I used `git commit --amend` to change the commit message and then force pushed it.

I appreciate your understanding and sorry for the inconvenience caused.

Best,
Shreyas

**Comment by ice0** [comment]
Hi, Shreyas!

I plan to fix macOS build tomorrow.

**Comment by shreyaspranav** [comment]
Hi everyone,

I hope you’re doing well! I wanted to kindly ask if someone could take a moment to review my pull request. As the macOS build has been fixed and merged, could you please reapprove for the macOS CI workflow?

I’m eager to hear your feedback and make any necessary improvements.

Thank you for your time and assistance!

Best,
Shreyas

**Comment by shreyaspranav** [comment]
Hi everyone,

I apologize for not merging the macOS fix earlier. If possible, could you please reapprove the pull request for the workflows?

Thank you for your understanding and support!

Best,
Shreyas

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
