### PR TITLE
[Studio] Bone Tool: fix how to check for skeleton deformation

### PR DESCRIPTION
**Pull request by rodolforg**
No crashes in previous code, but it could eventually be a
false positive. Besides, it didn't make clear what it did.

### CODE REVIEW

**Comment by rodolforg** [comment]
Fix what I mentioned here: https://github.com/synfig/synfig/pull/2049#issuecomment-789483930

**Comment by ice0** [comment]
@rodolforg Can you rebase it, please?

**Comment by ice0** [comment]
@morevnaproject Can you check it, please?

**Comment by morevnaproject** [comment]
Testing now!

**Comment by morevnaproject** [comment]
Looks good to me! ^__^

**Review by morevnaproject — DISMISSED** [review]

**Comment by morevnaproject** [comment]
Woops... stop. Let me check one more thing... ^__^"

**Comment by morevnaproject** [comment]
Done. Looks good. ^__^

**Review by morevnaproject — APPROVED** [review]

**Pull request merged**
