### PR TITLE
Synfig couldn't open files with arabic filenames (Windows) - #1517

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
I couldn't test it though!
I just followed what @morevnaproject pointed in #1517

**Comment by morevnaproject** [comment]
Hi!
Thank you for the patch! 
I am digging it as well. Just wondering, why not use simply this? ^__^ -

```
#ifdef _WIN32
  argv = g_win32_get_command_line();
#else
  argv = g_strdupv (argv);
#endif
```

**Comment by rodolforg** [comment]
:)

I did that way to release memory on exit.
As code can be interrupted by exceptions and returned immediatly, that was one way to assure the memory release.

**Comment by morevnaproject** [comment]
I see now! Testing it...
Thank you!

**Comment by morevnaproject** [comment]
I have tested PR and for some reason this solution didn't worked - the filename wasn't converted properly.

I have used `argv = g_win32_get_command_line();` with following `g_strfreev(argv);` and it worked.

Still that wasn't enough to fix the issue, as the files were still failed to open (although the filename was decoded properly). So, I made other fixes in this PR - https://github.com/synfig/synfig/pull/1532

**Comment by rodolforg** [comment]
Ouch.
I pushed a new commit to show what would fix this problem, if you want to use it in your PR

**Comment by morevnaproject** [comment]
Will test it! ^__^

**Comment by morevnaproject** [comment]
It works now! ^__^

**Comment by morevnaproject** [comment]
I have added changes to #1532. Thank you!

**Pull request closed without merging**
