### PR TITLE
fix ask for file when layer->new layer->other->sound/image is invoked

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
fixes: #773 

@morevnaproject 
Please review and suggest if changes are required

### CODE REVIEW

**Comment by morevnaproject** [comment]
Thank you for the fix! It prompts for file as expected now. But when I import image, the layer dimensions are always set to square (60x60 px) -

screenshot_001

So, it would be nice to retrieve image dimensions and set layer parameters accordingly.
Thank you! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject was working on input dialog for vectorizer! will do the fix now [^_^]

**Comment by ankit-kumar-dwivedi** [comment]
Done the required changes but while checking import audio I encounter #819

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject done changes please review

**Comment by morevnaproject** [comment]
Looks good to me now! Thank you! ^__^

**Pull request merged**
