### PR TITLE
fix: Parameter & Library Panels are now more similar to TimeTrack Panel

### PR DESCRIPTION
**Pull request by rodolforg**
They now show stuff like #2385 and #2719 do.

### CODE REVIEW

**Comment by rodolforg** [comment]
(rebased)

**Comment by ice0** [comment]
Please rebase.

**Comment by rodolforg** [comment]
Rebased.
What is this error? o.O

**Comment by ice0** [comment]
> Rebased. What is this error? o.O

I broke it, sorry. Should be fixed with #2737

**Comment by ice0** [comment]
Please rebase again.

**Comment by rodolforg** [comment]
Done :)

**Comment by rodolforg** [comment]
> I broke it, sorry.

I don't get why. AppVeyor built it ok on the PR :/

**Comment by ice0** [comment]
> I don't get why. AppVeyor built it ok on the PR :/

This is because I didn't rebase it. So the changes from this PR (https://github.com/synfig/synfig/pull/2734) didn't included.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
