### PR TITLE
refactor: port CurveWarp to Cobra renderer engine

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
Not actually finished, but ready for tests @Svarov-RZM  XD

**Comment by Svarov-RZM** [comment]
> Not actually finished, but ready for tests

Oh hell yeah dude, let's go!
I promise to test it on weekends, too tired after work, it's been a bit overwhelming lately.

**Comment by rodolforg** [comment]
@Svarov-RZM rebased to current master. Sorry multiple commits, but I'm testing some stuff. I'll smash them later.
But it is basically only missing proper documentation for new classes.

**Comment by Svarov-RZM** [comment]
I've finished testing and honestly I thought there would be bugs since you said it's not finished yet, but I didn't find any. It works beautifully. Tested on vector and raster work and it all works just like in 1.0.2 version but faster and no longer crashes on zoom.

[CurveWarpTest.zip](https://github.com/synfig/synfig/files/14317719/CurveWarpTest.zip)
On this simple test file the performance is slightly more than 3 times faster than in 1.0.2 version (11 seconds against 37 seconds). It's hard to test the Curve Warp alone since other layers were ported too, but the important thing is that overall performance is better. Thank you! It's great to have Curve Warp layer in usable state again.

**Comment by rodolforg** [comment]
@Svarov-RZM thank you for testing and I'm glad it's working fine!
So I'll start working on Sphere Distort, Twirl, Noise Distort layers. Maybe I finish them until next weekend :)

**Review by morevnaproject — APPROVED** [review]

**Pull request merged**
