### PR TITLE
[Skeleton Tool] Can't load saved file that has layers made with skeleton tool

### LINKED ISSUE #1680: [Skeleton Tool] Can't load saved file that has layers made with skeleton tool
Can be replicated when you try to load this file.

[Robby.zip](https://github.com/synfig/synfig/files/5145213/Robby.zip)

This is what happens. 

Screenshot 2020-08-29 12:00:25

### PR DESCRIPTION
**Pull request by Aa20475**
This Closes #1680

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hi! Can you please fix conflicts?

**Comment by Aa20475** [comment]
Ahhh! I've included code that fixes #1683  in this PR itself. :man_facepalming: I'll split them up.

**Comment by morevnaproject** [comment]
Hi! I tested the PR. It works for regular Skeleton layer, but for Skeleton Deformation layer it still gives an error when loading saved file.

**Comment by Aa20475** [comment]
Hey! I am unable to replicate this. Can you please share the save file?

**Comment by Aa20475** [comment]
Agggh! I am not getting any error when I'm using the bone as usual. But when I use the "Create Layer" button to make the layer, synfig is crashing when saving the file. I'm working on it's fix.

**Comment by Aa20475** [comment]
Please verify @morevnaproject

**Comment by morevnaproject** [comment]
It works now! Thank you!

**Pull request merged**
