### PR TITLE
fix distortions at the end of lines made with the drawing tool

### LINKED ISSUE #2448: Distortions at the end of lines made with the drawing tool
**Describe the bug**
The drawing tool generates a distortion at the end of the drawing that is made. The error occurs when the contour, region and advanced contour options are activated, whether they are used alone or at the same time.

**To Reproduce**
1. Click on the drawing tool.
2. Draw any shape with long click.
3. Finish the form by releasing the click.
4. The error can be seen at the end of the line in the drawing.

**Expected behavior**
It is true that, depending on the modifications that the tool has had, certain variations to what is drawn are expected, such as smoothness. But you would expect the tangent and vertex handles to not get so tangled in the end.

**Screenshots**

https://user-images.githubusercontent.com/45057390/143924401-31c74db1-f985-489e-80ea-0587b5e0b253.mp4

**System information:**
 - OS: Arch Linux x64
 - Commit ID: 0ab9d69 

**Additional comments**
I hope the information is useful for everyone.
Thanks for the excellent work :)

### LINKED ISSUE #2460: Unwanted Vertex Points at the end of line, when using Draw tool
I am using Fedora 35, Synfig-Studio Flatpak version

https://user-images.githubusercontent.com/87817029/145769322-024a5487-443b-4f74-8567-0ede45476a29.mp4

How to Fix This ?

### PR DESCRIPTION
**Pull request by rodolforg**
fix #2448
fix #2460

### CODE REVIEW

**Comment by rodolforg** [comment]
@Gilraiser please test it

**Comment by Gilraiser** [comment]
Hello, cordial greetings to all. I am compiling commit 0720aac right now.

**Comment by Gilraiser** [comment]
Hi, I just tested commit 0720aac on archlinux, and the problem persists.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
Please backport to solve this issue pointed in forums: https://forums.synfig.org/t/odd-draw-tool-looping/13762/3

**Pull request merged**
