### PR TITLE
synfig-studio: remove some unused headers

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
and a NULL :P

**Comment by rodolforg** [comment]
Travis didn't run ? :P

**Comment by ice0** [comment]
@rodolforg yep, out of free minutes :(

**Comment by ice0** [comment]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Ok, looks like we need to migrate MacOS builds out of Travis.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
