### PR TITLE
revert: getenv is very slow on Windows, so I replaced most of the logging calls with a macro that is disabled by default.

### PR DESCRIPTION
**Pull request by ice0**
Reverts synfig/synfig#2826

Forgot to update the commit message.

Refs: e23b229

### CODE REVIEW

**Review by morevnaproject — DISMISSED** [review]

**Comment by ice0** [comment]
@rodolforg 
Git comment is important for automatic changelog generation.
So I want to revert commit with incorrect message and merge the correct one.
I was thinking about adding an empty commit with a new message, but that's bad for cherry picking.
Maybe you guys have a better idea.

**Comment by morevnaproject** [comment]
@rodolforg The commit message should start with "perf:" (or other tag, to help automatically generate changelog in the future)

**Comment by rodolforg** [comment]
I don't it is worth to add a revert commit and a new one just for a tag.
The history will have 3 commits and the bad one keeps existing.

As we have so few contributors we could do a forced push this time if that's important

**Comment by ice0** [comment]
Agree.

**Pull request closed without merging**
