### PR TITLE
Fixed issue with saving `loop` flag in some dynamic lists (Such as `average` and `weighted_average`)

### PR DESCRIPTION
**Pull request by rodolforg**
Such as 'average' and 'weighted_average'.

Every Dynamic List has loop parameter.

### CODE REVIEW

**Comment by rodolforg** [comment]
Maybe backport?

**Comment by rodolforg** [comment]
One difference here: it doesn't write `loop="false"` as current code does for some dynamic lists like `bline`. I chose to do it because `loop` is false by default.

**Comment by ice0** [comment]
> Maybe backport?

Agree.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
