### PR TITLE
Update Info.plist

### PR DESCRIPTION
**Pull request by DhairyaBahl**
Added CFBundleIdentifier. Fixed issue #1705 . KIndly guide me further if i have to improve it. 

Thanks :)

### CODE REVIEW

**Comment by AYESDIE** [comment]
Your changes are only in [ea45154](https://github.com/synfig/synfig/pull/1749/commits/ea451547227d3e7e036425e6594ab060a09313f9) but it has 2 other redundant merge. This needs to be addressed. Just rebase your changes on top of master.

**Comment by DhairyaBahl** [comment]
@AYESDIE I researched a lot on google how to rebase master on branches in origin but i didn't find any commands for that. So I am rebasing branches by the use of github desktop and it is showing this branch is up-to-date with master..

What should i do? Kindly help

Thanks :)

**Comment by ice0** [comment]
Looks ok, but two notes:
1) PRODUCT_BUNDLE_IDENTIFIER is used by XCode to set right identifier. Unfortunately we are currently not using XCode, so it's need to be set explicitly. I suggest to set it to `org.synfig.SynfigStudio`
2) Please update copyright year too (2008 -> 2020).

**Comment by DhairyaBahl** [comment]
@ice0 Okay I got it . There is 1 problem, when I will make these changes, github will increase my number of commits irrelevantly.
What should I do ??

Thanks :)

**Comment by DhairyaBahl** [comment]
@ice0 as it is already showing 3 commits under this PR. NExt time i will remember i don't have to reverse merge the PR rather than i have to rebase but how can I improve this problem in this PR ??

Kindly help Thanks :)

**Pull request closed without merging**
