### PR TITLE
[Synfig Studio] Replacing Gtk::HBox with Gtk::Box

### PR DESCRIPTION
**Pull request by FirasH**
Replaced the following deprecated stuff:
- `Gtk::HBox`

and some comments cleaning as well.

### CODE REVIEW

**Comment by rodolforg** [comment]
Hm… I don't think it always good to replace the `HBox` with `Grid`. `HBox` is deprecated, but `Box` is not, as they're still available in Gtk 4 / gtkmm4 :
https://developer.gnome.org/gtk4/stable/GtkBox.html
https://developer.gnome.org/gtkmm-tutorial/stable/sec-multi-item-containers.html.en#sec-boxes

`Grid` doesn't works the same as `Box` when programmer codes `Box` with `pack_start()` and `pack_end()`. AFAIK, `Grid` can't reproduce the `Box` behavior when both methods are used.

**Comment by FirasH** [comment]
In the current code `pack_start` and `pack_end` are used in case of checkbuttons to place them on the right edge of the `HBox`. To achieve the same visual result I had to expand the label on the left and the UI cannot be distinguished from the previous version.
So yes, you’re right the way `Box` and `Grid` work is not the same but I don’t think any user will suffer this change because, as I noted before, unless you read the code you can’t notice the difference.

I think that for this specific case there isn’t any practical difference as the layout is very simple but at least we avoid using stuff that is likely to be removed anyway in the near future or at least this is what’s suggested in Gtk documentation. I know we need to reference an older version of Gtk but if some changes can be done future proofing the code it’s even better IMHO, less work for the same piece of code.

**Comment by rodolforg** [comment]
I read somewhere else that they would be deprecated, but they were not. And I hope not: Grid is over complicated for simple single rows or columns layout, and don't provide that feature widgets on start and on end in the same way.
So… I don't see why don't simply replace H/VBox with Box only.

Anyway, not really important if you changed while keeping the same layout/resize behavior.

**Comment by FirasH** [comment]
mmm, let's see what other developers suggest...
For me both are equallly viable solutions 👍

**Comment by Keyikedalube** [comment]
> likely to be removed anyway in the near future or at least this is what’s suggested in Gtk documentation

I remember last year making a similar PR with `Gtk::Grid` as a replacement for `Gtk::H/VBox`. Because I thought the docs meant it too

> I read somewhere else that they would be deprecated, but they were not.

I've been digging where I read that too, couldn't find it, but found this post instead:
[Is GtkBox going to be deprecated?](https://discourse.gnome.org/t/is-gtkbox-going-to-be-deprecated/2332)

I agree with rodolforg's suggestion for `Gtk::Box` as a container for single row/column and `Gtk::Grid` for table-like container. But this PR is fine too. I can understand reading the code placing the first widget using `attach()` and the remaining widgets using `attach_next_to()`.

Not related to this PR but in Gtk 4 `Gtk::Toolbar` has been removed and Gtk community also suggest using `Gtk::Box` as a replacement. The user was trying to implement single row toolbar:
https://discourse.gnome.org/t/hope-gtktoolbar-back-to-gtk4/6201

**Comment by FirasH** [comment]
To me `Gtk::Box` feels more appropriate and less complicated for this specific purpose as @rodolforg suggested and chose `Gtk::Grid` just for the chances of having `Gtk::Box` replaced soon but doesn't appear to be the case.


Probably the best solution for now is using `Gtk::Box` and keep this decision consistent across Synfig Studio code.

**Comment by Keyikedalube** [comment]
Would you squash this? Git diff shows `Gtk::Box` replacing `Gtk::Grid` because of your initial commit. If you squash it the diff between old and new (your PR)  would appear correct.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
