### PR TITLE
build: Use vcpkg to build synfig

### PR DESCRIPTION
**Pull request by hesham-essam**
This relies on vcpkg's ports overlay feature which allows adding custom ports, and manifest mode feature which allows specifying dependency tree for one project similar to npm or cargo.
To build you do something like
```
> mkdir build
> cd build
> cmake -DCMAKE_TOOLCHAIN_FILE="<vcpkg directory>/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_OVERLAY_PORTS="../vcpkg-ports" -DCMAKE_BUILD_TYPE=Release -DVCPKG_INSTALLED_DIR="../../synfig_vcpkg_installed" ..
> cmake --build . -j <number-of-cores> --config Release
> .\output\Release\bin\synfigstudio.exe
```

Some notes:
1 - <del>  I had to use the cmake provided by visual studio for this to work. </del>
2 - Installation directory of vcpkg (VCPKG_INSTALLED_DIR) has to be outside the source tree, otherwise cmake complains.
3 - Debug mode fails to generate icons due to errors caught by the msvc's runtime checks.

### CODE REVIEW

**Comment by ice0** [comment]
```
C:\projects\test\synfig\build>cmake -DCMAKE_TOOLCHAIN_FILE="c:/projects/test/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_OVERLAY_PORTS="../vcpkg-ports" -DCMAKE_BUILD_TYPE=Release -DVCPKG_INSTALLED_DIR="../../synfig_vcpkg_installed" ..
-- Running vcpkg install
Error: Cannot resolve a minimum constraint for dependency libtool from synfig:x64-windows.
The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
See `vcpkg help versioning` for more information.
-- Running vcpkg install - failed
CMake Error at C:/projects/test/vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  C:\projects\test\synfig\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/CMakeDetermineSystem.cmake:104 (include)
  CMakeLists.txt:4 (project)
```

**Comment by hesham-essam** [comment]
@ice0 I wrote a port for libtool but forgot to check it out in git 😅 please try again

**Comment by ice0** [comment]
Now it builds fine, but on start it fails with error:
```
Fontconfig error: Cannot load default config file: No such file: (null)
```

**Comment by hesham-essam** [comment]
I also get the same error, but synfig opens all the same. Can you please send me the whole log?

**Comment by ice0** [comment]
```
(synfigstudio.exe:18908): GLib-GIO-WARNING **: 08:50:33.759: win32 session dbus binary not found: C:\projects\test\synfig\build\output\Release\bin\\gdbus.exe
synfig(18908) [8:50:34] info: Created directory "C:\Users\az/Synfig"
synfig(18908) [8:50:34] info: Starting Subsystem "Sound"
synfig(18908) [8:50:34] info: Starting Subsystem "Types"
synfig(18908) [8:50:34] info: Starting Subsystem "Rendering"
synfig(18908) [8:50:34] info: rendering threads 12
synfig(18908) [8:50:34] info: Starting Subsystem "Modules"
synfig(18908) [8:50:34] info: Starting Subsystem "Layers"
synfig(18908) [8:50:34] info: Starting Subsystem "Targets"
synfig(18908) [8:50:34] info: Starting Subsystem "Importers"
synfig(18908) [8:50:34] info: Starting Subsystem "Thread Pool"
synfig(18908) [8:50:34] info: Loading modules from C:\projects\test\synfig\build\output\Release/etc/synfig_modules.cfg
synfig(18908) [8:50:34] info: Loading lyr_freetype..
synfig(18908) [8:50:34] info: Attempting to register "lyr_freetype"
synfig(18908) [8:50:34] info: Found module "lyr_freetype"
synfig(18908) [8:50:34] info: Initializing FreeType...
synfig(18908) [8:50:34] info: Success for "lyr_freetype"
synfig(18908) [8:50:34] info: Loading lyr_std..
synfig(18908) [8:50:34] info: Attempting to register "lyr_std"
synfig(18908) [8:50:34] info: Found module "lyr_std"
synfig(18908) [8:50:34] info: Success for "lyr_std"
synfig(18908) [8:50:34] info: Loading mod_bmp..
synfig(18908) [8:50:34] info: Attempting to register "mod_bmp"
synfig(18908) [8:50:35] info: Found module "mod_bmp"
synfig(18908) [8:50:35] info: Success for "mod_bmp"
synfig(18908) [8:50:35] info: Loading mod_example..
synfig(18908) [8:50:35] info: Attempting to register "mod_example"
synfig(18908) [8:50:35] info: Found module "mod_example"
synfig(18908) [8:50:35] info: Success for "mod_example"
synfig(18908) [8:50:35] info: Loading mod_ffmpeg..
synfig(18908) [8:50:35] info: Attempting to register "mod_ffmpeg"
synfig(18908) [8:50:35] info: Found module "mod_ffmpeg"
synfig(18908) [8:50:35] info: Success for "mod_ffmpeg"
synfig(18908) [8:50:35] info: Loading mod_filter..
synfig(18908) [8:50:35] info: Attempting to register "mod_filter"
synfig(18908) [8:50:35] info: Found module "mod_filter"
synfig(18908) [8:50:35] info: Success for "mod_filter"
synfig(18908) [8:50:35] info: Loading mod_geometry..
synfig(18908) [8:50:35] info: Attempting to register "mod_geometry"
synfig(18908) [8:50:35] info: Found module "mod_geometry"
synfig(18908) [8:50:35] info: Success for "mod_geometry"
synfig(18908) [8:50:35] info: Loading mod_gif..
synfig(18908) [8:50:35] info: Attempting to register "mod_gif"
synfig(18908) [8:50:35] info: Found module "mod_gif"
synfig(18908) [8:50:35] info: Success for "mod_gif"
synfig(18908) [8:50:35] info: Loading mod_gradient..
synfig(18908) [8:50:35] info: Attempting to register "mod_gradient"
synfig(18908) [8:50:35] info: Found module "mod_gradient"
synfig(18908) [8:50:35] info: Success for "mod_gradient"
synfig(18908) [8:50:35] info: Loading mod_imagemagick..
synfig(18908) [8:50:35] info: Attempting to register "mod_imagemagick"
synfig(18908) [8:50:35] info: Found module "mod_imagemagick"
synfig(18908) [8:50:35] info: Success for "mod_imagemagick"
synfig(18908) [8:50:35] info: Loading mod_jpeg..
synfig(18908) [8:50:35] info: Attempting to register "mod_jpeg"
synfig(18908) [8:50:35] info: Found module "mod_jpeg"
synfig(18908) [8:50:35] info: Success for "mod_jpeg"
synfig(18908) [8:50:35] info: Loading mod_noise..
synfig(18908) [8:50:35] info: Attempting to register "mod_noise"
synfig(18908) [8:50:35] info: Found module "mod_noise"
synfig(18908) [8:50:35] info: Success for "mod_noise"
synfig(18908) [8:50:35] info: Loading mod_particle..
synfig(18908) [8:50:35] info: Attempting to register "mod_particle"
synfig(18908) [8:50:35] info: Found module "mod_particle"
synfig(18908) [8:50:35] info: Success for "mod_particle"
synfig(18908) [8:50:35] info: Loading mod_png..
synfig(18908) [8:50:35] info: Attempting to register "mod_png"
synfig(18908) [8:50:35] info: Found module "mod_png"
synfig(18908) [8:50:35] info: Success for "mod_png"
synfig(18908) [8:50:35] info: Loading mod_ppm..
synfig(18908) [8:50:35] info: Attempting to register "mod_ppm"
synfig(18908) [8:50:35] info: Found module "mod_ppm"
synfig(18908) [8:50:35] info: Success for "mod_ppm"
synfig(18908) [8:50:35] info: Loading mod_svg..
synfig(18908) [8:50:35] info: Attempting to register "mod_svg"
synfig(18908) [8:50:35] info: Found module "mod_svg"
synfig(18908) [8:50:35] info: Success for "mod_svg"
synfig(18908) [8:50:35] info: Loading mod_yuv420p..
synfig(18908) [8:50:35] info: Attempting to register "mod_yuv420p"
synfig(18908) [8:50:35] info: Found module "mod_yuv420p"
synfig(18908) [8:50:35] info: Success for "mod_yuv420p"
synfig(18908) [8:50:35] info: DONE
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_real"
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_bline_point"
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_matrix"
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_segment"
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_transformation"
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_vector"
synfig(18908) [8:50:35] warning: no icon for value type: "weighted_width_point"
synfig(18908) [8:50:35] warning: no icon for value type: "nil"
synfig(18908) [8:50:35] warning: no icon for value type: "matrix"
synfig(18908) [8:50:35] warning: no icon for value type: "bone_weight_pair"
synfig(18908) [8:50:35] warning: no icon for value type: "width_point"
synfig(18908) [8:50:35] warning: no icon for value type: "dash_item"
synfig(18908) [8:50:35] warning: no icon for value type: "bone_object"
synfig(18908) [8:50:35] warning: no icon for value type: "bone_valuenode"
synfig(18908) [8:50:35] warning: no icon for value type: "transformation"
synfig(18908) [8:50:35] warning: no icon for value type: "pair_bone_object_bone_object"
synfig(18908) [8:50:35] warning: no icon for value type: "pair_bone_object_bone_object"
synfig(18908) [8:50:35] warning: no icon for value type: "pair_bone_object_bone_object"
synfig(18908) [8:50:35] info: Loading Basic Settings...
synfig(18908) [8:50:35] info: Loading Plugins...
synfig(18908) [8:50:35] info: Loading plugins from C:/projects/test/synfig/build/output/Release/share/synfig/plugins
synfig(18908) [8:50:35] info:    Loading plugin: add-skeleton-simple
synfig(18908) [8:50:35] info:    Loading plugin: lottie-exporter
synfig(18908) [8:50:35] info:    Loading plugin: view-unhide-all-layers
synfig(18908) [8:50:35] info: Loading plugins from C:\Users\az/Synfig/plugins
synfig(18908) [8:50:35] warning: Can't read plugin directory: Error opening directory "C:\Users\az/Synfig/plugins": No such file or directory
synfig(18908) [8:50:35] info: Init UI Manager...
synfig(18908) [8:50:35] info: Init Dock Manager...
synfig(18908) [8:50:35] info: Init State Manager...
synfig(18908) [8:50:35] info: Init Main Window...
synfig(18908) [8:50:35] info: Init Toolbox...
synfig(18908) [8:50:35] info: Init About Dialog...
synfig(18908) [8:50:35] info: Init Tool Options...
synfig(18908) [8:50:35] info: Init History...
synfig(18908) [8:50:35] info: Init Canvases...
synfig(18908) [8:50:35] info: Init Keyframes...
synfig(18908) [8:50:35] info: Init Layers...
synfig(18908) [8:50:35] info: Init Parameters...
synfig(18908) [8:50:35] info: Init MetaData...
synfig(18908) [8:50:35] info: Init Library...
synfig(18908) [8:50:35] info: Init Info...
synfig(18908) [8:50:35] info: Init Navigator...
synfig(18908) [8:50:35] info: Init SoundWave...
synfig(18908) [8:50:35] info: Init Timetrack (old)...
synfig(18908) [8:50:35] info: Init Timetrack...
synfig(18908) [8:50:35] info: Init Curve Editor...
synfig(18908) [8:50:35] info: Init Layer Sets...
synfig(18908) [8:50:35] info: Init Color Dialog...
synfig(18908) [8:50:35] info: Init Gradient Dialog...
synfig(18908) [8:50:35] info: Init DeviceTracker...
synfig(18908) [8:50:35] info: Init ModPalette...
synfig(18908) [8:50:35] info: Init Setup Dialog...
synfig(18908) [8:50:36] info: Init Input Dialog...
synfig(18908) [8:50:36] info: Loading Custom Workspace List...
synfig(18908) [8:50:36] info: Init auto recovery...
synfig(18908) [8:50:36] info: Loading Settings...
synfig(18908) [8:50:36] info: Init Tools...
synfig(18908) [8:50:36] info: Checking auto-recover...
synfig(18908) [8:50:36] info: Done.
Fontconfig error: Cannot load default config file: No such file: (null)
```

**Comment by hesham-essam** [comment]
No, I ran it from powershell. I will investigate in a clean environment.

**Comment by ice0** [comment]
> No, I ran it from powershell. I will investigate in a clean environment.

Hmmm, from PowerShell it also runs fine. Please check from command-line.

**Comment by hesham-essam** [comment]
@ice0 Did you use the cmake that ships with visual studio? Can you also please send me the CMakeCache, it might be the case that it chose a library other than the one provided by vcpkg.

**Comment by hesham-essam** [comment]
I locally built synfig using the vanilla command line with visual studio's cmake, and it ran.

**Comment by ice0** [comment]
> Did you use the cmake that ships with visual studio?

```
C:\projects\test\synfig\build-debug2>where cmake
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
```

I think yes.

> Can you also please send me the CMakeCache, it might be the case that it chose a library other than the one provided by vcpkg.

Sure.
[CMakeCache.zip](https://github.com/synfig/synfig/files/9050151/CMakeCache.zip)

P.S.
I found the difference between VS and command-line build. VS builds `Debug` configuration by default.
If I use `cmake --build . -j 8 --config Debug -- /p:CL_MPcount=8` when it also runs fine.
What is the size of `synfigstudio.exe` in your case? I have 14M for Debug and 3.6M for Release.

**Comment by hesham-essam** [comment]
locally cmake finds the pkgconfig provided by vcpkg
```
//pkg-config executable
PKG_CONFIG_EXECUTABLE:FILEPATH=E:/Programming/very/long/path/to/test/gtk3/x64-windows/tools/pkgconf/pkgconf.exe
```
I'm using latest cmake from [`https://cmake.org/`](https://cmake.org/)
I'm guessing that older versions of cmake don't operate well with `pkgconf`, and maybe  they need `pkg-config`. I will test and get back to you.

**Comment by hesham-essam** [comment]
> On my local machine it builds fine

Does it also run?

**Comment by hesham-essam** [comment]
> Yes. Removed it (for testing purposes) and CMake configure is also stops now.

CMake configure doesn't work you mean? What is the error message?

**Comment by hesham-essam** [comment]
> Ok, just need to put updated FindPkgConfig.cmake to synfig.git/cmake folder.
I would actually prefer encouraging users to use a newer version of cmake instead since this will prevent updates to FindPkgConfig from cmake's side.

But apart from this, just to make sure:
1. Did imagemagick build successfully?
2. Did synfig build and run without problems as opposed to before?

**Comment by ice0** [comment]
> I tried putting synfig inside a path that has arabic and/or russian characters and it didn't work. Neither this build, nor the official build from the website. Does your build path have non English characters?

No. My path is `c:\projects\vcpkg-test`.
Which version

> I would actually prefer encouraging users to use a newer version of cmake instead since this will prevent updates to FindPkgConfig from cmake's side.

It can be solved in this way:
```
if(MSVC AND CMAKE_VERSION VERSION_LESS 3.20.3)
    include(SynfigFindPkgConfig)
else()
    include(FindPkgConfig)
endif()
```
In that case we doesn't require from user to install additional CMake but unfortunately I can't find what changes Microsoft is adding to their CMake (probably none) so I don't know yet which solution is better.

**Comment by hesham-essam** [comment]
This should be fixed now

**Comment by hesham-essam** [comment]
I have a couple of days off, I would like to solve the issue you're facing. I'm unable to reproduce it locally, I tried changing the language of the system, but stuff still worked. Did you find what causes it or how can I reproduce it?

**Comment by ice0** [comment]
> I have a couple of days off, I would like to solve the issue you're facing. I'm unable to reproduce it locally, I tried changing the language of the system, but stuff still worked. Did you find what causes it or how can I reproduce it?

I'm doing a clean build right now.
Which version of VS are you using?

1. Building VS 2019 + Windows Server 2016 fails:
```
[17/885] "C:/projects/vcpkg-vs2019/synfig_vcpkg_installed/x64-windows/tools/glib/glib-compile-resources.exe" "gtk/gtk.gresources.xml" "--sourcedir" "./gtk" "--sourcedir" "C:/projects/vcpkg-vs2019/vcpkg/buildtrees/gtk3/src/3.24.34-35fefc5b4d.clean/gtk" "--sourcedir" "../src/3.24.34-35fefc5b4d.clean/gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.h" "--manual-register"
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
[18/885] "C:/projects/vcpkg-vs2019/synfig_vcpkg_installed/x64-windows/tools/glib/glib-compile-resources.exe" "gtk/gtk.gresources.xml" "--sourcedir" "./gtk" "--sourcedir" "C:/projects/vcpkg-vs2019/vcpkg/buildtrees/gtk3/src/3.24.34-35fefc5b4d.clean/gtk" "--sourcedir" "../src/3.24.34-35fefc5b4d.clean/gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.c" "--manual-register" "--dependency-file" "gtk/gtkresources.c.d"
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
ninja: build stopped: subcommand failed.
```
Full log: [package-x64-windows-rel-out.zip](https://github.com/synfig/synfig/files/9155825/package-x64-windows-rel-out.zip)


2. VS 2019 + Windows 10:
```
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```

I noticed that when running the build, it already installs CMake 3.22.2.
Can we use it?
In this case, we do not require the user to download and install CMake manually.

install

3. VS 2022 + Windows 10:
- Still building. Update status later

**Comment by ice0** [comment]
> Did you find what causes it or how can I reproduce it?

Yes, I find the issue: https://github.com/synfig/synfig/issues/2759

**Comment by hesham-essam** [comment]
Thanks for your quick feedback!

>  Which version of VS are you using?

I have VS 2022.

>  Building VS 2019 + Windows Server 2016 fails:

Currently downloading Windows Server 2016 (English version), and I will put it on a virtualbox and try to reproduce and fix the error.

> VS 2019 + Windows 10:

Yeah, I just forgot to do the fix you suggested.

> I noticed that when running the build, it already installs CMake 3.22.2.
> Can we use it?

I will check if there is a seamless way to do that. At first glance it's not as straightforward as I'd like it to be, since there's no port for cmake in vcpkg, it seems that it checks the version of cmake and installs a newer one internally.  For example, vcpkg did not install cmake on my machine (there is no cmake.exe in vcpkg folder or in its downloads folder).

> VS 2022 + Windows 10:
> Builds fine but won't run. Fortunately, I can see the place where it stops. (https://github.com/synfig/synfig/issues/2759)

I'm currently rebuilding dependencies (the really boring part about this project, rebuilding stuff a lot), will get back to you on this once it's done.

> Some warnings at start:

First one is missing icons, and second one is missing gdk-pixbuf loaders. Will fix first one by adjusting the port for gtk3 to download the icons, and the second one by making our cmake scripts copy the necessary gdk-pixbuf dependent files to bin directory.

**Comment by ice0** [comment]
> Currently downloading Windows Server 2016 (English version), and I will put it on a virtualbox and try to reproduce and fix the error.

I'm not sure, but maybe this error has something to do with the old version of CMake. 
I will install the new version from the CMake site and see if that helps.

> > VS 2019 + Windows 10:
> 
> Yeah, I just forgot to do the fix you suggested.

I prefer your solution.
If we can't use the pre-installed CMake, then it is better to ask the user to install the required version.

> 
> > I noticed that when running the build, it already installs CMake 3.22.2.
> > Can we use it?
> 
> I will check if there is a seamless way to do that. At first glance it's not as straightforward as I'd like it to be, since there's no port for cmake in vcpkg, it seems that it checks the version of cmake and installs a newer one internally. For example, vcpkg did not install cmake on my machine (there is no cmake.exe in vcpkg folder or in its downloads folder).

I'm thinking maybe you just need to add it as a build dependency to `vcpkg.json`?

**Comment by hesham-essam** [comment]
> I'm thinking maybe you just need to add it as a build dependency to vcpkg.json?

Does not work. They have no public port for cmake. I think they just internally download a newer cmake and run the build scripts using the newer cmake if an older one is invoked.
https://github.com/microsoft/vcpkg/blob/b2a22ff59ab523788a26980f7d38a4e5d4fedb8f/scripts/vcpkgTools.xml#L17-L23

**Comment by ice0** [comment]
> Does not work. They have no public port for cmake. I think they just internally download a newer cmake and run the build scripts using the newer cmake if an older one is invoked. https://github.com/microsoft/vcpkg/blob/b2a22ff59ab523788a26980f7d38a4e5d4fedb8f/scripts/vcpkgTools.xml#L17-L23

Got it.
In this case, you can check the minimum required version of CMake that has this commit (https://github.com/Kitware/CMake/commit/94a84dc0af227e574e2a9950cf2c830e2f57218f)?

**Comment by hesham-essam** [comment]
Rebased, pacakged adwaita and hicolor icon theme + added librsvg pixbuf loader.

I reimplemented librsvg port since the one provided by vcpkg doesn't export pkgconfig target/file, and it doesn't place `pixbufloader-svg.dll` to its correct location. I had to reimplement libcorco port in the process.

I also added a port for gdk-pixbuf since the one provided by vcpkg reports incorrect loaders directory in its pkgconfig file.

Now locally I only get these warnings:
```
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_real"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_bline_point"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_matrix"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_segment"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_transformation"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_vector"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "weighted_width_point"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "nil"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "matrix"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "bone_weight_pair"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "width_point"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "dash_item"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "bone_object"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "bone_valuenode"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "transformation"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "pair_bone_object_bone_object"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "pair_bone_object_bone_object"
synfig(6644) [8:43:59 PM] warning: no icon for value type: "pair_bone_object_bone_object"
```
which I don't think have to do with this PR.

**Comment by hesham-essam** [comment]
I added an OpenEXR port (the major reason for not using the default port is that it doesn't install the pkgconfig files).

And I tried porting MLT, but I hit a dead end. MLT uses a lot of linux and gcc specific stuff (headers such as sys/time, __attribute__ clauses, etc.), and they don't support building with msvc. See https://github.com/mltframework/mlt/issues/241

**Comment by ice0** [comment]
> And I tried porting MLT, but I hit a dead end. MLT uses a lot of linux and gcc specific stuff (headers such as sys/time, gcc __attribute__ clauses, etc.), and they don't support building with msvc. See [mltframework/mlt#241](https://github.com/mltframework/mlt/issues/241)

Is it possible to build MLT using MSVC/clang toolchain?

**Comment by hesham-essam** [comment]
Using clang would solve the gcc specific stuff, but the POSIX/linux headers issue will still remain.

**Comment by hesham-essam** [comment]
Now locally synfig builds fine within Visual Studio 2017 using its embedded cmake.

**Comment by hesham-essam** [comment]
I think this PR is in an OK state right now. I will be focusing on the conan PR in the following days.

**Comment by ice0** [comment]
```
brotlicommon.dll
brotlidec.dll
bz2.dll
cairo-2.dll
fftw3.dll
fontconfig-1.dll
freetype.dll
fribidi-0.dll
gio-2.0-0.dll
glib-2.0-0.dll
glibmm-2.4-1.dll
gmodule-2.0-0.dll
gobject-2.0-0.dll
harfbuzz.dll
iconv-2.dll
intl-8.dll
jpeg62.dll
libexpat.dll
libffi.dll
liblzma.dll
libpng16.dll
libxml2.dll
pango-1.0-0.dll
pangocairo-1.0-0.dll
pangoft2-1.0-0.dll
pangowin32-1.0-0.dll
pcre.dll
sigc-2.0-0.dll
tiff.dll
xml++-2.6-2.dll
zlib1.dll
```

These libraries are located in both the bin and lib\synfig\modules folders.
Is it possible to not duplicate them?

**Comment by hesham-essam** [comment]
I suppose I can write a custom target for cleaning up duplicate dlls.

**Comment by ice0** [comment]
> I suppose I can write a custom target for cleaning up duplicate dlls.

I suggest to do this on install/pack step.

What can be improved here:
1) Install step doesn't install some necessary dlls;
2) `synfig-studio/src/gui/CMakeLists.txt`
> TODO: separate this to a separate file maybe?

I think yes, better to move this code to `cmake/SynfigVcpkg.cmake`?
3) Maybe also move `vcpkg-ports` to `autobuild` folder? All build stuff is located here.

P.S. If you're busy right now, I suggest to rebase this PR and merge it as is, and do fixes in the new PR later.

**Comment by hesham-essam** [comment]
Rebased

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
