### PR TITLE
Fix crash when switching workspaces

### LINKED ISSUE #2584: Switching workspace crashes Synfig
**Describe the bug**
Can no longer switch between workspaces: Animating, Compositing, Default, and/or user custom ones.
 The program just crashes.

**To Reproduce**
1. Go to 'Window > Workspace'
2. Click on 'Compositing'
3. Crash

**Expected behavior**
Workspace switches from Default to Compositing successfully.

**Screenshots**
Screenshot from 2022-03-20 14-12-37

**System information:**
 - OS: Fedora
 - OS version: 35
 - Commit ID: f64f99f020f0689fb006969a7c649c101c52d066

**Additional comments**
Crash reproducible both on Debug and Release build.
I got this console output at the end:
```
Application appears to have terminated successfully
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by hesham-essam**
Fixes #2584. Hiding a window causes it to be removed from Gtk::Application. When all windows are removed, the main event loop stops.

### CODE REVIEW

**Comment by rodolforg** [comment]
Yes, this was the source of the problem when we switched to Gtk::Application :)

**Comment by ice0** [comment]
Hi!
A little explanation about this hack (with hiding the window). 

https://github.com/synfig/synfig/blob/042c7378917c32af4354bac5d35283a63a7b828c/synfig-studio/src/gui/docks/dockmanager.cpp#L582-L584

The initial problem is that if you close the minimized Synfig window, it would open offscreen at startup and not be visible. (https://github.com/synfig/synfig/issues/1871)
Probably this is only a Windows OS issue just in case.

Rodolfo fixed this problem, but another issue appeared: on a multi-monitor configuration, the window opened a little higher than it should be, and the minimize/maximize buttons were out of view. 
https://github.com/synfig/synfig/pull/1973
https://github.com/synfig/synfig/issues/1975


I noticed that this happens if the window is at coordinates (0, 0). (In fact, this is not entirely true, more on that later). But if you hide the window and move it to (0, 0) and then show it, then its position is correct and it opens where it should, in the top left corner.

This was done out of a misunderstanding of what was really going on. 

The fact is that on a multi-monitor configuration, the monitors form a virtual rectangle that combines them into one large display. However, if the monitors are not the same geometry (as in my case), then the top left corner of one of the monitors will not be at the (0, 0) coordinates.
In my case, this is (0, 173) pixels, and this is exactly the information we can get using the `display->get_monitor(i)->get_geometry(rect)` method. 
This is done here:
https://github.com/synfig/synfig/blob/042c7378917c32af4354bac5d35283a63a7b828c/synfig-studio/src/gui/docks/dockmanager.cpp#L429

I.e. the solution is quite simple, we need to move the window not to (0, 0) but to the top left corner of the monitor on which window is located. The code that hides the window then becomes unnecessary and everything will work correctly.

So I can merge the current PR as is and fix the hack in another PR (this will remove all current changes and hack) or maybe you want to continue working in this PR?

**Comment by hesham-essam** [comment]
I will fix the hack

**Comment by hesham-essam** [comment]
I don't have multiple monitors to test this, but this should ensure that the top left point is visible.

**Comment by ice0** [comment]
Looks good to me.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
