### PR TITLE
Remove references to absent UI translation files

### PR DESCRIPTION
**Pull request by morevnaproject**

### CODE REVIEW

**Comment by ice0** [comment]
That's strange. @rodolforg is already add them here: https://github.com/synfig/synfig/pull/1202

**Comment by ice0** [comment]
@morevnaproject oh, i see. They already added to the end. So you can just remove that lines.

**Comment by morevnaproject** [comment]
Ah, you right! ^__^

**Comment by morevnaproject** [comment]
Done.

**Comment by rodolforg** [comment]
Whoops. My bad

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
