### PR TITLE
[Lottie Exporter] Add support for Sine convert method

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Added sine convert method for Lottie Exporter plugin.
@AnishGG , @ice0 , please review :smiley: .

### CODE REVIEW

**Comment by AnishGG** [comment]
Works like a charm. :smile:

**Comment by saurabh-ramola** [comment]
@ice0  Does this need any changes? ^_^

**Comment by saurabh-ramola** [comment]
The sine convert method wasn't working properly for simple circle. Now it has been fixed.
@AnishGG , @ice0 Please review.

**Comment by ice0** [comment]
@saurabh-ramola please squash and rebase.

**Comment by saurabh-ramola** [comment]
@ice0 Done :smiley:

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
