### PR TITLE
feat: add handles to Bevel layer parameters

### LINKED ISSUE #3042: Feature request: Gui handles for Bevel layer
Gui handles for the following 3 parameters of Bevel layer will improve usability of the layer.
1.  Light angle (represented by angle handle in the gui)
2. Depth of Bevel (represented by circle handle in gui)
3. Softness ( represented by circle handle in gui)
(kind of like the star region handles)
image
image

### PR DESCRIPTION
**Pull request by rodolforg**
fix #3042

### CODE REVIEW

**Comment by yoSachinkr** [comment]
@rodolforg in the appvayor build, while using bones, i found that the width handle for bones are not showing even though the width handle toggle is on!
image

**Comment by rodolforg** [comment]
If it is a Skeleton Layer, width is not useful. Or is it?

If it is a Skeleton deformation layer, you should be able to change width in "rest" mode (disable layer)

**Comment by yoSachinkr** [comment]
> If it is a Skeleton Layer, width is not useful. Or is it?

Width is useful specially while linking all the vertices of a region as the width of the bones determines the influence region of the bones.

**Comment by rodolforg** [comment]
@yoSachinkr got it.

I'll restore it. Sadly it pollutes the workspace :( Maybe we should elaborate a way (maybe a tool?) for linking skeleton bones to spline vertices / group transforms... Any idea / proposal?

**Comment by morevnaproject** [comment]
Looks cool! Thank you!

**Comment by yoSachinkr** [comment]
> @yoSachinkr got it.
> 
> I'll restore it. Sadly it pollutes the workspace :( Maybe we should elaborate a way (maybe a tool?) for linking skeleton bones to spline vertices / group transforms... Any idea / proposal?

@rodolforg One possible solution:
1. Keeping the **width handle toggle** on by default when using bones tool.
2.  And showing the width handles for only the selected bone while the rest remain hidden. 

https://github.com/synfig/synfig/assets/50204208/faea076a-788d-4ced-8126-8f328cbed7c1

**Pull request merged**
