### PR TITLE
Fix crash when moving origin point of child bone in Skeleton Deformation Layer using Bone Tool

### PR DESCRIPTION
**Pull request by rodolforg**
when moving a child bone with Bones tool

### CODE REVIEW

**Comment by rodolforg** [comment]
[As I said here](https://github.com/synfig/synfig/pull/1698/files#r582108422), I still don't know what this code is for.
The commit  9664b8c8273d36335bb3ed2d7c6c01cc9d0a9a96 that inserted this code is from PR #1698, that fix issue #1658, but the commit description and code comment are not related to the PR or to this issue the PR deals.

**Comment by rodolforg** [comment]
(the forced push was to fix the exception class: from `String` to `Error`).

**Comment by morevnaproject** [comment]
> [As I said here](https://github.com/synfig/synfig/pull/1698/files#r582108422), I still don't know what this code is for.

Hi! This code is fixing this issue - https://github.com/synfig/synfig/issues/1627
Without this code we will have wrong behavior, which is demonstrated in this video - https://www.youtube.com/watch?v=dzTPdNbqS3U&feature=youtu.be ^__^

**Comment by rodolforg** [comment]
> Hi! This code is fixing this issue - #1627

Thank you for pointing the correct issue! :D How can I create the second bone? I can only create child bones :(
Actually, I don't know how deformation layer works (what are those bone pairs?)

**Comment by ice0** [comment]
@rodolforg, are there any more changes planned? Temporarily switched this PR to "Draft"

**Comment by rodolforg** [comment]
@ice0 no because I don't understand further than I did lol

**Comment by morevnaproject** [comment]
> How can I create the second bone? I can only create child bones :(
> Actually, I don't know how deformation layer works (what are those bone pairs?)

Hi! Here I have recorded an explanation video on how Skeleton Deformation works - https://youtu.be/T1SgaJg44ns
(I hope my explanation is okay ^__^")

**Comment by rodolforg** [comment]
>  (I hope my explanation is okay ^__^")

It was great! It's a totally different approach of "regular" skeleton that I didn't realize what was the pair stuff :) Thank you and sorry for my ignorance here

**Comment by morevnaproject** [comment]
Thank you for help! Please ask again if you need any more clarifications - I'll try to be here as possible. ^__^

**Comment by rodolforg** [comment]
@morevnaproject  by the way, congrats for your NGO accomplishment (I just saw your presentation! ;) )!

**Comment by morevnaproject** [comment]
Thank you! It took some efforts and time. Tomorrow will go to receive all official documents on hands. Let's keep rockin'! :tada:

**Comment by rodolforg** [comment]
If something is left to do in this code slice (not bug fix) is line 206:
```c++
ValueNode_Composite::Handle comp = ValueNode_Composite::Handle::cast_dynamic(value_desc.get_parent_desc().get_parent_desc().get_value_node());
```

That isn't the way to check if it a Skeleton Deformation bone list parameter :/

**Review by morevnaproject — APPROVED** [review]

**Pull request merged**
