### PR TITLE
Adding FontConfig Support in FontFamily Widget

### PR DESCRIPTION
**Pull request by DhairyaBahl**
@ice0 @rodolforg 

This will solve the issue #1766 

I've added fontconfig support in the FontFamily widget by editing its cmake files . 

Kindly review it and guide me further if i have to make some changes.

Thanks :)

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by DhairyaBahl** [comment]
@Keyikedalube @ice0 
Can you guys tell me what is the best way to understand the codebase of synfig. How should I approach it ? What should I study first ?? coz now I think I have a little Knowledge of how the cmakelist works how widget works and same for few other parts of the code !! but how can I Move forward ? 

I feel like you guys are spoonfeeding me and I am a noob or something ! I want to put effort on my side, kindly tell me how should I move forward ?

Thanks :+1:

**Comment by Keyikedalube** [comment]
@DhairyaBahl You are doing alright :) Keep learning and you'll cover more grounds (synfig codebase)

BTW, congrats on your another successful PR!

**Comment by DhairyaBahl** [comment]
@Keyikedalube Yes I am learning bit by bit :) It was just about feeling lil bit inferior. No issues, I think it will go over time ;) Thanks

**Comment by rodolforg** [comment]
You can read some dev info here, if you didn't yet. Maybe it helps you :)
https://synfig-docs-dev.readthedocs.io

**Comment by DhairyaBahl** [comment]
@rodolforg I read it but not for the sake of knowledge but just to refer to that when I am stuck in problem. I will also read it to learn also. Thanks for the tip :)

**Comment by ice0** [comment]
@DhairyaBahl Unfortunately there is no step-by-step guide (AFAIK).
So currently we trying to collect all available information in one place (https://synfig-docs-dev.readthedocs.io/).
After that it can be structured and serve as a basis for guide.

Also you can look here: https://wiki.synfig.org/Developer_Documentation

P.S.  I have added [issue ](https://github.com/synfig/synfig/issues/1800) for the following questions. This way we can use them to figure out which parts should be documented first.

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by DhairyaBahl** [comment]
@ice0 

Okay.. I understand. So for the time being I should keep contributing to the issues which helped me earlier and will keep helping me to understand a new thing in the codebase and even I came to know anything that must be mentioned in the documentation then I will make a PR in that issue also. 

Thanks :+1:

**Pull request merged**
