### PR TITLE
Trying to fix skeleton copy

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
fixed LGTM reports

**Comment by rodolforg** [comment]
It seems to work with: 
[bone-dup-test.zip](https://github.com/synfig/synfig/files/4671201/bone-dup-test.zip)
But now I noticed that it doesn't work with Gilraiser example https://github.com/synfig/synfig/issues/1393#issuecomment-632256581

**Comment by rodolforg** [comment]
Now it just duplicates the skeleton itself, don't try to link anything to its bones.
What do you think, @morevnaproject @ice0 ?

**Comment by morevnaproject** [comment]
@rodolforg Thank you so much for taking on this issue! I am reviewing it now. ^__^

**Comment by morevnaproject** [comment]
> Now it just duplicates the skeleton itself, don't try to link anything to its bones.
> What do you think, @morevnaproject @ice0 ?

I see. If we duplicate a group (which contains character parts and its skeleton), then we will get a copy of this character, but his parts are not linked to skeleton.

Of course, I would prefer to have a copy which preserves links.

But, of course the behavior introduced by this PR is **much** better than situation without this PR (I mean duplicated bones and corrupted files).

**Comment by morevnaproject** [comment]
I think if we merge this PR at its current state to stable version of Synfig (1.3.x), then we will avoid **a lot** of bug reports after release.

**Comment by rodolforg** [comment]
@morevnaproject I removed draft status then.

> Of course, I would prefer to have a copy which preserves links.

The problem is that we don't know if the linked layers are or not cloned too.
Unless we make an exception in layer duplicate action to investigate this everytime a skeleton layer is to be duplicated.

**Pull request merged**
