### PR TITLE
Some svg parser code cleaning

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by ice0** [comment]
@rodolforg can you fix alert and rebase, please?

**Comment by rodolforg** [comment]
Ouch
I unintentionally rebased and pushed other commits too :(

There's a looot of memory leaks...

**Comment by rodolforg** [comment]
@ice0 I'll redo this PR

**Comment by rodolforg** [comment]
Superseded by myself #2137

**Pull request closed without merging**
