### PR TITLE
[Core] remove reminiscent Cairo (and Pango) stuff

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
It misses cleaning CMakeLists.txt .
But I still don't know CMake :(

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
@Keyikedalube  @ice0 @AYESDIE , you guys do know CMake. Could you check for this zombie Cairo and Pango stuff in synfig-core folder in CMake building system files?

**Comment by Keyikedalube** [comment]
@rodolforg I'm afraid I can't help much here. I don't know/hack around synfig-core stuff just the GUI frontend because that's where I feel more confident in.

**Comment by rodolforg** [comment]
ice0 removed all Cairo and Pango stuff of synfig-core. These libraries aren't used anymore in it.

However, there still some references to it like here: https://github.com/synfig/synfig/blob/master/synfig-core/src/CMakeLists.txt#L62-L67

**Comment by rodolforg** [comment]
There are some references to Gdk and Gtk too, and synfig-core doesn't use it :(
https://github.com/synfig/synfig/blob/eafeda4828fea262646abba906b6650fb16591f4/synfig-core/src/CMakeLists.txt#L82-L83

**Comment by AYESDIE** [comment]
A few more references that needs to be addressed

https://github.com/synfig/synfig/blob/eafeda4828fea262646abba906b6650fb16591f4/synfig-core/src/modules/lyr_freetype/CMakeLists.txt#L6-L8

**Comment by ice0** [comment]
@rodolforg I will do this.

**Pull request merged**
