### PR TITLE
[Lottie Exporter] Add support for Logarithm convert method

### PR DESCRIPTION
**Pull request by saurabh-ramola**
Added support for Logarithm convert method.
@AnishGG , please review ^__^

### CODE REVIEW

**Comment by ice0** [comment]
Whoops, conflicts after merging previous PR. Can you check and rebase?

**Comment by saurabh-ramola** [comment]
> Whoops, conflicts after merging previous PR. Can you check and rebase?

Done :smiley:

**Comment by saurabh-ramola** [comment]
Oops, deleted some lines accidentally, have reversed it in the last commit.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
