### PR TITLE
Fix text layer family search and allow user selection

### PR DESCRIPTION
**Pull request by rodolforg**
If FontConfig is available.

### CODE REVIEW

**Comment by rodolforg** [comment]
As usual, I have no idea on OSX

**Comment by rodolforg** [comment]
@morevnaproject  :)

**Comment by morevnaproject** [comment]
@rodolforg  Cool! I am taking this for test! ^__^

**Comment by morevnaproject** [comment]
I tested it on Linux and it works great! @rodolforg you couldn't imagine how I missed that feature! ^__^

screenshot_001

Can someone test this PR on Windows? ^__^ @Svarov-RZM @ice0

**Comment by morevnaproject** [comment]
I have made attempt to test it on OSX 10.9. The build completed successfully, but I wasn't able to run Synfig - it segfaults when checking for autorecover. This is most probably not related to this PR. I will investigate further and report an issue...

**Comment by morevnaproject** [comment]
Hmmm.. I tried to build latest commit from master branch (4f1e92f74cb2) on the same system and it doesn't crash.
So, it looks like the crash on OSX happens because of this PR.

I am attaching debugging info here.

```
Konstantin2s-iMac:~ admin$ /Users/admin/sources/synfig/_production/SynfigStudio.app/Contents/MacOS/SynfigStudio

   synfig studio -- starting up application...

synfig(96158) [08:48:28] info: Starting Subsystem "Sound"
synfig(96158) [08:48:28] info: Starting Subsystem "Types"
synfig(96158) [08:48:28] info: Starting Subsystem "Rendering"
synfig(96158) [08:48:28] info: rendering threads 4
synfig(96158) [08:48:28] info: Starting Subsystem "Modules"
...
synfig(96158) [08:48:29] info: Loading Custom Workspace List...
synfig(96158) [08:48:29] info: Init auto recovery...
synfig(96158) [08:48:29] info: Loading Settings...
synfig(96158) [08:48:29] info: Init Tools...
synfig(96158) [08:48:29] info: Checking auto-recover...
synfigstudio(96158,0x7fff7b39e310) malloc: *** error for object 0x7fd295eb4538: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

And this - https://gist.github.com/morevnaproject/3be83631fac596bb2fa444ac1abe2b12

**Comment by rodolforg** [comment]
Are you able to build a debug version?

**Comment by morevnaproject** [comment]
Yes, I can build debug version. Also, I need to check if I have fontconfig package installed... ^__^

**Comment by rodolforg** [comment]
It shouldn't crash if you don't have it installed ;)

**Comment by ice0** [comment]
Tested on Windows 2016 - works great!

**Comment by ice0** [comment]
Tested on MacOS 10.14 (Mojave).

It aborts on different places, but the real problem is here:
```
const std::vector<std::string>& families = FamilyFontConfigWrap::get();
for (const std::string &family : families) {
	Gtk::TreeModel::Row row = *(enum_TreeModel->append());
	row[enum_model.value] = family;
}
```

if I change this to:
```
const std::vector<std::string> families;
```
it stops to fail, but if I call:
```
FamilyFontConfigWrap::get();

const std::vector<std::string> families;
```
then it aborts again.

**Comment by ice0** [comment]
Looks like the problem is here:
```
FcPatternDestroy(font);
```
When I comment out this string - all works fine.


```
std::sort( families.begin(), families.end() );
families.erase( std::unique( families.begin(), families.end() ), families.end() );
```

Maybe then it is better to use `std::set`?

**Comment by rodolforg** [comment]
> Maybe then it is better to use `std::set`?

I think I did that way somehow related to performance... But it was probably when I was reading the files myself instead of using fontconfig.

> When I comment out this string - all works fine.

Done ;) Thank you

**Comment by morevnaproject** [comment]
I am taking this for test...

**Comment by morevnaproject** [comment]
Now it works on OSX 10.9! No crash. ^__^

**Comment by morevnaproject** [comment]
screenshot_004

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
