### PR TITLE
[Lottie Exporter] Add support for Vector Angle convert method

### PR DESCRIPTION
**Pull request by saurabh-ramola**
@AnishGG I have separated the Vector Angle convert method from the aTan2 convert method PR.
Please review it.

### CODE REVIEW

**Comment by AnishGG** [comment]
I suggest to add [Lottie Exporter] in the P.R. heading, for better understandibility. ^__^

**Comment by AnishGG** [comment]
@saurabh-ramola could you rebase this with master branch. ^__^

**Comment by saurabh-ramola** [comment]
> @saurabh-ramola could you rebase this with master branch. ^__^

Done ^_^

**Comment by AnishGG** [comment]
@saurabh-ramola for some reason, I don't see: https://github.com/synfig/synfig/blob/master/synfig-studio/plugins/lottie-exporter/common/Param.py#L530-L531 these lines in this PR and that is why we got LGTM alert.
Is it because of some rebasing fault?

**Comment by AnishGG** [comment]
> @saurabh-ramola for some reason, I don't see: https://github.com/synfig/synfig/blob/master/synfig-studio/plugins/lottie-exporter/common/Param.py#L530-L531 these lines in this PR and that is why we got LGTM alert.
> Is it because of some rebasing fault?

Actually, you missed these 2 lines in this new P.R.
Do have a look at it. ^__^

**Comment by saurabh-ramola** [comment]
> Actually, you missed these 2 lines in this new P.R.
> Do have a look at it. ^__^

My bad, I have fixed it now. :D

**Comment by saurabh-ramola** [comment]
@AnishGG there were some files that needed to be put into makefiles, I have added them now. There's also a slight change in the vector angle method expression. Please review it ^__^

**Comment by AnishGG** [comment]
> @AnishGG there were some files that needed to be put into makefiles, I have added them now. There's also a slight change in the vector angle method expression. Please review it ^__^

Yes, it is a good thing to compile and test your plugin before the final changes. I also usually test with command line because it is faster than recompiling everytime.
@ice0 This PR is ready to be merged. ^__^
Keep up the good work @saurabh-ramola !

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
