### PR TITLE
Fixed wrong documented comment (FrameDial=>JackDial)

### PR DESCRIPTION
**Pull request by DhairyaBahl**
Changed FrameDial => JackDial in comment

### CODE REVIEW

**Comment by DhairyaBahl** [comment]
@ice0 I am sorry, I deleted previous pull request because it became quite messed up and I was getting confused. So I did everything again. Hope you don't mind

Thanks :)

**Comment by ice0** [comment]
@DhairyaBahl No problem. Please rebase, as I fixed Appveyor CI (it fails because of keys problem)

**Comment by DhairyaBahl** [comment]
@ice0 I rebased it. Now it will work. Kindly guide me if i have to resolve it further. 

Thanks :)

**Comment by DhairyaBahl** [comment]
@ice0 Will this be included in hacktoberfest ??

Thanks :)

**Comment by AYESDIE** [comment]
This repository has `hacktoberfest` on its labels. So once this PR is approved or merged, it'll count towards the hacktoberfest progress.

\\(^_^)/

**Comment by DhairyaBahl** [comment]
@AYESDIE That's wonderul. I mean every issue will count towards hacktoberfest. GREAT !!

Thanks :)

**Review by AYESDIE — COMMENTED** [review]
This isn't rebased properly on the `master` branch. Your changes must be made on top of the changes that were made on the `master` branch.

**Comment by AYESDIE** [comment]
Also, I could see there were similar rebasing issues on your other PR. Fixing them over there would help your changes getting approved quickly.

**Comment by DhairyaBahl** [comment]
@AYESDIE I reverse merged by repo with the global repo. How can i properly rebase my repo?? Kindly guide.

Thanks :)

**Comment by DhairyaBahl** [comment]
@AYESDIE I merged master branch properly. Is that okay or I still have loopholes ?

Thanks :)

**Comment by AYESDIE** [comment]
Rebasing is different from Merging. Your changes on the commit [cd3d339](https://github.com/synfig/synfig/commit/cd3d3399b95714bb3eeaea679d7d28829f82d806) already exist in master branch on commit [0450390](https://github.com/synfig/synfig/commit/045039035ffc3c54c21f29d1c14957f4a47e1808) which adds another point in the git history. Since the changes you made only exist on the commit [dc0be1d](https://github.com/synfig/synfig/pull/1748/commits/dc0be1d2d97d98a228ccc7db21395cae1762c79f), the other commit is redundant. 

Rebasing will help you sort this one out. Here's a really big article on that: https://git-scm.com/book/en/v2/Git-Branching-Rebasing 
Or else you can look for it too. There are alot of resources explaining how it works.

**Comment by DhairyaBahl** [comment]
@AYESDIE TBH I actually thought they were same. Now you told me, i will read it in more detail. 

Thanks :)

**Comment by DhairyaBahl** [comment]
@AYESDIE I daily have to merge every branch of my repo to the upstream. I guess rebasing will solve the problem. 

Thanks :)

**Comment by DhairyaBahl** [comment]
I rebased each and every branch of my repo. 
git fetch upstream , git rebase upstream/master , git push -f origin master and then to each and every branch individually
Kindly look on my PR now. 

Thanks :)

**Review by AYESDIE — APPROVED** [review]
Nice job.

@ice0 you can check and merge this ^_^

**Comment by DhairyaBahl** [comment]
@AYESDIE Thank you brother :).1st PR with SYNFIG YaY !!  Kindly look at my other PRs too.

**Comment by ice0** [comment]
Fixes https://github.com/synfig/synfig/issues/1742
Merged. Thank you!

**Pull request merged**
