### PR TITLE
Bone Tool: fix selection of active bone when clicking on a bone duck

### LINKED ISSUE #2469: Can't select active bone when creating Skeleton Deformation layer
**Describe the bug**
When creating  Skeleton Deformation Layer using Bone Tool clicking on existing bone should set it as active (parent to next one).
But if Skeleton Deformation Layer is placed inside of **transformed** group, then it is not possible to select active bone anymore.

**To Reproduce**
Video - https://youtu.be/1hExD64ZkbE

**System information:**
 - Commit ID: 310aaad378224b6db22c

### PR DESCRIPTION
**Pull request by rodolforg**
fix #2469

### CODE REVIEW

**Review by ice0 — DISMISSED** [review]

**Comment by morevnaproject** [comment]
Hi! I have tested it and for some reason the issue is still present after applying changes from this PR.

**Comment by morevnaproject** [comment]
This feature looks fantastic!

Though, I have found one issue while testing.
Here is a sample file -
[scene014-bug.sif.zip](https://github.com/synfig/synfig/files/7801385/scene014-bug.sif.zip)

Open it in Synfig, you will see one Skeleton Deformation Layer inside. Turn it off and Synfig will crash with an error:
```
synfigstudio: ../../../../src/cairo-arc.c:189: _cairo_arc_in_direction: Assertion `angle_max >= angle_min' failed.
```

Thank you! ^__^

**Comment by morevnaproject** [comment]
Woops, sorry, commented on wrong issue ^__^"

**Comment by rodolforg** [comment]
@morevnaproject  sorry my poor testing: I completely missed the point.

Now it is fixed - I hope :)

**Comment by morevnaproject** [comment]
Works perfectly now! Thank you!

**Review by morevnaproject — APPROVED** [review]

**Pull request merged**
