### PR TITLE
fix: Wrong color in HSV wheel when color was changed with paint bucket

### LINKED ISSUE #2678: Wrong color in the parameters
**Describe the bug**
When a color is placed on a shape, when you open the color window in the parameters docker, it shows the wrong color different from the one the shape has in the workspace. The same thing happens in the tool docker when clicking on the fill color box the window that opens has the same error.

**To Reproduce**
1. Create any region or shape with area to color.
2. Select any color and with the paint bucket tool paint the shape.
3. Go to the parameters docker and click on the color parameter.
4. In the color window you will see a different color than the one assigned.

**Expected behavior**
It should have the color that was just assigned.

**Screenshots**

https://user-images.githubusercontent.com/45057390/172741819-6d9301e1-9740-4012-ab1d-a6688442b4b2.mp4

**System information:**
 - OS:Arch Linux x64 with Kernel 5.15.45-1-lts
 - Development version:
 - Revision: 20220606
 - Branch: master
 - Revision ID: a18ac7b
 - Built on Jun  7 2022

**Additional comments**
I hope it will be useful for everyone, thanks for the hard work.

### PR DESCRIPTION
**Pull request by ice0**
Fix #2678

`are_close_colors` always returned true.

### CODE REVIEW

**Comment by rodolforg** [comment]
I guess the main reason was: `Gdk::Color::get_red()` returns `unsigned short`, and `Gdk::RGBA::get_red()` returns `double`.
I wonder if there are more similar cases around.

**Comment by ice0** [comment]
Related PR #2654

**Comment by rodolforg** [comment]
Looking at git history, this method was created by commit 951cd2daf51558e1bef2800987cf2b920bdc48e6 for fixing #452.

Does this bug remain fixed? (I can't test your PR right now).

**Comment by ice0** [comment]
> Looking at git history, this method was created by commit [951cd2d](https://github.com/synfig/synfig/commit/951cd2daf51558e1bef2800987cf2b920bdc48e6) for fixing #452.
> 
> Does this bug remain fixed? (I can't test your PR right now).

The problem is that when we call the `hvsColorWidget->set_current_rgba`, we immediately lose the HUE value, which sets rotation angle for color wheel and the color wheel is reset to zero position.
Unfortunately there is no way to set color wheel using HSV value, so I reverted back this function (`are_close_colors`).

**Review by rodolforg — APPROVED** [review]

**Pull request merged**
