### PR TITLE
Proposed v1.4.2

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by morevnaproject** [comment]
Awesome! Now, can you please move all relevant PRs in "Backported" column on this board? - https://github.com/synfig/synfig/projects/9 ^__^

**Comment by rodolforg** [comment]
What are those building errors? :(

**Comment by rodolforg** [comment]
Relevant or all related PR ? How should I know what is 'relevant'? XD

What about related issues? Only those already there or all?

**Comment by ice0** [comment]
Windows builds (with autotools) always fails by timeout.
MacOS... I don't know what's happening I need to check.

**Comment by rodolforg** [comment]
Sorry my strange syntax, but here is the list of PR included in this proposal for v1.4.2:
```
1173    #
- 1963
1429
1325
1337
1351 (1349)
1979    #
1982 (311)
1995    #
2000
2059    #
2046
2001
2057
2066 (https://forums.synfig.org/t/animate-a-parameter-converted-to-a-time-loop/11839)    #
2071 (+- 453)    #
2084    #
2092 (2087)    #
2102    #
2157
1929 (
https://forums.synfig.org/t/moving-panels-in-layout/11634)    #
2109 (+- 2047)    #
2107 (2035)    #
2120 (2119)    #
2116 (2110)    #
1890 (1731)    #
1260 (1256)    #
1956
2165    #
1769 *** (1768)
- 1776
1811 (1005)
1823 (1794, 1336)
- 1848 (1798)
1855 (1854)
1953
2033 (2026   https://forums.synfig.org/t/anyone-know-how-to-toggle-animate-mode-as-a-hotkey/11787)    #
2156
2160 (422)
```

- Contents surrounded by parenthesis is a related bug report. If preceded by  "+-", it is partially solved.
- # means it is in "Backported" panel of project 1.4.2
- prepended - char means only part of PR was used
- *** (in 1769 only) - the PR number is not in the commit message…

**Comment by rodolforg** [comment]
Ok, I need to backport this commit https://github.com/synfig/synfig/commit/7f67cc22dc831edb199b82c71aab22b407aa3292#diff-d9c4f996f4bd5c99a9379d67087e3947b8313d471574e9a82635bd178fdd168d  (partially)

**Comment by rodolforg** [comment]
@morevnaproject  @ice0  appveyor is failing due to missing mlt++

and Catalina is due to this message:
```
In file included from ../../../test/stringf.cpp:25:
  CXXLD    fixed
In file included from ../../../ETL/stringf:32:
In file included from ../../../ETL/_stringf.h:41:
In file included from /usr/local/Cellar/glibmm@2.66/2.66.1/include/glibmm-2.4/glibmm/miscutils.h:23:
In file included from /usr/local/Cellar/glibmm@2.66/2.66.1/include/glibmm-2.4/glibmm/arrayhandle.h:21:
In file included from /usr/local/Cellar/glibmm@2.66/2.66.1/include/glibmm-2.4/glibmm/containerhandle_shared.h:21:
/usr/local/Cellar/glibmm@2.66/2.66.1/include/glibmm-2.4/glibmm/refptr.h:92:18: error: expected ';' at end of declaration list
  inline RefPtr() noexcept;
                 ^
                 ;
```

**Comment by ice0** [comment]
> @morevnaproject @ice0 appveyor is failing due to missing mlt++

Yeah, I can add it, but the build will still fail due to the time limit. (for testing the release, it installs and builds everything twice). 

> 
> and Catalina is due to this message:
> 
> ```
>   inline RefPtr() noexcept;
> Does it not support C++11?

It support C++11. You can see it in logs (https://github.com/synfig/synfig/pull/2168/checks?check_run_id=3038685167)
```
checking for ranlib... ranlib
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
...
$CXX ------------------------------> 'g++'
$CXXFLAGS -------------------------> '-g -std=c++11 -W -Wall -O2 -DNDEBUG'
```

The problem here is "-w" flag, which is used to suppress warnings. I don't know why, but adding this flags breaks `make distcheck` command.
https://github.com/synfig/synfig/blob/960c100c98e31a11023c525a9a77b7870237e6ba/autobuild/synfigstudio-release.sh#L98

Any idea why this is happening?

**Comment by rodolforg** [comment]
> Yeah, I can add it, but the build will still fail due to the time limit. (for testing the release, it installs and builds everything twice).

Oh, ok. Maybe we should provide a pre-built binary in synfig.org server? Or ask for msys2.org?



> Any idea why this is happening?

Maybe it is overriding the internally defined CXXFLAGS?

**Comment by rodolforg** [comment]
> Oh, ok. Maybe we should provide a pre-built binary in synfig.org server? Or ask for msys2.org?

I just found out it _is_ provided by MSYS2 in the mlt package!
https://packages.msys2.org/package/mingw-w64-x86_64-mlt?repo=mingw64

 `/mingw64/bin/libmlt++.dll`

**Comment by morevnaproject** [comment]
>> Awesome! Now, can you please move all relevant PRs in "Backported" column on this board? - https://github.com/synfig/synfig/projects/9 ^__^

> Sorry my strange syntax, but here is the list of PR included in this proposal for v1.4.2:
> ...

@rodolforg Thank you for providing the list!

Now I am going to make sure that all PRs are moved to "Backported" column. This is needed to filter already released PRs when we will generate Release notes for 1.5.x.

Also, I need to think what to do with partially-backported PRs. 
I will try following logic:
- If the remaining  (non-backported) part of PR is safe to ignore in future Release Notes, then this PR s moved to "Backported" column.
- Else: I will not move PR into "Backported" column, but I will edit PR's description to clarify which part of PR was backported already. Also, I'll have to make that backported part of PR is reflected in Release Notes of 1.4.2.

**Comment by morevnaproject** [comment]
I wonder, if it is okay to have #2199 (Advanced Outline for Lottie) backported here... We have a lot of commits made during GSOC-2020's Lottie project, which are not included in this branch. I am worried that this can break functionality? @rodolforg did you had chance to verify if Lottie exporter works correctly?

**Comment by rodolforg** [comment]
>  @rodolforg did you had chance to verify if Lottie exporter works correctly?

I followed ice0 suggestion and I copied the current lottie exporter plugin folder contents into the 1.4.x branch. I downgraded the changes made by Mattia Basaglia in plugin exporter system. I made it before #2199 (with support to a lot of converters, regular outline layer, etc). After that, I tested some cases (animated circles and rectangles).

Outline and Advanced Outline initial support is good but yet not perfect. However, I think it's better than no support?

**Comment by morevnaproject** [comment]
@rodolforg I see. Sure, then the Lotti exporter should work correctly. But in this case we should put all Lottie Exporter PRs into "Backported" column of 1.4.2 project. Otherwise all those changes will appear in future Release Notes of 1.5.x, which we do not want to do.

Actually, I also need a list of all those PRs to include them into Release Notes of 1.4.2 (because there are a lot of changes made during GSoC-2020). ^__^

**Comment by morevnaproject** [comment]
P.S. @rodolforg I appreciate that you have put PR number in description of last commit when doing cherry-pick of PR with multiple commits. This really helps to track changes. I think this is a very good practice, what do you think @ice0? ^__^

screenshot_004

**Comment by rodolforg** [comment]
> Actually, I also need a list of all those PRs to include them into Release Notes of 1.4.2 (because there are a lot of changes made during GSoC-2020). ^__^

Lottie Exporter plugin: - Fix converter methods not working with radius of simple circle layer (#1101) - Add support for variable gamma correction (#1174) - Add support for converters: sine, cos, integer, linear gradient, aTan2, Vector angle, radial_composite, radial gradient, vector x, vector y, power, dot product, logarithm, reciprocal, range, vector length, not (#1236 #1254 #1286 #1363 #1409 #1447 #1446 #1516 #1515 #1593 #1586 #1619 #1606 #1650 #1587) - Add support for blur layers (#1505) - Add support for Outline layer without variable widths (#1647) - Add support for Advanced Outline layer (#2199) - Improve support for exported values (#2182)

**Comment by rodolforg** [comment]
I kept track of everything I cherry-picked on this branch here:
https://github.com/synfig/synfig-docs/blob/1.4.2-release-notes/source/releases/stable/1.4.2.rst
of this PR https://github.com/synfig/synfig-docs/pull/29

**Comment by morevnaproject** [comment]
> Lottie Exporter plugin: - Fix converter methods not working with radius of simple circle layer (#1101) - Add support for

Got it, thank you! Also #2202 is there too. ^__^

> I kept track of everything I cherry-picked on this branch here:
> https://github.com/synfig/synfig-docs/blob/1.4.2-release-notes/source/releases/stable/1.4.2.rst
> of this PR [synfig/synfig-docs#29](https://github.com/synfig/synfig-docs/pull/29)

Awesome! I have added all PRs included here into 1.4.2 project (included Lottie ones).

Since all those PR are already included into draft release notes [synfig/synfig-docs#29](https://github.com/synfig/synfig-docs/pull/29), I have moved them from "Backported" to "Release Notes" column.

So, we can safely merge this PR now! :tada:

**Pull request merged**
