### PR TITLE
refactor!: clean etl::angle

### PR DESCRIPTION
**Pull request by rodolforg**
BREAKING CHANGE: some etl::angle API changed - see related commits

### CODE REVIEW

**Comment by rodolforg** [comment]
Will this PR be accepted?
Can I remove stuff inside `ETL_WRAP_ANGLES` too? It was commented out 15 years ago: https://github.com/synfig/synfig/commit/7555e3b7805d66eac4fd47efd0a05b90db61387b

**Comment by ice0** [comment]
> Will this PR be accepted? Can I remove stuff inside `ETL_WRAP_ANGLES` too? It was commented out 15 years ago: [7555e3b](https://github.com/synfig/synfig/commit/7555e3b7805d66eac4fd47efd0a05b90db61387b)

Yes and yes.

**Comment by rodolforg** [comment]
Ready for review, but a doubt:
should Angle be fully on a header file as it was/is, or should we separate in an implementation file too?

**Comment by rodolforg** [comment]
(rebased)

**Comment by ice0** [comment]
> should Angle be fully on a header file as it was/is, or should we separate in an implementation file too?

I suggest to leave it header-only, because in that case it has more chances for optimizations.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
