### PR TITLE
feat: added toggle setting for plugin warnings

### PR DESCRIPTION
**Pull request by Funinja**
Added functional disable plugin warning setting as requested from issue #3186. 

New setting in preferences:
image

New plugin warning:
image

### CODE REVIEW

**Comment by Funinja** [comment]
Force-pushed was for the commit messages only.

**Comment by ice0** [comment]
@mohamedAdhamc @morevnaproject @pgilfernandez @rodolforg 

I'm not sure, but do we need a global option, or should it be for each plugin?

**Comment by pgilfernandez** [comment]
Maybe it's a good idea to have the option per plugin. That way once you fully trust a plugin you can disable warning just for it...

**Comment by mohamedAdhamc** [comment]
> Maybe it's a good idea to have the option per plugin. That way once you fully trust a plugin you can disable warning just for it...

I agree, having it be per plugin does make more sense or at least I see it that way. So I use a plugin a lot and I trust it doesn't mess my work and then I just want to increase the speed of my workflow. That doesn't necessarily mean I would feel the same about the other plugins i have now or in the future.

Although I think we can also possibly have a global one as well, but it'd have to be done in a way that would be easier for the user to understand and not confuse them both.

**Comment by Funinja** [comment]
I agree with everyone here, having the option to toggle warnings per plugin makes sense.

 Unfortunately, I believe the best solution to this feature would be to build a Plugin Dialogue Manager to interface with plugin toggle warning settings individually and make them persistent (after closing and reopening the application). Funny enough, the plugin dialogue manager is one of the ideas in this year's GSOC proposal and I don't know if it is fair for me to start on this contribution, being currently one of GSOC's applicants for the plugin manager for Synfig.

 If it is okay with everyone, I can make a simple plugin dialogue manager with the only feature being to toggle the individual plugins, and the GSOC applicant who is picked to develop the plugin dialogue manager can use it as a base code for their development.

**Comment by mohamedAdhamc** [comment]
@Funinja how about just changing "do not show warning" to something like "do not show warning again for this plugin". And you can then save which plugins have a "do not show warning" preference set to them. If they do then you wouldn't show the warning and if they don't then you can show it normally.

or possibly adding "do not show warning again for this plugin" underneath the current "global" one.

@ice0 any thoughts on this ?

**Comment by Funinja** [comment]
> @Funinja how about just changing "do not show warning" to something like "do not show warning again for this plugin". And you can then save which plugins have a "do not show warning" preference set to them. If they do then you wouldn't show the warning and if they don't then you can show it normally.
> 
> or possibly adding "do not show warning again for this plugin" underneath the current "global" one.
Yes, I can do this, but my main concern is if someone accidentally disables the warning for a certain plugin and wants to turn the warning back on. I'm not sure where would they go if they want to turn it back on.

**Comment by mohamedAdhamc** [comment]
> > @Funinja how about just changing "do not show warning" to something like "do not show warning again for this plugin". And you can then save which plugins have a "do not show warning" preference set to them. If they do then you wouldn't show the warning and if they don't then you can show it normally.
> > or possibly adding "do not show warning again for this plugin" underneath the current "global" one.
> 
> Yes, I can do this, but my main concern is if someone accidentally disables the warning for a certain plugin and wants to turn the warning back on. I'm not sure where would they go if they want to turn it back on.

Ok, yes now I see what you mean.

**Pull request closed without merging**
