### PR TITLE
refactor: prefer CanvasView::Handle & others instead of etl::handle

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by ice0** [comment]
@rodolforg 
Looks good, please rebase.

**Comment by rodolforg** [comment]
Done

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
@rodolforg 

Forgot to ask. What does `cia` mean?

**Comment by ice0** [comment]
Ok, got it.

Merged. Thank you!

**Pull request merged**
