### PR TITLE
Skeleton tool Cont.

### PR DESCRIPTION
**Pull request by Aa20475**
This is a continuation PR to PR #1485

### CODE REVIEW

**Comment by morevnaproject** [comment]
Again, please try to avoid making commits that do 2 or more things.

**Comment by morevnaproject** [comment]
This PR has following problem: there are several unfinished  features in this branch (I mean 24ca0ae65c20123442767b1082e7da590aca0a61 and 044c21c). This make it hard to test, because both unfinished features has issues and they are overlapping, so it gets hard to detect where issues come from. 

Can you please separate unfinished features into separate branches? (they both should "grow" from "Conditional Width points; Minor fixes" commit)
After that every branch can become separate PR, with clean commits history.

**Comment by Aa20475** [comment]
But I thought I'll stop working on Dashed line till I complete the single parameter. Do you think I should still have separate PRs?

**Comment by morevnaproject** [comment]
Yes, you should learn how to work on separate PRs. Previous PR (#1485) was a mess in terms of commits, but that was okay, since you've been busy learning the source code. Now it's time to learn to make a clean contributions. Mixing several fixes into one is not good for development. ^__^

**Comment by morevnaproject** [comment]
If you need help with separating commits - let me know or ask @rodolforg.

And yes, it's best to resolve issues with PR #1485 first, so I can merge it. ^__^

**Comment by Aa20475** [comment]
Alright! Will make the changes you requested first!  I'll come to this after that! Let's get that merged! :smiley:

**Comment by morevnaproject** [comment]
#1485 is merged now. Please re-organize your new commits into separate branches. ^__^

**Comment by Aa20475** [comment]
Hey! 

As you suggested, now I have two branches to work on those issues separately. Do you want me to open two separate PRs. What do I do with the new PR I made?

**Comment by morevnaproject** [comment]
Yes, please make two separate PRs.

> What do I do with this PR?

Please make a list of things that remaining in this PR and post it here.

**Comment by Aa20475** [comment]
I'm also rebasing with the master branch

**Comment by Aa20475** [comment]
Alright! I made the PRs as you suggested!

**Comment by morevnaproject** [comment]
> I made the PRs as you suggested!

Good. I suggest to put more meaningful names for PRs. I.e. for #1605 it can be "Skeleton Tool: Use dashed outline for parent-child relationships". ^__^

> Please make a list of things that remaining in this PR and post it here.

Please post a list of commits that remaining in this PR (the ones not included into other PRs).

**Comment by Aa20475** [comment]
Okay 😅😅

**Comment by Aa20475** [comment]
Actually, there are no other changes in this PR. Should I close it?

**Comment by morevnaproject** [comment]
> Actually, there are no other changes in this PR.

This is what I was expecting. ^__^

> Should I close it?

Yes.

**Pull request closed without merging**
