### PR TITLE
Fix whitespace indentation

### LINKED ISSUE #1755: Fix whitespace indentation for duckmatic.cpp
**Issue description**:
The file duckmatic.cpp is indented with spaces. All synfig files use tab character for indentation.
Moreover, we also have `-Wmisleading-indentation` warning message triggered because of inconsistent whitespace indentation.

On your preferred IDE or programming text editor, turn on whitespace visualization (if this feature is provided) to easily fix this issue.

# Spaces
Screenshot from 2020-10-09 12-25-06

# Tabs
Screenshot from 2020-10-09 12-24-18

### PR DESCRIPTION
**Pull request by rahmanuh**
Fix #1755 

This is a huge change :sweat_smile:
I have made sure there is no `-Wmisleading-indentation` warning from this file.

### CODE REVIEW

**Comment by Keyikedalube** [comment]
You forgot these lines:
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L316-L323
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L366
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L1589-L1590

**Comment by Keyikedalube** [comment]
@rahmanuh Please use your editor whitespace visualization feature to track down spaces. There are more :(

This file is too big. It's tedious to keep pulling updates and scrolling.

Here's some more I tracked down:
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L170
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L934
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L2133
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L2142
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L2148
- https://github.com/synfig/synfig/blob/044390e07476da87d0d957eb7b9770bc7d618f42/synfig-studio/src/gui/duckmatic.cpp#L2779

Fingers crossed these are all the ones left to fix and there's no more.

**Comment by AYESDIE** [comment]
The size of changes makes me wonder why don't we use a `.clang-format` file on our project. That can help us to not only define a C++ coding format but will also help us to format the code according to our defined format. *clang-format* is also supported by alot of IDEs already.

Any thoughts?

**Comment by ice0** [comment]
@AYESDIE Maybe because where is no clang in 2001 😅
I think this is a good idea to add `.clang-format` for the project. It would also be nice to integrate automatic style checking into our CI for the new PRs.

**Comment by AYESDIE** [comment]
Oh ofcourse I didn't mean it about when the project actually began but I think this is something we should add so as to automatically fix similar issues without the need of manual review and stuff. And yes, we can also take advantage of automatic style checking in CI after that.

**Review by Keyikedalube — APPROVED** [review]
All OK to me :)

Up to maintainers now. Might need to be squashed though.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
