### PR TITLE
Workarea handle selection

### PR DESCRIPTION
**Pull request by d-j-a-y**
Now the handles selection in the workarea is interactive. Shift & Ctrl modifier reactive.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hello! Nice improvement! But there is some problem - the selection border is not disappears after you release the mouse button. It stays visible and after some time disappears. See this video for demonstration - http://cloud.morevnaproject.org/seafile/f/9221e363ef/

Commit id: 9340db1
Tested with gtk 3.14.13 and gtk 3.10.9.

**Comment by d-j-a-y** [comment]
>the selection border is not disappears after you release the mouse button.

should be fixed now ( commit id : d0ed161 )

**Comment by morevnaproject** [comment]
Works perfectly now! Thank you!

**Comment by morevnaproject** [comment]
Merged.

**Pull request closed without merging**
