### PR TITLE
Fix incorrect position of Widthpoints on Homogenous Advanced Outline

### LINKED ISSUE #1431: Incorrect position of Widthpoints on Homogenous Advanced Outline
**Synfig version & platform**:
1.3.14, current master

**Issue description**:
When Advanced Outline has "Homogenous" parameter enabled, then positions of widthpoints are not correct. See sample file and illustrations below.

Sample file - [homogenous-bug.sifz.zip](https://github.com/synfig/synfig/files/4651232/homogenous-bug.sifz.zip)

Version 1.2.2:
screenshot_002

Version 1.3.14:
screenshot_001

@blackwarthog can you take a look please?

### PR DESCRIPTION
**Pull request by rodolforg**
fix #1431

### CODE REVIEW

**Comment by rodolforg** [comment]
Please test it wih different splines o.O
Homogeneous or not.
Looped or not.

**Comment by morevnaproject** [comment]
:open_mouth: :rocket: :boom:

**Comment by morevnaproject** [comment]
It works perfectly now! :tada:

**Comment by morevnaproject** [comment]
Also merged to v1.3.x. Thank you so much for the fix!

**Pull request merged**
