### PR TITLE
FrameDial=>JackDial

### PR DESCRIPTION
**Pull request by DhairyaBahl**
This is commit for issue #1742 Kindly look forward to this PR.

@Keyikedalube @AYESDIE @ice0 

Thanks :)

### CODE REVIEW

**Comment by AYESDIE** [comment]
You have already made a PR for that issue over here #1748...

**Comment by DhairyaBahl** [comment]
@AYESDIE Extremely sorry. I am getting a bit confused b/w all the PRs. By the way we can actually use this PR if you want coz there is no rebasing problem. Otherwise i have no problem in closing it. :+1: 

Thank you and sorry :)

**Comment by AYESDIE** [comment]
The other PR is already fine and I have approved it already, you don't need to make a new PR for that same issue.

**Comment by DhairyaBahl** [comment]
@AYESDIE Okay Got it. Sorry for inconvenience 

Thanks :)

**Pull request closed without merging**
