### PR TITLE
fix: update Solid Color layer name in Lottie exporter

### PR DESCRIPTION
**Pull request by pgilfernandez**
Synfig solid Color layers weren't exported because the layer name changed (in v1.4.4 it's `SolidLayer` while in new v1.5x it's `solid_layer`) but it wasn't updated in the Lottie exporter plugin.

Now it works again
=D

fix https://github.com/synfig/synfig/issues/3198

### CODE REVIEW

**Comment by pgilfernandez** [comment]
BTW, this PR closes issue https://github.com/synfig/synfig/issues/3198
;)

**Comment by rodolforg** [comment]
Please add "fix #3198" as the last line of your PR description. This will autoclose the issue ;)

**Comment by pgilfernandez** [comment]
> Please add "fix #3198" as the last line of your PR description. This will autoclose the issue ;)

Thanks for the tip!
I added it in the first post, is it like that?

**Comment by rodolforg** [comment]
It was broken since e087e44e449510fd9da1f741e00a0fbeb0f42ba6 ... :(

**Review by rodolforg — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
