### PR TITLE
fix: prevent memory leak on importing PNG files

### PR DESCRIPTION
**Pull request by rodolforg**
And it's HUGE: the whole image.

### CODE REVIEW

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by morevnaproject** [comment]
I have noticed the leak during rendering big project last week, but didn't knew why this happens. It was eating 20 Gb of RAM. Thank you so much!

**Comment by rodolforg** [comment]
This problem dates 1.2.0 version o.O

**Comment by rodolforg** [comment]
b4ec83f5d6bff7c2e3a350754a3cbf35123c4181

**Comment by ice0** [comment]
@morevnaproject 
Forgot to backport this.

**Pull request merged**
