### PR TITLE
Fix #997 Re-arranged Gamma widgets layout to make render window fit on lower resolution screens

### LINKED ISSUE #997: Render window unresizable
**Synfig version & platform**:
1.3.11
*Development version:
Revision: 20191027
Branch: master
Revision ID: d0285b*

**Issue description**:
Can't resize render dialog window on my Debian (XFCE) system. The window is too large, buttons like Cancel and Render are not accessible

Screenshot_2019-11-06_08-43-00

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83251186-render-window-unresizable?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Keyikedalube**
- Aligned Gamma pattern and sliders to 2nd column
- Turned off set_draw_value

### CODE REVIEW

**Comment by Keyikedalube** [comment]
@ice0 Here's the PR for #997 
Couldn't fix the slider snapping behavior.

**Comment by ice0** [comment]
Hi!
In your code you need to add **set_round_digits(1);**
```
scale_gamma_r->set_hexpand(true);
scale_gamma_r->set_draw_value(false);
scale_gamma_r->set_round_digits(1);
```
for all scales. This will bring snapping back.

**Comment by Keyikedalube** [comment]
Thanks @ice0 Committed the changes.

**Comment by morevnaproject** [comment]
I have one more idea: how about to place widgets like this? -
68775336-50bffb80-0654-11ea-9551-c09ee74ed273

**Comment by Keyikedalube** [comment]
[Your first layout idea](https://github.com/synfig/synfig/issues/997#issuecomment-553447377) looks clean and somewhat more accessible than the one above.

However, that new (second) layout will save even more blank areas for other tabs ;) If you like I can go back and hack the code again.

BTW I have an additional idea for your new layout too. How about abbreviating the color names ie., instead of labeling as
- Red
- Green
- Blue
we could label it as
- R
- G
- B
That way the sliders can have more horizontal space.

**Comment by morevnaproject** [comment]
> However, that new (second) layout will save even more blank areas for other tabs ;) If you like I can go back and hack the code again.

Yes, the idea is to save even more space. ^__^ Can you implement this layout, please?

About replacing "red, Green, Blue" to "R, G, B":
I think it is better to keep them as they are, because "R, G, B" might be problematic for localization.

**Comment by Keyikedalube** [comment]
> Yes, the idea is to save even more space. ^__^ Can you implement this layout, please?

Made the changes :)


In order to make more space for sliders I commented out hexpands for spin buttons.
I noticed the spin buttons for other tabs **Image, Time,...** expands if the window is maximized.
For Gamma correction tab the spin buttons won't expand only the sliders will.

**Comment by morevnaproject** [comment]
Looks great now! ^__^

**Comment by morevnaproject** [comment]
Merged via 529e50e4280e469f787cdba2e5a2aacf8e1f8d0a.
Thank you!

**Pull request closed without merging**
