### PR TITLE
don't duplicate warning message about old canvas

### LINKED ISSUE #1380: Multiple repeated warning messages when opening old file
When opening an old file (2017) https://wiki.synfig.org/images/3/38/Crosshair-leg.zip
I got this warning dialog:
Captura de tela de 2020-04-26 09-36-33

### PR DESCRIPTION
**Pull request by rodolforg**
fix #1380

Not best solution though

### CODE REVIEW

**Comment by ice0** [comment]
@rodolforg Maybe add a bool flag and add message text if it enabled?

**Comment by morevnaproject** [comment]
We can check if canvas is root:

```
if (canvas->is_root()) {
... do stuff ...
}
```

Would that work? ^__^

**Comment by morevnaproject** [comment]
I have mate another PR for that - #1391 ^__^

**Comment by rodolforg** [comment]
Close due to #1391

**Pull request closed without merging**
