### PR TITLE
Fix issue #1231

### LINKED ISSUE #1231: Setting environment dependencies on openSUSE leads to conflicting commands
**Synfig version & platform**:
Master: c3054c4
openSUSE Leap 15.1

**Issue description**:
If you want to setup a freshly installed openSUSE machine using the provided script:
"1-setup-linux-native.sh"

The command:
"if command -v apt-get >/dev/null; then"

which includes apt-get is detected by the OS and thus the part needed to set openSUSE using zypper is not chosen:
"elif which zypper >/dev/null; then"

Currently I have simply removed all the code before the code for zypper and it works correctly. Probably the order should be from the most specific package manager (e.g zypper or yum) to the most generic like apt-get.

### PR DESCRIPTION
**Pull request by FirasH**
Fixes #1231 
Change the order of the Package Managers for Linux system to avoid ambiguities with apt-get

### CODE REVIEW

**Comment by FirasH** [comment]
I have tested  it on openSUSE and it works perfectly.
Could someone please verify if it works on Ubuntu/Debian?

**Comment by FirasH** [comment]
Fixes #1231

**Comment by FirasH** [comment]
Fixes #1231

**Comment by ice0** [comment]
Checked on Ubuntu - works fine. @morevnaproject please review.

**Comment by morevnaproject** [comment]
Looks good to me! ^__^

**Pull request merged**
