### PR TITLE
Use /etc/os-release to detect OS

### LINKED ISSUE #1255: "1-setup-linux-native.sh" script: Use values from "/etc/os-release" to detect OS
As improvement to #1231:
We can use `/etc/os-release` file to detect OS properly.

Here is the contents of this file on my Linux Mint sysem:
```
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

We can import those values into `1-setup-linux-native.sh` script with this:
```
source /etc/os-release
```

...and then check `ID_LIKE` variable:

```
if [ "$ID_LIKE" == "ubuntu" ]; then
   ... (apt-get stuff) ...
elif ...
```

@FirasH what do you think about this? ^__^

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/90292418-1-setup-linux-native-sh-script-use-values-from-etc-os-release-to-detect-os?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by FirasH**
Fixes #1255

### CODE REVIEW

**Comment by FirasH** [comment]
I tried it on openSUSE 15.1 and Ubuntu 18.04 and it works.

**Comment by ice0** [comment]
I will check on Manjaro tomorrow

**Comment by ice0** [comment]
Checked on Manjaro - everything works fine.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
