### PR TITLE
7 new icons 

### PR DESCRIPTION
**Pull request by jcome**
- Replace Gtk Icons with Synfig Studio Version for: New, Open, Save, Save As, Save All, Undo and Redo icons

### CODE REVIEW

**Comment by genete** [comment]
"Open an existed document" Please replace it with "Open an existing
document"

2015-04-26 10:29 GMT+02:00 Yu Chen <notifications@github.com>:

>
>    - Replace Gtk Icons with Synfig Studio Version for: New, Open, Save,
>    Save As, Save All, Undo and Redo icons
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/synfig/synfig/pull/186
> Commit Summary
>
>    - Rename spal file filter according to other dialogs
>    - Merge http://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Merge https://github.com/synfig/synfig
>    - Add new icons for New, Open, Save/As/All and Un/Redo
>    - Remove unused icon saveall_icon.sif
>
> File Changes
>
>    - *M* synfig-studio/images/Makefile.am
>    <https://github.com/synfig/synfig/pull/186/files#diff-0> (47)
>    - *D* synfig-studio/images/saveall_icon.sif
>    <https://github.com/synfig/synfig/pull/186/files#diff-1> (80)
>    - *M* synfig-studio/src/gui/app.cpp
>    <https://github.com/synfig/synfig/pull/186/files#diff-2> (14)
>    - *M* synfig-studio/src/gui/canvasview.cpp
>    <https://github.com/synfig/synfig/pull/186/files#diff-3> (4)
>    - *M* synfig-studio/src/gui/docks/dock_history.cpp
>    <https://github.com/synfig/synfig/pull/186/files#diff-4> (4)
>    - *M* synfig-studio/src/gui/iconcontroller.cpp
>    <https://github.com/synfig/synfig/pull/186/files#diff-5> (14)
>    - *M* synfig-studio/src/gui/mainwindow.cpp
>    <https://github.com/synfig/synfig/pull/186/files#diff-6> (6)
>
> Patch Links:
>
>    - https://github.com/synfig/synfig/pull/186.patch
>    - https://github.com/synfig/synfig/pull/186.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/synfig/synfig/pull/186>.
>



-- 
Carlos

**Comment by morevnaproject** [comment]
Hello, Yu!
I don't see any .sif files in your commits. Probably you forgot to include them?

**Comment by jcome** [comment]
2015-05-01 23:31 GMT+08:00 Konstantin Dmitriev <notifications@github.com>:

> forgot to include them?


Thanks for review. yes, and now I pushed the sif to the branch.

~ yu

**Comment by morevnaproject** [comment]
Mered now. Thank you! ^__^

**Pull request closed without merging**
