### PR TITLE
[Skeleton Tool] Edit Second bone too when Skeleton Deformation Layer edited

### LINKED ISSUE #1626: [Skeleton Tool] Edit Second bone too when Skeleton Deformation Layer edited
Let's suppose user created several bones in Skeleton Deformation Layer (using Skeleton Tool).
Then he realized that some bones are not placed correctly, so he changed their points.
With current behavior, when user edits first bone (initial position) the position of second bone is not changed.
This leads to problems, shown in this video -https://youtu.be/obN94tO6xGM

Solution:

When user edits first bone of Skeleton Deformation Layer, then the same modification should be applied to second bone.

It is important to note that we should apply delta value.

I.e. let's suppose first bone has angle 30 degrees and it was changed to value of 45 degrees. Then we should add 15 degrees to second bone.

### PR DESCRIPTION
**Pull request by Aa20475**
Closes #1626 

Still need to add a condition to check if the current state is `state_bone`

### CODE REVIEW

**Comment by Aa20475** [comment]
Hey! I don't seem to find a way to check if we are using skeleton tool. I thought of an alternative though, I can add a signal to `canvas_interface` similar to how I did to set the `active_bone`.

**Comment by Aa20475** [comment]
Hey! It works! But I made a change to `CanvasInterface`. Please verify and let me know.

**Comment by morevnaproject** [comment]
Testing now!

**Comment by morevnaproject** [comment]
I have tested the PR. It generally works well, but I have some notes:

1. Currently, when one bone edited you apply **same value** to other bone. But, as mentioned in original issue, you should apply delta value:

> It is important to note that we should apply delta value.

> I.e. let's suppose first bone has angle 30 degrees and it was changed to value of 45 degrees. Then we should add 15 degrees to second bone.

2. When first bone edited I expect second bone to be modified, but **not vice versa**. So, this part of condition in `valuedescset.cpp` can be removed:
```
}else if(value_desc.get_parent_value_node() == comp->get_link("second")){
			bone = ValueNode_Bone::Handle::cast_dynamic(comp->get_link("first"));
```

**Comment by Aa20475** [comment]
Hey! I can't understand why it's crashing.

**Comment by morevnaproject** [comment]
Hi! Can you run it through debugger and post a call stack here?

**Comment by Aa20475** [comment]
Okayy

**Comment by Aa20475** [comment]
Screenshot 2020-08-27 10:38:18

This is a screenshot of the call stack

**Comment by morevnaproject** [comment]
So, it fails in this place:

screenshot_004

I suggest to split this long line into shorter lines (put intermediate values into variables).
And then see at which particular point it is crashing.

Also I am surprised that you are subtracting value of one bone from another. You should subtract old_value from new_value...

**Comment by Aa20475** [comment]
>Also I am surprised that you are subtracting value of one bone from another. You should subtract old_value from new_value...

I am taking the delta value using that right? And adding it to the new_value?

**Comment by morevnaproject** [comment]
I am expecting this:
`bone2_new_value = bone2_old_value + (bone1_new_value - bone1_old_value)`

**Comment by Aa20475** [comment]
Hey! Please verify now. I think it works!

**Comment by morevnaproject** [comment]
I have tested the PR. It works good when I modify bone angle and bone length. But when I modify bone origin the result is weird - the second bone gets shifted in unpredictable way.

**Comment by morevnaproject** [comment]
Hi! Apologies for delay with a reply. I have tested this PR and it is crashing when I am trying to move bone origin - https://youtu.be/qRq5sWAl-SI

**Comment by rodolforg** [comment]
This PR can be closed, because it was already merged via another PR… (PR #1698 )

**Comment by rodolforg** [comment]
> it is crashing when I am trying to move bone origin

and this is fixed by #2049

**Comment by ice0** [comment]
@rodolforg just rebased it. And it looks like there some unmerged changes here.

**Comment by ice0** [comment]
@Aa20475 it really looks like code duplicate :( 
Can you check if correct version is already merged?

**Comment by rodolforg** [comment]
@ice0 I recently made some changes here and you merged it.

**Comment by rodolforg** [comment]
Please compare this PR code with this one from @Aa20475 : https://github.com/synfig/synfig/pull/1698/files . They're equal.

**Comment by rodolforg** [comment]
Anyway, we need to decide how that canvas_interface->get/set_state will be done.

**Comment by ice0** [comment]
> Anyway, we need to decide how that canvas_interface->get/set_state will be done.

You mean this PR? (https://github.com/synfig/synfig/pull/1697)
If yes, then I think it can be resolved in correct way, without changes to `synfigapp` library

**Comment by rodolforg** [comment]
>  If yes, then I think it can be resolved in correct way, without changes to `synfigapp` library

How do you propose? I can make the PR if you want.

**Comment by ice0** [comment]
> > If yes, then I think it can be resolved in correct way, without changes to `synfigapp` library
> 
> How do you propose? I can make the PR if you want.

For #1697 I just removed the addition of the menu item in the `Instance` class.  So no changes to `synfigapp` is required.

You can check it here: https://github.com/synfig/synfig/pull/2064

**Comment by rodolforg** [comment]
Closed because it was already merged by PR #1698 that (accidentally?) included the change proposed by this PR.

**Pull request closed without merging**
