### PR TITLE
refactor!: remove `etl::ceil_to_int` and `etl::floor_to_int`

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by ice0** [comment]
@rodolforg 
Please rebase.

**Comment by rodolforg** [comment]
Rebased.

**Comment by ice0** [comment]
> Rebased.

One more time please. I thought you are offline and I merged another PR.

**Comment by rodolforg** [comment]
Not a problem :) Done again

**Review by ice0 — APPROVED** [review]

**Pull request merged**
