### PR TITLE
store DEFS before BONES node in SIF XML file

### LINKED ISSUE #360: Bug Synfig Studio 1.3.2 Dynamic connect
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

Hello synfig people
my name is peter , and I come from germany .

In my video you can see the problem .
https://vimeo.com/216629892

I hope the Synfig Studio is further developed .
thank you for the effort

Lg peter

### LINKED ISSUE #362: BONES structure is saved before DEFS structure
### Description:
If there're bones in Synfig project, they will be saved BEFORE defs structure. It means, that all exported values that attached (linked) to bones will not resolve correctly and Synfig won't be able to open a file.

### Affected version:
All Synfig versions started from 1.0.2.

### To reproduce:
Open attached file in Synfig and then just save it somewhere else or as sifz file. Now, try to open the newly saved file. You can't.
[BoneFollowsSpline.zip](https://github.com/synfig/synfig/files/987120/BoneFollowsSpline.zip)

Relevant: https://github.com/synfig/synfig/issues/360
That guy has the same problem. He even made a whole video about it.

P.S. Cursed github doesn't allow sif/sifz attachments.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/45004066-bones-structure-is-saved-before-defs-structure?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rodolforg**
fix #362 and fix #360

### CODE REVIEW

**Comment by rodolforg** [comment]
Is there any case BONES should come before DEFS?

**Comment by ice0** [comment]
@blackwarthog @morevnaproject your opinion?

**Comment by blackwarthog** [comment]
as i remember we moved it to solve other bug
we need some time to solve problem with bones

**Comment by rodolforg** [comment]
> as i remember we moved it to solve other bug we need some time to solve problem with bones

indeed: https://github.com/synfig/synfig/commit/c04d1499e1c61e6d6edd174fb8d36df018c475d6

**Comment by rodolforg** [comment]
Therefore, in order to solve the mentioned issues, it's better to change the SIF reader/parser to ignore/handle file data order

**Comment by blackwarthog** [comment]
> Therefore, in order to solve the mentioned issues, it's better to change the SIF reader/parser to ignore/handle file data order

i think about refactoring of bones, valuenodes, valuebase and serialization
may be i'll write prototype before

**Comment by rodolforg** [comment]
Superseded by #2433

**Pull request closed without merging**
