### PR TITLE
[Skeleton Tool] Console warning when adding bone with a parent

### LINKED ISSUE #1686: [Skeleton Tool] Console warning when adding bone with a parent
When user adds a second bone (or more bones after that) there is a warning in console appears:
```
.../synfig-core/src/synfig/valuenodes/valuenode_const.cpp:82 forcing convert to ValueNode_Bone
```

Video - https://youtu.be/f7tKf0wQeB4

### PR DESCRIPTION
**Pull request by Aa20475**
Closes #1686

### CODE REVIEW

**Comment by morevnaproject** [comment]
The build fails with the following error:
```
...
g++ -DHAVE_CONFIG_H -I. -I/home/konstantin/sources/synfig/synfig-studio/src/gui -I../..  -I/home/konstantin/sources/synfig/synfig-studio/src  -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -pthread -D_REENTRANT -I/home/konstantin/sources/synfig/synfig-core/src -I/home/konstantin/sources/synfig/ETL -I/home/konstantin/sources/synfig/_production/build/include/ETL -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/OpenEXR -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/mlt++ -I/usr/include/mlt -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DIMAGE_EXT=\"png\" -DSYNFIG_DATADIR=\"/home/konstantin/sources/synfig/_production/build/share/synfig\" -DLOCALEDIR=\"/home/konstantin/sources/synfig/_production/build/share/locale\" -fdiagnostics-color=always -O2 -DNDEBUG -MT states/synfigstudio-state_bone.o -MD -MP -MF states/.deps/synfigstudio-state_bone.Tpo -c -o states/synfigstudio-state_bone.o `test -f 'states/state_bone.cpp' || echo '/home/konstantin/sources/synfig/synfig-studio/src/gui/'`states/state_bone.cpp
/home/konstantin/sources/synfig/synfig-studio/src/gui/states/state_bone.cpp: In member function ‘etl::smach<studio::CanvasView, studio::EventKey>::event_result studio::StateBone_Context::event_mouse_release_handler(const etl::smach<studio::CanvasView, studio::EventKey>::event&)’:
/home/konstantin/sources/synfig/synfig-studio/src/gui/states/state_bone.cpp:747:84: error: expected ‘,’ or ‘;’ before ‘)’ token
        ValueNode_Bone::Handle bone_node = ValueNode_Bone::create(bone,get_canvas()));
```

**Comment by morevnaproject** [comment]
@Aa20475 Can you please fix this? I believe this is a simple typo. ^__^

**Comment by Aa20475** [comment]
Yes! ^__^

**Comment by morevnaproject** [comment]
Looks good now! Thank you!

**Pull request merged**
