### PR TITLE
Fixed Add, Subtract and Difference blend modes 

### LINKED ISSUE #821: "Add" blend method doesn't rendered properly
**Synfig version & platform**:
1.2.2 and latest baster (commit 70e71983e72ebff09a26a796b93ff9db35a15513).

**Issue description**:
"Add" blend method should crop alpha of top layer according to alpha of bottom layer. See https://wiki.synfig.org/Blend_Method_Parameter#Add

This doesn't happens, see sample file - 
[bug.sifz.zip](https://github.com/synfig/synfig/files/3118152/bug.sifz.zip)

screenshot_004

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/73331033-add-blend-method-doesn-t-rendered-properly?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ThaFireDragonOfDeath**
As I received no objections [here](https://github.com/synfig/synfig/issues/821#issuecomment-504050958), I fixed the the three broken blending modes.

**Change description:**
With this commits, blending works now as described [here](https://wiki.synfig.org/Blend_Method_Parameter#Add) for Add, Subtract and Difference blending methods (closes #821).

**Tests:**
You can test the fix with the test file uploaded in [this](https://github.com/synfig/synfig/issues/821#issuecomment-504050958) comment.

I hope, this is helpful ^.^

### CODE REVIEW

**Comment by morevnaproject** [comment]
Thank you for the fix! ^__^ It works correctly for mentioned Blend Methods now, but we need to decide about this - https://github.com/synfig/synfig/issues/821#issuecomment-504050958

**Comment by ThaFireDragonOfDeath** [comment]
@morevnaproject 
That should now fix the motion blur issue, caused by the fix for the blend functions ^.^

**Comment by morevnaproject** [comment]
@ThaFireDragonOfDeath Awesome! Thank you for taking on this. ^__^

Please consider also to change BLEND_METHODS_ASSOCIATIVE and BLEND_METHODS_COMMUTATIVE groups:
https://github.com/ThaFireDragonOfDeath/synfig/blob/edfa193d9a125312c6201ec02247c1e15b8d40b5/synfig-core/src/synfig/color/color.h#L312-L319

Those groups define if particular optimizers can be applied to blend methods during rendering.
With changes made in this PR, the "Add" blend method is no longer associative (i.e. eligible a+b=b+a rule) and commutative (eligible for a(b+c)=ab+ac rule).
But BLEND_ADD_NOCROP will be eligible for those groups instead. ^__^

**Comment by ThaFireDragonOfDeath** [comment]
@morevnaproject 
Aaaand done :).

**Comment by morevnaproject** [comment]
Finally, just one more thing: I suggest to rename `BLEND_ADD_NOCROP` to `BLEND_ADD_COMPOSITE`. Thank you! ^__^

**Comment by ThaFireDragonOfDeath** [comment]
@morevnaproject 
Done :).

**Pull request merged**
