### PR TITLE
ci: Add automatically showing contributors how their pull requests affect the release notes

### PR DESCRIPTION
**Pull request by Ahmed-Khaled-dev**
This is done by adding a simple GitHub workflow that uses the [Release Notes Manager](https://github.com/Ahmed-Khaled-dev/release-notes-manager) GitHub Action which I created for Synfig during Google Summer of Code 2024.

## What does this do?
- Adds the [second feature](https://github.com/Ahmed-Khaled-dev/release-notes-manager?tab=readme-ov-file#2-automatically-shows-contributors-how-their-pull-requests-affect-the-release-notes) listed in the features of the Release Notes Manager.

- Finishes the optional/additional point in the first half of the [Google Summer of Code Project](https://synfig-docs-dev.readthedocs.io/en/latest/gsoc/2024/ideas.html#automated-release-notes-generator-and-packaging-script-fixes-175-or-350-hrs)

A detailed explanation of how it works can be found in the video below (originally used in a status update message)

https://github.com/user-attachments/assets/5820743b-4e6d-43d8-ad56-0db2ad9a2b6e

## Why is this beneficial?
- Enhances the description of the changes in the release notes for clearer understanding, since the contributors' pull requests' titles and descriptions will look bad in the release notes if they aren't clear, and the GitHub bot will encourage them to improve it, so they will automatically improve it to make it more descriptive

- Gives Synfig's pull requests a more professional feel, which can result in attracting more new contributors

## Note
- The current version of the Release Notes Manager GitHub Action offers limited customization from the workflow in this repository. Additional customization features (like customizing the messages the bot sends) can be added later after closing issue [#3377](https://github.com/Synfig/Synfig/issues/3377), but for now, if they need to be edited, I can easily edit them in the Release Notes Manager GitHub Action itself

### CODE REVIEW

**Comment by mohamedAdhamc** [comment]
Hey @Ahmed-Khaled-dev

So a change in the title, or the description triggers a rerun. But would adding another commit to the PR also trigger a rerun ? Also do you think it could be possible to replace the original comment instead of making a new one ? I'm worried that maybe in some cases the bot could produce lots of unnecessary comments.

**Comment by Ahmed-Khaled-dev** [comment]
Hello @mohamedAdhamc

> But would adding another commit to the PR also trigger a rerun ?

No, nothing triggers a rerun except editing the title or description of the pull request (which are the only things in the pull requests that affect the release notes), I tested this now to confirm it, I tested all the following and they all don't trigger a rerun, adding commits, comments, labels, assignees, etc.

>Also do you think it could be possible to replace the original comment instead of making a new one? I'm worried that maybe in some cases the bot could produce lots of unnecessary comments.

At the time of creating this feature, I actually thought of the same idea. Still, I decided that since it doesn't comment except when the title or description is changed, then it wouldn't create any unnecessary comments and would give a nice interactive feel in the pull request, continuously showing the contributor and other people how his addition will look like in the release notes.

But since you mentioned it, I just checked if it's doable, and there doesn't seem to be a straightforward way to do it, but I am sure there is a workaround for it.

**Comment by mohamedAdhamc** [comment]
Screenshot from 2024-10-21 19-49-25

I just tested this and it looks good!

**Review by mohamedAdhamc — CHANGES_REQUESTED** [review]
Screenshot from 2024-10-21 19-51-46

I suggest changing the text to:
"
Thank you for contributing!
Below is how your contribution will appear in Synfig's release notes. Review it and improve your pull request's title and description so that your contribution is clear. You can add images, videos, and anything else you want. Have fun!
"

Just some punctuation/sentence structure changes. As this would show in every PR.

**Comment by Ahmed-Khaled-dev** [comment]
I agree, the new message looks better, let me know if you would also like me to edit the message that gets sent when they improve their pull request title or description:

image

"
Thank you for trying to improve your contribution description!
Below is how your updated contribution will look like in Synfig's release notes, review it and improve it till you are satisfied!
"

**Comment by mohamedAdhamc** [comment]
It looks good, just a few small edits.

Thank you for attempting to improve your contribution description! 
Below is how your updated contribution will appear in Synfig's release notes. Review it and make further improvements until you're satisfied!

Let me know when you do so. Because when that's done, I think everything else here looks good. I will approve it.

**Comment by Ahmed-Khaled-dev** [comment]
Done 👌🏻 

image

image

**Review by mohamedAdhamc — APPROVED** [review]
Looks good to me. Works as expected.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
