### PR TITLE
Create waveform Panel 

### PR DESCRIPTION
**Pull request by maitreyi0505**
issue #783 
https://github.com/synfig/synfig/issues/783

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hi @maitreyi0505! 
I made an attempt to compile your code and it failed with the following error:

```
g++ -DHAVE_CONFIG_H -I. -I/home/konstantin/sources/synfig/synfig-studio/src/gui -I../..  -I/home/konstantin/sources/synfig/synfig-studio/src  -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -pthread -D_REENTRANT -I/home/konstantin/sources/synfig/synfig-core/src -I/home/konstantin/sources/synfig/ETL -I/home/konstantin/sources/synfig/_production/build/include/ETL -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/OpenEXR -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/mlt++ -I/usr/include/mlt -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DIMAGE_DIR=\"/home/konstantin/sources/synfig/_production/build/share/pixmaps/synfigstudio\" -DIMAGE_EXT=\"png\" -DPLUGIN_DIR=\"/home/konstantin/sources/synfig/_production/build/share/synfig/plugins\" -DSOUND_DIR=\"/home/konstantin/sources/synfig/_production/build/share/synfig/sounds\" -DLOCALEDIR=\"/home/konstantin/sources/synfig/_production/build//locale\" -fdiagnostics-color=always -O2 -DNDEBUG -MT widgets/synfigstudio-widget_sound.o -MD -MP -MF widgets/.deps/synfigstudio-widget_sound.Tpo -c -o widgets/synfigstudio-widget_sound.o `test -f 'widgets/widget_sound.cpp' || echo '/home/konstantin/sources/synfig/synfig-studio/src/gui/'`widgets/widget_sound.cpp
/home/konstantin/sources/synfig/synfig-studio/src/gui/widgets/widget_sound.cpp:7:10: fatal error: fmt/format.h: No such file or directory
 #include <fmt/format.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:3090: recipe for target 'widgets/synfigstudio-widget_sound.o' failed
make[3]: *** [widgets/synfigstudio-widget_sound.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/konstantin/sources/synfig/synfig-studio/src/gui/docks/dock_sound.cpp:45:0:
/home/konstantin/sources/synfig/synfig-studio/src/gui/widgets/widget_sound.h:7:10: fatal error: fmt/format.h: No such file or directory
 #include <fmt/format.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:2152: recipe for target 'docks/synfigstudio-dock_sound.o' failed
make[3]: *** [docks/synfigstudio-dock_sound.o] Error 1
make[3]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-studio/src/gui'
Makefile:446: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-studio/src'
Makefile:716: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/konstantin/sources/synfig/_production/synfig-studio'
Makefile:531: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ankit-kumar-dwivedi** [comment]
hi, @maitreyi0505 still working on this?

**Comment by maitreyi0505** [comment]
Sorry, I couldn't proceed with the implementation of the idea

**Comment by ankit-kumar-dwivedi** [comment]
@maitreyi0505 That is alright you can still contribute to synfig let us know if you need any help.
We know it's difficult to start something new :) 
Closing this for now!

**Pull request closed without merging**
