### PR TITLE
Setting up VERSIONINFO resource for CMake Windows builds.

### PR DESCRIPTION
**Pull request by AYESDIE**
Fixes: #1412

image

Toolbar (not pinned):
image

Toolbar (pinned):
image

### CODE REVIEW

**Comment by AYESDIE** [comment]
These changes are on top of #1491.

**Comment by ice0** [comment]
Looks like ImageMagick issue on 32-bit:
```
synfig(2836) [11:44:33 AM] error: exception 'Magick: NoEncodeDelegateForThisImageFormat `MIFF' @ error/constitute.c/WriteImage/1212'
```
I will check it.

**Comment by AYESDIE** [comment]
But it built on this one https://ci.appveyor.com/project/Synfig/synfig/builds/34280912/job/oklgxdri30ssa096 I'll also check this out.

**Comment by AYESDIE** [comment]
The issue lies [here](https://github.com/synfig/synfig/blob/master/cmake/InstallMSYS2.cmake#L124). 
To reproduce this problem, if you comment that part out and try to build, it'll show those problems. Maybe some RegEx problem.

**Comment by AYESDIE** [comment]
Hopefully, #1595 should fix this. Once that's merged, I will rebase this on top of it.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
