### PR TITLE
feat: new Chroma Key layer

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by ice0** [comment]
I suggest to add a second pass and desaturate key color.

This is for example what I mean:
1) Original image
2) Key color removed
3) Key color desaturated


KeyExample4

[Original image](https://www.nyfa.edu/student-resources/wp-content/uploads/2014/07/81RyJJGWGmL._SL1500_-1024x1024.jpg)

**Comment by rodolforg** [comment]
Hmm.. @ice0 how could I do it? Does this feature already exist in Synfig/Cobra?

**Comment by ice0** [comment]
> Hmm.. @ice0 how could I do it?

On the image above, I just desaturated all the blues.
In your algorithm, you can desaturate the pixels selected by the key color. To desaturate, you need to convert the pixel to HSL/HSV color space and reduce the S part. 

More information you can find in [this discussion](https://stackoverflow.com/questions/13328029/how-to-desaturate-a-color).

You can also convert the color to YUV colorspace using the built-in methods in `synfig::Color` and [reduce U/V part](https://stackoverflow.com/questions/8427786/how-to-adjust-image-saturation-in-yuv-color-space), but it looks like it would be more complicated (I haven't tested it anyway, so I could be wrong).

> Does this feature already exist in Synfig/Cobra?

I don't know. I only see the `Color Correct` layer, but it doesn't look like what we need here.

**Comment by rodolforg** [comment]
Nice.

Sadly I couldn't get the same results :(
[test-chroma-key-with-desaturate.zip](https://github.com/synfig/synfig/files/8308706/test-chroma-key-with-desaturate.zip)

**Comment by rodolforg** [comment]
Whoops, force-pushed because I forgot to commit some lines.

**Comment by morevnaproject** [comment]
I have tested and it works great! Very useful feature!

Please rebase and resolve conflicts. ^__^

**Comment by rodolforg** [comment]
Rebased

**Comment by rodolforg** [comment]
Rebased again to fix commit titles. Should they be squashed?

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
> Rebased again to fix commit titles. Should they be squashed?

Looks good to me. Merged, thank you!

**Pull request merged**
