### PR TITLE
fix: recent file list is reversing every time Synfig Studio launches

### PR DESCRIPTION
**Pull request by rodolforg**
mistake done in 4f1bd3d9d8 (#3229)

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by rodolforg** [comment]
@ice0 something is wrong with macOS jobs...
From 18h30 UTC to 19h00 UTC Github was down and since then the macOS jobs can't run...

**Comment by ice0** [comment]
> @ice0 something is wrong with macOS jobs... From 18h30 UTC to 19h00 UTC Github was down and since then the macOS jobs can't run...

Hi, Rodolfo!

Yes, Github reported outages, so I thought that the long build on a macOS was related to this.
In fact, Homebrew stopped supporting MacOS 11, so I bumped up the macOS version on Github CI.
Related PR: https://github.com/synfig/synfig/pull/3259

**Comment by ice0** [comment]
@rodolforg 
Please rebase.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
